"""cir — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import numpy as np
import plotly.graph_objects as go


def compute_cir_from_results(results: dict, dt_ns: float = 0.1) -> dict:
    paths = (
        results.get("los_paths", [])          # direct SBR rays
        + [p for p in results["nlos_paths"] if p["bounces"] == 0]  # analytic LOS
        + [p for p in results["nlos_paths"] if p["bounces"] > 0]   # multipath
    )
    if not paths:
        return {"time_ns": np.array([]), "h_complex": np.array([]), "power_db": np.array([])}
    # rest unchanged

    delays = np.array([p["ritardo_assoluto_ns"] for p in paths])
    campos = np.array([p["campo_complesso"]      for p in paths], dtype=np.complex128)

    t_max  = delays.max() + 10.0
    t_axis = np.arange(0.0, t_max, dt_ns)
    h      = np.zeros(len(t_axis), dtype=np.complex128)

    idx = np.round(delays / dt_ns).astype(int)
    valid = (idx >= 0) & (idx < len(h))
    np.add.at(h, idx[valid], campos[valid])

    power_db = 20.0 * np.log10(np.abs(h) + 1e-30)
    
    return {"time_ns": t_axis, "h_complex": h, "power_db": power_db}


def plot_cir_dictionary(results: dict, noise_floor_db: float = -120.0):
    """
    Takes the exact dictionary output from compute_cir_from_results 
    and plots it as a digital stem plot (Power Delay Profile).
    """

    cir_dictionary = compute_cir_from_results(results, dt_ns=0.1)

    # 1. Extract the exact arrays your function built
    t_axis = cir_dictionary["time_ns"]
    pwr_db = cir_dictionary["power_db"]
    
    if len(t_axis) == 0:
        print("[CIR PLOT] The dictionary is empty. No rays reached the RX.")
        return

    # 2. Clamp the -600 dB empty bins (from the 1e-30 addition) to our noise floor
    plot_pwr = np.clip(pwr_db, a_min=noise_floor_db, a_max=None)
    
    fig = go.Figure()

    # 3. Create the "stems" dropping down to the noise floor
    fig.add_trace(go.Bar(
        x=t_axis,
        y=plot_pwr - noise_floor_db,         
        base=noise_floor_db,                 
        width=t_axis[1] - t_axis[0] if len(t_axis) > 1 else 0.1, 
        marker_color="dodgerblue",
        marker_line_width=0,                 
        name="Received Power"
    ))

    # 4. Put red dots exactly on the signal peaks
    valid_peaks = pwr_db > noise_floor_db
    fig.add_trace(go.Scatter(
        x=t_axis[valid_peaks],   
        y=pwr_db[valid_peaks],
        mode="markers",
        marker=dict(color="red", size=6),
        name="Multipath Arrivals"
    ))

    # 5. Dynamic Y-axis scaling based on your strongest ray
    max_pwr = np.max(pwr_db) if np.any(valid_peaks) else noise_floor_db + 10
    y_top = max_pwr + 10.0 

    fig.update_layout(
        title="Channel Impulse Response (CIR)",
        xaxis_title="Absolute Delay (ns)",
        yaxis_title="Power (dB)",
        yaxis=dict(range=[noise_floor_db, y_top]),
        xaxis=dict(range=[max(0, t_axis[0] - 2), t_axis[-1] + 2]),
        template="plotly",
        showlegend=True,
        hovermode="x unified"
    )

    fig.show()
