"""constants — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations


S_MIN_MAGNITUDE  = 1e-7


MAX_PATH_DIST    = 1e8


SELF_INTERSECT_EPSILON = 0.05


NORMAL_OFFSET    = 1e-7


C_LIGHT = 299_792_458.0
    

_OCCLUSION_SLACK = 0.05
