"""diffraction — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import numpy as np
from em_core import fresnel


def extract_diffraction_edges(mesh, min_angle=30, max_angle=179.9):
    diff_edges = []
    face_pairs = mesh.face_adjacency         
    adj_edges = mesh.face_adjacency_edges    
    
    normals_left = mesh.face_normals[face_pairs[:, 0]]
    normals_right = mesh.face_normals[face_pairs[:, 1]]
    
    cos_angles = np.clip(np.einsum('ij,ij->i', normals_left, normals_right), -1.0, 1.0)
    angles = np.degrees(np.arccos(cos_angles))
    
    valid_mask = (angles >= min_angle) & (angles <= max_angle)
    valid_edge_indices = adj_edges[valid_mask]
    
    valid_pairs = face_pairs[valid_mask]
    valid_normals_left = normals_left[valid_mask]
    valid_normals_right = normals_right[valid_mask]
    
    for idx, edge in enumerate(valid_edge_indices):
        p0 = mesh.vertices[edge[0]]
        p1 = mesh.vertices[edge[1]]
        
        edge_vec = p1 - p0
        edge_len = np.linalg.norm(edge_vec)
        
        if edge_len > 1e-5: 
            # --- DYNAMIC CONVEXITY TEST ---
            face0_nodes = mesh.faces[valid_pairs[idx, 0]]
            
            # Find the vertex in Face 0 that is NOT part of the diffraction edge
            v_other_idx = [v for v in face0_nodes if v not in edge][0]
            p_other = mesh.vertices[v_other_idx]
            
            # Vector pointing into Face 0 from the edge origin
            vec_in_face0 = p_other - p0
            
            # If Face 0 bends AGAINST Face 1's normal -> Convex outer corner
            # If Face 0 bends TOWARD Face 1's normal -> Concave inner corner
            is_convex = bool(np.dot(vec_in_face0, valid_normals_right[idx]) <= 1e-5)
            
            diff_edges.append({
                'p0': p0, 
                'p1': p1,
                'dir': edge_vec / edge_len,
                'len': edge_len,
                'n0': valid_normals_left[idx],
                'n1': valid_normals_right[idx],
                'is_convex': is_convex   # <-- Store the flag
            })
            
    print(f"[PRE-PROCESSING] Mesh analizzata. Trovati {len(diff_edges)} spigoli di diffrazione validi.")
    return diff_edges


def generate_keller_cone_rays(hit_point, incoming_dir, edge_dir, n0, n1, is_convex, num_diff_rays=360):
    # 1. Normalize
    incoming_dir = incoming_dir / np.linalg.norm(incoming_dir)
    edge_dir     = edge_dir / np.linalg.norm(edge_dir)

    # 2. Calculate beta_0 (Angle between incident ray and edge)
    # Do NOT flip edge_dir. Allow cos_beta_0 to be negative if the incident 
    # ray is coming from the "opposite" direction.
    cos_beta_0 = np.clip(np.dot(incoming_dir, edge_dir), -1.0, 1.0)
    beta_0     = np.arccos(cos_beta_0)  

    # 3. Create local orthonormal basis
    z_axis    = edge_dir
    cross_vec = np.cross(incoming_dir, z_axis)
    
    # Handle grazing incidence along the edge
    if np.linalg.norm(cross_vec) < 1e-9:
        return []

    x_axis = cross_vec / np.linalg.norm(cross_vec)
    y_axis = np.cross(z_axis, x_axis)

    EPSILON    = 1e-4
    child_rays = []
    
    # Generate the full sweep
    angles = np.linspace(0, 2 * np.pi, num_diff_rays, endpoint=False)

    for alpha in angles:
        # The cone equation works perfectly whether beta_0 is acute or obtuse
        ray_dir = (np.sin(beta_0) * np.cos(alpha) * x_axis +
                   np.sin(beta_0) * np.sin(alpha) * y_axis +
                   np.cos(beta_0) * z_axis)
        
        ray_dir = ray_dir / np.linalg.norm(ray_dir)

        # Removed the global Z-culling bug here!

        dot_n0 = np.dot(ray_dir, n0)
        dot_n1 = np.dot(ray_dir, n1)

        # --- APPLY TOPOLOGY-AWARE CULLING ---
        if is_convex:
            # Convex: Valid if in front of AT LEAST ONE face
            if dot_n0 >= -EPSILON or dot_n1 >= -EPSILON:
                child_rays.append(ray_dir)
        else:
            # Concave: Valid ONLY if in front of BOTH faces
            if dot_n0 >= -EPSILON and dot_n1 >= -EPSILON:
                child_rays.append(ray_dir)

    return child_rays


def inject_keller_children(
    batch:                  RayBatch,
    edge_local_idx:         np.ndarray,
    active_global_idx:      np.ndarray,
    edge_pts:               np.ndarray,
    edge_dirs:              np.ndarray,
    incoming_dirs:          np.ndarray,
    edge_starts:            np.ndarray,
    edge_ends:              np.ndarray,
    edge_is_convex:         np.ndarray,  # <--- NEW: The missing keyword argument
    k_wave:                 float,
    keller_events:          list,
    generate_keller_cone_rays: Callable,
    num_diff_rays:          int,
    edge_n0:                np.ndarray,  
    edge_n1:                np.ndarray,  
) -> None:
    """
    For each ray that hit a diffraction edge, generate Keller cone children
    and append them to `batch` via RayBatch.append_rays().

    Fixes vs original:
      1. beta_0 uses abs(cos_beta) so the half-angle is always in [0, pi/2].
      2. dist_acc_child is computed by walking ph_child waypoints, not from
         batch.dist_acc[gi], which is stale for edge-killed rays (they never
         pass through the Fresnel reflect block where dist_acc is incremented).
      3. The diffraction edge event is appended to cronologia so it appears
         in dettaglio_rimbalzi at print time, with beta_0, |D|, and phase.
    """
    B2 = batch.path_hist.shape[1]

    new_origins_l    = []
    new_dirs_l       = []
    parent_S_l       = []
    new_bounce_l     = []
    new_diffracted_l = []
    new_dist_acc_l   = []
    new_ph_l         = []
    new_pl_l         = []
    new_fi_l         = []
    new_cr_l         = []
    parent_idx_l     = []

    for k, li in enumerate(edge_local_idx):
        gi     = int(active_global_idx[li])
        ep     = edge_pts[k]
        ed     = edge_dirs[k].astype(np.float64)
        ed     = ed / np.linalg.norm(ed)          # ensure unit vector
        inc    = incoming_dirs[k].astype(np.float64)
        inc    = inc / np.linalg.norm(inc)
        estart = edge_starts[k]
        eend   = edge_ends[k]
        n0     = edge_n0[k].astype(np.float64) # <-- Fetch normal A
        n1     = edge_n1[k].astype(np.float64) # <-- Fetch normal B
        is_cvx = bool(edge_is_convex[k])

        MIN_EDGE_DIST_WAVELENGTHS = 2.0  # standard rule of thumb

        # ── Diffraction coefficient ───────────────────────────────────
        cos_beta = np.clip(np.dot(inc, ed), -1.0, 1.0)
        beta_0   = np.arccos(abs(cos_beta))       # always in [0, pi/2]

        D_coef = compute_scalar_gtd_coefficient(k_wave, beta_0)

        # Skip degenerate grazing hits — D=0 returned by the coefficient fn
        if abs(D_coef) == 0.0:
            continue

        parent_S_val = complex(batch.S_real[gi]) + 1j * complex(batch.S_imag[gi])
        diffracted_S = parent_S_val * D_coef

        child_dirs = generate_keller_cone_rays(ep, inc, ed, n0, n1, is_cvx, num_diff_rays=num_diff_rays)
        if not child_dirs:
            continue
    
        # ── Build path history for children ──────────────────────────
        pl_parent = int(batch.path_len[gi])   # slots 0..pl_parent-1 are filled
                                               # slot 0 = TX origin
        new_pl    = min(pl_parent + 1, B2)    # +1 for the edge point

        ph_child = np.zeros((B2, 3), dtype=np.float32)
        ph_child[:pl_parent, :] = batch.path_hist[gi, :pl_parent, :]
        if pl_parent < B2:
            ph_child[pl_parent, :] = ep.astype(np.float32)

            # In inject_keller_children, after computing ep:
        if pl_parent > 1:  # there was a prior reflection
            last_reflection = batch.path_hist[gi, pl_parent - 1, :].astype(np.float64)
            dist_refl_to_edge = np.linalg.norm(ep - last_reflection)
            min_valid_dist = MIN_EDGE_DIST_WAVELENGTHS * (2 * np.pi / k_wave)
            if dist_refl_to_edge < min_valid_dist:
                continue  # too close to edge, GTD not valid here

        # ── FIX 2: compute TX→edge distance from waypoints ───────────
        # Cannot use batch.dist_acc[gi] — edge-killed rays skip the Fresnel
        # reflect block where dist_acc is normally incremented, so it still
        # holds the value from the previous bounce (or 0 for first-leg hits).
        waypoints = ph_child[:new_pl, :].astype(np.float64)   # (new_pl, 3)
        if new_pl >= 2:
            segs           = np.diff(waypoints, axis=0)        # (new_pl-1, 3)
            dist_acc_child = float(np.sum(np.linalg.norm(segs, axis=1)))
        else:
            dist_acc_child = 0.0

        # ── FIX 3: append edge event to cronologia ────────────────────
        parent_cr = list(batch.cronologia[gi])
        parent_cr.append({
            "num_rimbalzo":         int(batch.bounce[gi]) + 1,
            "face_id":              "Edge",
            "punto_impatto":        ep.astype(np.float64).copy(),
            "angolo_incidenza_deg": float(np.degrees(beta_0)),
            "tipo":                 "diffraction",
            "edge_dir":             ed.copy(),
            "D_coef_mag":           float(abs(D_coef)),
            "D_coef_phase_deg":     float(np.degrees(np.angle(D_coef))),
            # ── Metadata for exact UTD evaluation at RX capture ──────────
            "incident_dir":         inc.copy(),          # ray dir hitting edge
            "edge_n0":              n0.copy(),           # wedge face A normal
            "edge_n1":              n1.copy(),           # wedge face B normal
            "is_convex":            bool(is_cvx),        # wedge convexity flag
            "s_prime":              float(dist_acc_child),  # TX→edge distance
        })

        # ── Keller event log ──────────────────────────────────────────
        keller_events.append({
            "trigger_ray_id":  gi,
            "bounce_occurred": int(batch.bounce[gi]),
            "hit_point":       ep.copy(),
            "edge_dir":        ed.copy(),
            "incoming_dir":    inc.copy(),
            "beta_0_deg":      float(np.degrees(beta_0)),
            "D_coef_mag":      float(abs(D_coef)),
            "child_dirs":      [cd.copy() for cd in child_dirs],
            "path_to_edge":    list(batch.path_hist[gi, :pl_parent, :]) + [ep.copy()],
            "edge_start":      estart.copy(),
            "edge_end":        eend.copy(),
            "dist_to_edge":    dist_acc_child,
        })

        parent_fi = list(batch.face_ids[gi]) + ["Edge"]

        for cd in child_dirs:
            new_origins_l.append(ep + cd * 1e-5)
            new_dirs_l.append(cd)
            parent_S_l.append(diffracted_S)
            new_bounce_l.append(int(batch.bounce[gi]) + 1)
            new_diffracted_l.append(True)
            new_dist_acc_l.append(dist_acc_child)
            new_ph_l.append(ph_child.copy())
            new_pl_l.append(new_pl)
            new_fi_l.append(parent_fi)
            new_cr_l.append(list(parent_cr))   # each child gets its own copy
            parent_idx_l.append(gi)

    if not new_origins_l:
        return

    M  = len(new_origins_l)
    ph = np.stack(new_ph_l, axis=0)            # (M, B2, 3)

    batch.append_rays(
        new_origins    = np.array(new_origins_l,    dtype=np.float32),
        new_dirs       = np.array(new_dirs_l,       dtype=np.float32),
        parent_indices = np.array(parent_idx_l,     dtype=np.int32),
        parent_S       = np.array(parent_S_l,       dtype=np.complex64),
        new_bounce     = np.array(new_bounce_l,     dtype=np.int32),
        new_diffracted = np.array(new_diffracted_l, dtype=bool),
        new_dist_acc   = np.array(new_dist_acc_l,   dtype=np.float32),
        new_path_hist  = ph,
        new_path_len   = np.array(new_pl_l,         dtype=np.int32),
        new_face_ids   = new_fi_l,
        new_cronologia = new_cr_l,
    )


def compute_scalar_gtd_coefficient(k: float, beta_0: float) -> complex:
    """
    Computes a simplified isotropic Keller GTD diffraction coefficient.
    k: Wavenumber (2 * pi / wavelength)
    beta_0: Angle of incidence relative to the edge vector (radians)
    """
    # Prevent division by zero if ray is perfectly parallel to edge
    sin_beta = max(np.sin(beta_0), 1e-3)
    
    # Keller GTD magnitude scaling: inversely proportional to sqrt(k)
    # The 2.0 factor is an isotropic heuristic representing a 90-deg wedge average
    D_mag = 1.0 / (2.0 * np.sqrt(2.0 * np.pi * k) * sin_beta)
    
    # Diffraction introduces a characteristic -45 degree phase shift
    D_phase = -np.pi / 4.0 
    
    return D_mag * np.exp(1j * D_phase)


def fresnel_transition_function(x):
    """Kouyoumjian-Pathak transition function. x is real, >= 0."""
    x = np.asarray(x, dtype=np.float64)
    x = np.maximum(x, 0.0)
    sqrt_x = np.sqrt(x)
    # scipy.special.fresnel(t) returns (S(t), C(t)) with
    #   C(t)=Int_0^t cos(pi u^2/2) du , S(t)=Int_0^t sin(pi u^2/2) du
    # Substituting tau = sqrt(pi/2) u gives
    #   Int_{sqrt(x)}^inf e^{-j tau^2} d tau
    #     = sqrt(pi/2) [ (1/2 - C(t)) - j (1/2 - S(t)) ],  t = sqrt(2x/pi)
    t = np.sqrt(2.0 * x / np.pi)
    S, C = fresnel(t)
    tail = np.sqrt(np.pi / 2.0) * ((0.5 - C) - 1j * (0.5 - S))
    return 2j * sqrt_x * np.exp(1j * x) * tail


def _cot_transition_term(beta, n, kL, sign):
    """sign = +1 uses (pi+beta) and a+; sign = -1 uses (pi-beta) and a-."""
    pi = np.pi
    # Integer N that brings (2 n pi N - beta) closest to +-pi
    if sign > 0:   # a+  ->  2 n pi N - beta = +pi
        N = round((pi + beta) / (2.0 * n * pi))
    else:          # a-  ->  2 n pi N - beta = -pi
        N = round((-pi + beta) / (2.0 * n * pi))

    a = 2.0 * np.cos((2.0 * n * pi * N - beta) / 2.0) ** 2
    x = kL * a

    cot_arg = (pi + sign * beta) / (2.0 * n)
    eps = 1e-6
    s = np.sin(cot_arg)

    if abs(s) < eps:
        # ---- Boundary limit: cot(arg) F(x) is finite as arg -> m*pi ----
        # epsilon_dev is the signed angular distance to the boundary.
        # (2 n pi N - beta) - sign*pi  ~  -sign * eps_dev
        eps_dev = (2.0 * n * pi * N - beta) - sign * pi
        # McNamara limiting form (s,h share it; sign of sqrt term = sign(eps))
        sgn = 1.0 if eps_dev >= 0 else -1.0
        term = (np.sqrt(2.0 * pi * kL) * sgn
                - 2.0 * kL * eps_dev * np.exp(1j * pi / 4.0)) * np.exp(1j * pi / 4.0)
        return n * term
    else:
        return (np.cos(cot_arg) / s) * fresnel_transition_function(x)


def fresnel_reflection_coeffs(eps_r_complex, grazing_angle):
    """Return (R_soft_TE, R_hard_TM) for a wave grazing a lossy dielectric.

    eps_r_complex : complex relative permittivity  eps_r - j sigma/(w eps0).
    grazing_angle : angle between ray and the surface plane [rad], in [0, pi/2].
    """
    # angle from the surface NORMAL
    theta = np.pi / 2.0 - grazing_angle
    ct = np.cos(theta)
    st = np.sin(theta)
    root = np.sqrt(eps_r_complex - st * st)

    # TE (perpendicular / "soft"):  R = (cos - root)/(cos + root)
    R_te = (ct - root) / (ct + root)
    # TM (parallel / "hard"):       R = (eps cos - root)/(eps cos + root)
    R_tm = (eps_r_complex * ct - root) / (eps_r_complex * ct + root)
    return R_te, R_tm


def lunar_eps_complex(freq_hz, eps_r=2.87, sigma=0.00169):
    """Complex relative permittivity of lunar regolith at a given frequency."""
    eps0 = 8.8541878128e-12
    w = 2.0 * np.pi * freq_hz
    return eps_r - 1j * sigma / (w * eps0)


def compute_utd_wedge_coefficient(
    k: float,
    beta_0: float,
    phi_i: float,
    phi_d: float,
    n: float,
    s_prime: float,
    s: float,
    polarization: str = "soft",
    eps_r_complex: complex | None = None,
) -> complex:
    """Kouyoumjian-Pathak UTD wedge diffraction coefficient.

    Parameters
    ----------
    k        : wavenumber 2 pi / lambda.
    beta_0   : angle between incident ray and the edge [rad], in (0, pi/2].
    phi_i    : incidence angle measured from the '0' face, in the plane
               perpendicular to the edge [rad], 0 <= phi_i <= n*pi.
    phi_d    : diffraction (observation) angle, same convention [rad].
    n        : wedge exterior-angle parameter, exterior angle = n*pi (1<=n<=2).
    s_prime  : source-to-edge distance [m].
    s        : edge-to-field-point distance [m].
    polarization : 'soft' (TE) or 'hard' (TM). Ignored if eps_r_complex given
                   (then the lossy Luebbers form is used, returning the soft
                   and hard blend via the supplied reflection coefficients).
    eps_r_complex : if provided, use the Luebbers lossy-wedge weighting on the
                    reflection-boundary terms (lunar soil). If None, ideal
                    PEC-style +-1 weighting (classic soft/hard K-P).

    Returns
    -------
    Complex scalar diffraction coefficient D (units of sqrt(length)).
    """
    sin_b0 = max(np.sin(beta_0), 1e-3)

    # Distance parameter for an astigmatic (spherical) incident wave
    L = (s * s_prime / (s + s_prime)) * sin_b0 * sin_b0
    kL = k * L

    d_phi = phi_d - phi_i      # incidence-related (diffraction-boundary) terms
    s_phi = phi_d + phi_i      # reflection-related terms

    # The two incidence (transmission) terms -- always +1 weighted
    T1 = _cot_transition_term(d_phi, n, kL, sign=+1)
    T2 = _cot_transition_term(d_phi, n, kL, sign=-1)

    # The two reflection terms
    R1 = _cot_transition_term(s_phi, n, kL, sign=+1)   # 'n'-face reflection
    R2 = _cot_transition_term(s_phi, n, kL, sign=-1)   # '0'-face reflection

    common = -np.exp(-1j * np.pi / 4.0) / (2.0 * n * np.sqrt(2.0 * np.pi * k) * sin_b0)

    if eps_r_complex is None:
        # Classic perfectly-reflecting wedge: soft = (-), hard = (+)
        refl_sign = -1.0 if polarization == "soft" else +1.0
        D = common * (T1 + T2 + refl_sign * (R1 + R2))
    else:
        # Luebbers lossy dielectric wedge: weight each reflection term by the
        # Fresnel reflection coefficient at the corresponding grazing angle.
        # Grazing angles seen by the reflected rays at the two faces:
        graze_n = beta_0 if False else max(np.sin(beta_0) * abs(np.sin(s_phi / 2.0)), 0.0)
        # Use physically meaningful grazing angles on each face:
        graze_0face = abs(phi_i)                 # off the illuminated '0' face
        graze_nface = abs(n * np.pi - phi_i)     # off the 'n' face
        R_te_0, R_tm_0 = fresnel_reflection_coeffs(eps_r_complex, np.clip(graze_0face, 0, np.pi / 2))
        R_te_n, R_tm_n = fresnel_reflection_coeffs(eps_r_complex, np.clip(graze_nface, 0, np.pi / 2))
        if polarization == "soft":
            R0w, Rnw = R_te_0, R_te_n
        else:
            R0w, Rnw = R_tm_0, R_tm_n
        # T-terms unchanged; R-terms weighted by the face reflection coeffs
        D = common * (T1 + T2 + Rnw * R1 + R0w * R2)

    return D


def utd_edge_geometry(edge_dir, n0, n1, incoming_dir, diffracted_dir, is_convex):
    """Compute the four UTD angles for one (incoming, diffracted) ray pair.

    Convention: phi is measured in the plane perpendicular to the edge, from
    the '0' face surface, increasing through the exterior region. phi_i uses
    the direction back toward the source; phi_d uses the diffracted direction.
    If your mesh winds faces oppositely you may need to swap n0<->n1.
    """
    t = edge_dir / np.linalg.norm(edge_dir)
    inc = incoming_dir / np.linalg.norm(incoming_dir)
    dif = diffracted_dir / np.linalg.norm(diffracted_dir)

    # beta_0 : angle the incident ray makes with the edge (oblique factor)
    beta_0 = np.arccos(np.clip(abs(np.dot(inc, t)), 0.0, 1.0))
    beta_0 = max(beta_0, 1e-3)

    # Local cross-section frame from the '0' face.
    u0 = np.cross(n0, t)                       # surface tangent of face0, perp to edge
    nu = np.linalg.norm(u0)
    if nu < 1e-9:
        u0 = np.cross(n1, t); nu = np.linalg.norm(u0)
    u0 = u0 / nu
    v0 = np.cross(t, u0)                        # completes right-handed (u0, v0, t)

    def _angle(vec):
        p = vec - np.dot(vec, t) * t            # project into plane perp to edge
        pn = np.linalg.norm(p)
        if pn < 1e-9:
            return 0.0
        p = p / pn
        a = np.arctan2(np.dot(p, v0), np.dot(p, u0))
        return a % (2.0 * np.pi)

    phi_i = _angle(-inc)                         # direction back toward source
    phi_d = _angle(dif)                          # direction toward observer

    # Wedge exterior-angle parameter from the inter-face angle.
    delta = np.arccos(np.clip(np.dot(n0, n1), -1.0, 1.0))   # angle between normals
    n = (1.0 + delta / np.pi) if is_convex else max(1.0 - delta / np.pi, 1.0)

    return beta_0, phi_i, phi_d, float(n)


def _utd_coeff_for_capture(cronologia, pos_rx, s_prime, s_child, k, eps_luna,
                           polarization="soft", use_lossy=False):
    """Evaluate the UTD wedge diffraction coefficient for a captured ray.

    Pulls the diffraction event from the ray's `cronologia`, reconstructs the
    EXACT edge->RX direction (rather than the discretized Keller-cone child),
    and returns the complex coefficient D. Falls back to 1+0j (no attenuation)
    if the record is missing or the geometry is degenerate.

    use_lossy=True activates the Luebbers finite-conductivity weighting using
    `eps_luna`; default False uses the ideal (validated K-P) soft/hard form.
    """
    de = next((b for b in cronologia if b.get("tipo") == "diffraction"), None)
    if de is None or "edge_n0" not in de:
        return 1.0 + 0.0j
    edge_pt  = np.asarray(de["punto_impatto"], dtype=np.float64)
    diff_dir = np.asarray(pos_rx, dtype=np.float64) - edge_pt
    nrm = np.linalg.norm(diff_dir)
    if nrm < 1e-9:
        return 1.0 + 0.0j
    diff_dir /= nrm
    beta0, phi_i, phi_d, n_wedge = utd_edge_geometry(
        np.asarray(de["edge_dir"],     dtype=np.float64),
        np.asarray(de["edge_n0"],      dtype=np.float64),
        np.asarray(de["edge_n1"],      dtype=np.float64),
        np.asarray(de["incident_dir"], dtype=np.float64),
        diff_dir,
        bool(de["is_convex"]),
    )
    D = complex(compute_utd_wedge_coefficient(
        k, beta0, phi_i, phi_d, n_wedge,
        s_prime=max(float(s_prime), 1e-6),
        s=max(float(s_child), 1e-6),
        polarization=polarization,
        eps_r_complex=(eps_luna if use_lossy else None),
    ))
    if not (np.isfinite(D.real) and np.isfinite(D.imag)):
        return 1.0 + 0.0j
    return D


def _cronologia_with_utd(cronologia, D_utd):
    """Return a copy of the ray's cronologia in which each diffraction event's
    coefficient (|D| and phase) is replaced by the actual UTD value used at
    capture. Without this, the detailed printout would still show the stale
    spawn-time scalar coefficient. The original batch dicts are not mutated.
    """
    out = []
    for b in cronologia:
        if b.get("tipo") == "diffraction":
            b2 = dict(b)
            b2["D_coef_mag"]       = float(abs(D_utd))
            b2["D_coef_phase_deg"] = float(np.degrees(np.angle(D_utd)))
            out.append(b2)
        else:
            out.append(b)
    return out
