"""em_core — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import numpy as np
import trimesh
import pandas as pd
from scipy.interpolate import RegularGridInterpolator


def fresnel(dir_in, dir_out, normal, epsilon):
    """
    Calcola la matrice di propagazione 3x3 di Fresnel per una riflessione.

    Args:
        dir_in  : direzione del raggio incidente (3,)
        dir_out : direzione del raggio riflesso  (3,)
        normal  : normale alla superficie (deve puntare verso la sorgente)
        epsilon : costante dielettrica relativa complessa

    Returns:
        P : matrice complessa 3x3 che trasforma E_in in E_out
    """
    k_in  = dir_in  / np.linalg.norm(dir_in)
    k_out = dir_out / np.linalg.norm(dir_out)
    n_hat = normal  / np.linalg.norm(normal)

    # Asse TE (s — trasverso elettrico, perpendicolare al piano di incidenza)
    s = np.cross(k_in, n_hat)
    s_norm = np.linalg.norm(s)

    if s_norm < 1e-9:
        # Incidenza normale: sceglie un asse di riferimento arbitrario
        ref = np.array([1.0, 0.0, 0.0])
        if abs(np.dot(ref, k_in)) > 0.9:
            ref = np.array([0.0, 1.0, 0.0])
        s = np.cross(k_in, ref)

    s /= np.linalg.norm(s)

    # Assi TM (p — trasverso magnetico, nel piano di incidenza)
    p_in  = np.cross(k_in,  s)
    p_out = np.cross(k_out, s)

    M_in  = np.column_stack((s, p_in,  k_in))
    M_out = np.column_stack((s, p_out, k_out))

    # Angolo di incidenza (sempre positivo)
    cos_theta  = abs(np.dot(k_in, n_hat))
    sin2_theta = 1 - cos_theta**2

    # Coefficienti di Fresnel
    g  = np.sqrt(epsilon - sin2_theta + 0j)
    Rs = (cos_theta - g)           / (cos_theta + g)
    Rp = (epsilon * cos_theta - g) / (epsilon * cos_theta + g)

    # Componente lungo k azzerata (non fisica in un'onda TEM)
    F = np.diag([Rs, Rp, 0.0]).astype(complex)

    # np.linalg.inv invece di .T — corretto anche se M_in non è esattamente ortonormale
    return M_out @ F @ np.linalg.inv(M_in)


def build_polarization(pol_type: str, direction: np.ndarray) -> np.ndarray:
    k = direction / np.linalg.norm(direction)

    # Per polarizzazioni lineari: vettori globali fissi
    pol_linear = {
        "linear_x":  np.array([1.0, 0.0, 0.0], dtype=complex),
        "linear_y":  np.array([0.0, 1.0, 0.0], dtype=complex),
        "linear_45": np.array([1.0, 1.0, 0.0], dtype=complex) / np.sqrt(2),
    }

    if pol_type in pol_linear:
        vec = pol_linear[pol_type]
        longitudinal = np.abs(np.dot(vec, k))
        if longitudinal > 0.1:
            raise ValueError(
                f"Polarizzazione '{pol_type}' ha componente longitudinale {longitudinal:.4f} "
                f"rispetto alla direzione {direction}.\n"
                f"Scegli una polarizzazione trasversa al raggio."
            )
        elif longitudinal > 1e-6:
            vec = vec - np.dot(vec, k) * k
        return vec / np.linalg.norm(vec)

    # Per RHCP/LHCP: base locale ortogonale al raggio (sempre valida)
    if pol_type in ("rhcp", "lhcp"):
        ref = np.array([0.0, 1.0, 0.0])
        if abs(np.dot(ref, k)) > 0.9:
            ref = np.array([0.0, 0.0, 1.0])
        x_t = np.cross(k, ref);  x_t /= np.linalg.norm(x_t)
        y_t = np.cross(k, x_t);  y_t /= np.linalg.norm(y_t)
        if pol_type == "rhcp":
            return (x_t - 1j * y_t) / np.sqrt(2)
        else:
            return (x_t + 1j * y_t) / np.sqrt(2)

    raise ValueError(
        f"Polarizzazione '{pol_type}' non riconosciuta.\n"
        f"Opzioni valide: linear_x, linear_y, linear_45, rhcp, lhcp"
    )


def vec_fresnel_scalar(
    incident: np.ndarray,   # (M, 3) unit vectors
    normals:  np.ndarray,   # (M, 3) unit vectors, already facing incident
    epsilon:  complex,
) -> np.ndarray:            # (M,) complex reflection coefficients
    """
    Vectorized scalar Fresnel:  R = (R_TE + R_TM) / 2
    All M rays computed in a single NumPy pass — no Python loop.
    """
    cos_t  = np.clip(np.abs(np.einsum('ij,ij->i', incident, normals)), 0.0, 1.0)
    sin2   = np.clip(1.0 - cos_t ** 2, 0.0, 1.0)
    sq     = np.sqrt(epsilon - sin2.astype(complex))   # (M,) complex
    R_TE   = (cos_t - sq) / (cos_t + sq)
    R_TM   = (epsilon * cos_t - sq) / (epsilon * cos_t + sq)
    return (R_TE + R_TM) / 2.0


def fresnel_polarized(k_in, k_out, n, epsilon, E_in, R_TE, R_TM):
    # 1. Asse Perpendicolare (TE o 'n')
    cross_kn = np.cross(k_in, n)
    norm_cross = np.linalg.norm(cross_kn)
    
    # [TRUCCO DA INGEGNERE] Se il raggio cade perfettamente perpendicolare, 
    # il cross product è 0. Dobbiamo forzare un asse arbitrario.
    if norm_cross < 1e-12:
        e_in_n = np.array([1.0, 0.0, 0.0]) if abs(k_in[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    else:
        e_in_n = cross_kn / norm_cross

    # 2. Assi Paralleli (TM o 'p')
    e_in_p = np.cross(e_in_n, k_in)
    e_out_p = np.cross(e_in_n, k_out)
    
    # e_out_n è identico a e_in_n, non serve ricalcolarlo
    e_out_n = e_in_n 

    # 3. Matrici
    # Impilando come righe otteniamo automaticamente l'inversa M^-1
    M_in_inv = np.array([e_in_p, e_in_n, k_in])
    
    # La matrice di ricostruzione deve avere i vettori come colonne, quindi usiamo .T (Transpose)
    M_out = np.array([e_out_p, e_out_n, k_out]).T 

    P = np.array([
        [R_TM, 0.0, 0.0],
        [0.0, R_TE, 0.0],
        [0.0,  0.0, 1.0]
    ])
    
    # 4. Moltiplicazione MATRICIALE vera e propria con l'operatore @
    E_out = M_out @ P @ M_in_inv @ E_in
    
    return E_out


def sionna_hv_basis(ray_dir, boresight, up):
    """
    Sionna-style local spherical H/V basis for a ray direction.

    Local device frame:
        local x = boresight
        local z = up, projected orthogonal to boresight
        local y = z x x

    Sionna antenna basis:
        V = theta_hat
        H = phi_hat

    Parameters
    ----------
    ray_dir : array-like, shape (3,)
        Direction at which the antenna pattern is evaluated.
        TX: propagation/departure direction.
        RX: came-from direction, i.e. -arrival_travel_direction.

    boresight : array-like, shape (3,)
        Device local +x axis in global coordinates.

    up : array-like, shape (3,)
        Device local +z axis reference in global coordinates.

    Returns
    -------
    h_global, v_global : np.ndarray
        Sionna-style H and V polarization basis vectors in global coordinates.
    """
    import numpy as np

    def _norm(v):
        v = np.asarray(v, dtype=np.float64)
        n = np.linalg.norm(v)
        if n < 1e-12:
            raise ValueError("Zero-length vector in sionna_hv_basis()")
        return v / n

    # Sionna device local axes in global coordinates
    x_hat = _norm(boresight)

    up = np.asarray(up, dtype=np.float64)
    z_hat = up - np.dot(up, x_hat) * x_hat

    if np.linalg.norm(z_hat) < 1e-9:
        # fallback if up is parallel to boresight
        ref = np.array([0.0, 0.0, 1.0])
        if abs(np.dot(ref, x_hat)) > 0.99:
            ref = np.array([0.0, 1.0, 0.0])
        z_hat = ref - np.dot(ref, x_hat) * x_hat

    z_hat = _norm(z_hat)

    # For boresight +X and up +Z, this gives y = +Y
    y_hat = _norm(np.cross(z_hat, x_hat))

    # Local-to-global rotation matrix
    R = np.column_stack((x_hat, y_hat, z_hat))

    # Ray direction in local device coordinates
    k_local = R.T @ _norm(ray_dir)
    k_local = _norm(k_local)

    # Sionna spherical coordinates: theta from +z, phi in x-y
    theta = np.arccos(np.clip(k_local[2], -1.0, 1.0))
    phi = np.arctan2(k_local[1], k_local[0])

    # Sionna spherical basis in local coordinates
    theta_hat_local = np.array([
        np.cos(theta) * np.cos(phi),
        np.cos(theta) * np.sin(phi),
       -np.sin(theta)
    ])

    phi_hat_local = np.array([
       -np.sin(phi),
        np.cos(phi),
        0.0
    ])

    # Sionna convention:
    #   V = theta_hat
    #   H = phi_hat
    h_global = _norm(R @ phi_hat_local)
    v_global = _norm(R @ theta_hat_local)

    return h_global, v_global


def apply_rpy(mesh, roll_deg=0.0, pitch_deg=0.0, yaw_deg=0.0, pivot='centroid'):
    """
    Applies Roll (X), Pitch (Y), and Yaw (Z) rotations to a trimesh object.
    
    Parameters:
    - mesh: The trimesh object to rotate
    - roll_deg, pitch_deg, yaw_deg: Angles in degrees
    - pivot: 'centroid' to rotate around its own center, or 'origin' to rotate around (0,0,0)
    """
    # Convert degrees to radians
    roll = np.radians(roll_deg)
    pitch = np.radians(pitch_deg)
    yaw = np.radians(yaw_deg)
    
    # Generate 4x4 rotation matrix using standard static X, Y, Z axes ('sxyz')
    rotation_matrix = trimesh.transformations.euler_matrix(roll, pitch, yaw, axes='sxyz')
    
    if pivot == 'centroid':
        # Translate centroid to origin, apply rotation, then translate back
        centroid = mesh.centroid
        t_to_origin = trimesh.transformations.translation_matrix(-centroid)
        t_to_centroid = trimesh.transformations.translation_matrix(centroid)
        
        # Combine the transformations: T_back * R * T_origin
        final_transform = trimesh.transformations.concatenate_matrices(
            t_to_centroid, rotation_matrix, t_to_origin
        )
    elif pivot == 'origin':
        # Rotate directly around the global coordinate origin
        final_transform = rotation_matrix
    else:
        raise ValueError("Pivot must be 'centroid' or 'origin'")
        
    # Apply transformation in place
    mesh.apply_transform(final_transform)
    return mesh


def antenna_frame_batched(boresights: np.ndarray, ups: np.ndarray) -> tuple:
    """
    Vectorized antenna_frame for N rays at once.
    
    Parameters
    ----------
    boresights : (N, 3) — ray/boresight directions
    ups        : (3,) or (N, 3) — up vector(s)
    
    Returns
    -------
    h : (N, 3)
    v : (N, 3)
    """
    boresights = boresights / np.linalg.norm(boresights, axis=1, keepdims=True)
    
    # Broadcast up to (N, 3) if scalar
    if ups.ndim == 1:
        ups = np.tile(ups, (len(boresights), 1))
    
    # h = normalize(cross(up, boresight))
    h = np.cross(ups, boresights)                                    # (N, 3)
    h_norm = np.linalg.norm(h, axis=1, keepdims=True)

    # Degenerate case: up parallel to boresight — use fallback axis
    degenerate = (h_norm[:, 0] < 1e-8)
    fallback = np.zeros_like(boresights)
    fallback[:, 0] = 1.0                                             # fallback = X axis
    h_fallback = np.cross(fallback, boresights)
    h_fallback_norm = np.linalg.norm(h_fallback, axis=1, keepdims=True)
    h_fallback = h_fallback / np.where(h_fallback_norm < 1e-8, 1.0, h_fallback_norm)

    h = np.where(degenerate[:, None], h_fallback, h / np.where(h_norm < 1e-8, 1.0, h_norm))

    # v = normalize(cross(h, boresight)) — matches scalar antenna_frame()
    # v = np.cross(h, boresights) 
    v = np.cross(boresights, h)                                      # (N, 3)
    v = v / np.linalg.norm(v, axis=1, keepdims=True)

    return h.astype(np.float32), v.astype(np.float32)


def sionna_hv_basis_batched(dirs: np.ndarray, boresight: np.ndarray, up: np.ndarray) -> tuple:
    """Vectorized Sionna local spherical H/V basis for N ray directions sharing
    a single antenna (one boresight + up). Same V=theta_hat, H=phi_hat
    convention as the scalar `sionna_hv_basis()`.

    Parameters
    ----------
    dirs      : (N, 3) — directions to evaluate (TX: departure; RX: came-from).
    boresight : (3,)   — device local +x axis in global coordinates.
    up        : (3,)   — device local +z reference in global coordinates.

    Returns
    -------
    h_global, v_global : (N, 3) each, in global coordinates.
    """
    dirs = np.asarray(dirs, dtype=np.float64)
    dirs = dirs / np.linalg.norm(dirs, axis=1, keepdims=True)

    x_hat = np.asarray(boresight, dtype=np.float64)
    x_hat = x_hat / np.linalg.norm(x_hat)

    up = np.asarray(up, dtype=np.float64)
    z_hat = up - np.dot(up, x_hat) * x_hat
    if np.linalg.norm(z_hat) < 1e-9:                      # up ∥ boresight fallback
        ref = np.array([0.0, 0.0, 1.0])
        if abs(np.dot(ref, x_hat)) > 0.99:
            ref = np.array([0.0, 1.0, 0.0])
        z_hat = ref - np.dot(ref, x_hat) * x_hat
    z_hat = z_hat / np.linalg.norm(z_hat)

    y_hat = np.cross(z_hat, x_hat)
    y_hat = y_hat / np.linalg.norm(y_hat)

    R = np.column_stack((x_hat, y_hat, z_hat))            # local -> global

    # ray dirs in the local frame: (R^T @ dirs[i]) == dirs[i] @ R
    k_local = dirs @ R                                    # (N, 3)
    k_local = k_local / np.linalg.norm(k_local, axis=1, keepdims=True)

    theta = np.arccos(np.clip(k_local[:, 2], -1.0, 1.0))  # (N,)
    phi   = np.arctan2(k_local[:, 1], k_local[:, 0])       # (N,)

    ct, st = np.cos(theta), np.sin(theta)
    cp, sp = np.cos(phi),   np.sin(phi)

    theta_hat_local = np.stack([ct * cp, ct * sp, -st], axis=1)        # (N, 3)
    phi_hat_local   = np.stack([-sp, cp, np.zeros_like(sp)], axis=1)   # (N, 3)

    # back to global: (R @ x_local[i]) == x_local[i] @ R.T
    h_global = phi_hat_local   @ R.T                      # H = phi_hat
    v_global = theta_hat_local @ R.T                      # V = theta_hat
    h_global = h_global / np.linalg.norm(h_global, axis=1, keepdims=True)
    v_global = v_global / np.linalg.norm(v_global, axis=1, keepdims=True)
    return h_global, v_global


def vec_fresnel_te_tm(
    k_in:    np.ndarray,   # (M, 3) incident directions (float64)
    normals: np.ndarray,   # (M, 3) surface normals, already flipped toward incident
    epsilon: complex,
) -> tuple:
    """
    Returns R_TE (M,) and R_TM (M,) complex per ray.
    Used by the Jones vector update in 4f.
    """
    cos_i  = np.clip(-np.einsum('mi,mi->m', k_in, normals), 0.0, 1.0)  # (M,)
    sin2_i = 1.0 - cos_i ** 2
    cos_t  = np.sqrt((epsilon - sin2_i).astype(np.complex128))          # (M,) complex

    R_TE = (cos_i - cos_t) / (cos_i + cos_t)
    R_TM = (epsilon * cos_i - cos_t) / (epsilon * cos_i + cos_t)

    return R_TE.astype(np.complex128), R_TM.astype(np.complex128)


def build_local_basis(k, V_ref):
    """
    Builds the (s, p, k) basis for a ray direction k,
    given a reference vertical direction V_ref (e.g. antenna's up axis).
    s = H = perpendicular to plane of incidence (TE)
    p = V = in the plane of incidence     (TM)
    """
    k = k / np.linalg.norm(k)
    s = np.cross(V_ref, k)
    norm_s = np.linalg.norm(s)
    if norm_s < 1e-10:
        # k is parallel to V_ref, pick arbitrary perpendicular
        s = np.cross(np.array([1, 0, 0]), k)
        s /= np.linalg.norm(s)
    else:
        s /= norm_s
    p = np.cross(k, s)   # automatically unit vector
    return s, p


def check_polarization_3d(E_3d, h_ray, v_ray):
    """
    Classify a 3D field by projecting it onto the ray's transverse (h, v) frame
    and computing Stokes parameters. Returns (pol_type, axial_ratio_dB, phase_delta_deg).
    Same convention as the bug.ipynb reference (delta = phase(Eh) - phase(Ev)).
    """
    Eh = np.dot(E_3d, h_ray)
    Ev = np.dot(E_3d, v_ray)
    a1, a2 = np.abs(Eh), np.abs(Ev)
    if a1 < 1e-9 and a2 < 1e-9:
        return "No Field", np.inf, 0.0

    delta = np.angle(Eh) - np.angle(Ev)
    delta = (delta + np.pi) % (2 * np.pi) - np.pi          # wrap to [-pi, pi]

    S0 = a1**2 + a2**2
    S3 = 2 * a1 * a2 * np.sin(delta)
    doc = S3 / S0 if S0 > 0 else 0.0                       # degree of circularity

    chi   = 0.5 * np.arcsin(np.clip(S3 / S0, -1.0, 1.0))
    ar    = 1.0 / np.tan(np.abs(chi)) if np.abs(chi) > 1e-9 else np.inf
    ar_db = 20 * np.log10(np.clip(ar, 1.0, 1e4))

    if ar_db < 3.0:
        pol_type = "RHCP" if doc > 0 else "LHCP"
    elif ar_db > 15.0:
        pol_type = "Linear"
    else:
        pol_type = "Elliptical (RH)" if doc > 0 else "Elliptical (LH)"
    return pol_type, float(ar_db), float(np.degrees(delta))


def jones_vector(polarization):
    """
    Returns the 2x1 Jones vector [H, V] for a given polarization.
    Uses e^{-iwt} convention, same as MATLAB raypl.
    """
    if polarization == "V":
        return np.array([0, 1], dtype=complex)
    elif polarization == "H":
        return np.array([1, 0], dtype=complex)
    elif polarization == "LHCP":
        return np.array([-1j, 1], dtype=complex) / np.sqrt(2)
    elif polarization == "RHCP":
        return np.array([1j, 1], dtype=complex) / np.sqrt(2)
    elif polarization == "cross":
        return np.array([1, 1], dtype=complex) / np.sqrt(2)
    else:
        # assume it's already a 2x1 Jones vector [H, V]
        v = np.array(polarization, dtype=complex)
        return v / np.linalg.norm(v)


def normalize(vec):
    return vec / np.linalg.norm(vec)


def antenna_frame(pointing, up):
    pointing = normalize(pointing)
    if abs(np.dot(pointing, up)) > 0.999:
        up = np.array([1.0, 0.0, 0.0])
    h_hat = normalize(np.cross(up, pointing))   # ← cross(up, pointing) not cross(pointing, up)
    # v_hat = normalize(np.cross(h_hat, pointing))
    v_hat = normalize(np.cross(pointing, h_hat)) 
    return h_hat, v_hat


def get_antenna_local_angles(ray_dir, boresight, h_ant, v_ant):
    """
    Calcola gli angoli di co-elevazione (theta) e azimuth (phi) locali 
    di un raggio rispetto al frame fisico tridimensionale dell'antenna.
    """
    # 1. Assicuriamo la normalizzazione dei vettori
    k = ray_dir / np.linalg.norm(ray_dir)
    z_loc = boresight / np.linalg.norm(boresight)
    x_loc = h_ant / np.linalg.norm(h_ant)
    y_loc = v_ant / np.linalg.norm(v_ant)
    
    # 2. Co-elevazione (theta): angolo sferico standard rispetto all'asse Z locale
    cos_theta = np.clip(np.dot(k, z_loc), -1.0, 1.0)
    theta_rad = np.arccos(cos_theta)
    theta_deg = np.degrees(theta_rad)
    
    # 3. Azimuth (phi): angolo sul piano X-Y locale dell'antenna
    # Proiettiamo il raggio sui due assi ortogonali della faccia dell'antenna
    proj_x = np.dot(k, x_loc)
    proj_y = np.dot(k, y_loc)
    
    # Se il raggio è perfettamente in asse o sul retro, l'azimuth è indefinito (lo fissiamo a 0)
    if np.abs(proj_x) < 1e-8 and np.abs(proj_y) < 1e-8:
        phi_deg = 0.0
    else:
        phi_deg = np.degrees(np.arctan2(proj_y, proj_x))
        
    return theta_deg, phi_deg


def global_az_el(d, eps=1e-8):
    """Spherical az/el (deg) of a direction in world XYZ. True elevation.

    At the pole (ray ∥ world Z) the horizontal projection vanishes and azimuth
    is undefined; we report 0.0 rather than letting atan2 of float residuals
    return a spurious ±180.
    """
    d = np.asarray(d, dtype=np.float64)
    d = d / np.linalg.norm(d)
    el = np.degrees(np.arcsin(np.clip(d[2], -1.0, 1.0)))
    az = 0.0 if np.hypot(d[0], d[1]) < eps else np.degrees(np.arctan2(d[1], d[0]))
    return az, el


def local_az_el(d, boresight, h_ant, v_ant, eps=1e-8):
    """az/el (deg) of a direction in the antenna frame. True ELEVATION.

    At the pole (ray ∥ v_ant) both in-plane projections vanish and azimuth is
    undefined; we report 0.0 (matching get_antenna_local_angles) instead of a
    spurious ±180 from atan2 of float residuals.
    """
    d = np.asarray(d, dtype=np.float64); d = d / np.linalg.norm(d)
    b = boresight / np.linalg.norm(boresight)
    h = h_ant / np.linalg.norm(h_ant)
    v = v_ant / np.linalg.norm(v_ant)
    proj_b = np.dot(d, b)
    proj_h = np.dot(d, h)
    el = np.degrees(np.arcsin(np.clip(np.dot(d, v), -1.0, 1.0)))
    az = 0.0 if np.hypot(proj_b, proj_h) < eps else np.degrees(np.arctan2(proj_h, proj_b))
    return az, el


def compute_link_angles(dep_dir, arr_dir,
                        boresight_tx, h_tx_ant, v_tx_ant,
                        boresight_rx, h_rx_ant, v_rx_ant):
    """
    dep_dir : unit travel direction LEAVING the TX (into the channel).
    arr_dir : unit travel direction ARRIVING at the RX (last segment).

    Returns a dict with departure (AoD) and arrival (AoA) angles in both the
    global world frame and the local antenna frame.  Legacy keys
    aoa_azimuth_deg / aoa_elevation_deg are kept (= GLOBAL AoA) so every branch
    of every engine reports them in one identical convention.
    """
    aod_az_g, aod_el_g = global_az_el(dep_dir)
    aod_az_l, aod_el_l = local_az_el(dep_dir, boresight_tx, h_tx_ant, v_tx_ant)
    # aoa_az_g, aoa_el_g = global_az_el(arr_dir)                       # travel dir
    came_from          = -np.asarray(arr_dir, dtype=np.float64)
    aoa_az_g, aoa_el_g = global_az_el(came_from)                     # look dir (RX→source), matches paper Eq 5-6
    aoa_az_l, aoa_el_l = local_az_el(came_from, boresight_rx, h_rx_ant, v_rx_ant)
    return {
        "aod_azimuth_global_deg":   float(aod_az_g),
        "aod_elevation_global_deg": float(aod_el_g),
        "aod_azimuth_local_deg":    float(aod_az_l),
        "aod_elevation_local_deg":  float(aod_el_l),
        "aoa_azimuth_global_deg":   float(aoa_az_g),
        "aoa_elevation_global_deg": float(aoa_el_g),
        "aoa_azimuth_local_deg":    float(aoa_az_l),
        "aoa_elevation_local_deg":  float(aoa_el_l),
        # legacy keys, now consistent everywhere (= GLOBAL AoA, true elevation):
        "aoa_azimuth_deg":          float(aoa_az_g),
        "aoa_elevation_deg":        float(aoa_el_g),
    }


def antenna_gain_pattern_2d(theta, phi, G_max_db=15.0, hpbw_h=60.0, hpbw_v=60.0):
    """
    Modello di guadagno 2D. 
    hpbw_h: Apertura a -3dB sul piano Orizzontale (Azimuth = 0 o 180)
    hpbw_v: Apertura a -3dB sul piano Verticale (Azimuth = 90 o -90)
    """
    if theta <= 90.0:
        # Calcoliamo l'apertura del fascio efficace (HPBW) per l'angolo phi corrente
        # Usiamo una combinazione ellittica standard dei due piani principali
        phi_rad = np.radians(phi)
        hpbw_eff = 1.0 / np.sqrt((np.cos(phi_rad) / hpbw_h)**2 + (np.sin(phi_rad) / hpbw_v)**2)
        
        # Attenuazione quadratica basata sulla co-elevazione theta
        loss_db = 12.0 * (theta / hpbw_eff) ** 2
        gain_db = G_max_db - loss_db
    else:
        # Fronte/Retro (Backlobe) fisso oltre i 90 gradi
        gain_db = G_max_db - 30
        
    return max(gain_db, -40.0)

def pattern_from_grap(path, sheet=0):
    """Load a Galileo GRAP .xlsx pattern -> callable pattern(theta, phi) [dBW].
    theta = coelevation (0-90), phi = azimuth (0-360), both degrees.
    Grid + axes attached as pattern.theta / pattern.phi / pattern.grid (grid is [theta, phi]).
    sheet: 0 = EIRP nominal, 1 = upper bound, 2 = lower bound."""
    df = pd.read_excel(path, sheet_name=sheet, header=None)

    theta = pd.to_numeric(df.iloc[1, 2:], errors="coerce").dropna().astype(float).values   # coelev (cols)
    phi   = pd.to_numeric(df.iloc[2:, 1], errors="coerce").dropna().astype(float).values   # azimuth (rows)

    raw = pd.DataFrame(df.iloc[2:2+phi.size, 2:2+theta.size].values) \
            .apply(pd.to_numeric, errors="coerce").fillna(-40.0).astype(float).values       # [phi, theta]
    grid = raw.T                                                                            # -> [theta, phi]

    assert grid.shape == (theta.size, phi.size), \
        f"axis/grid mismatch: grid {grid.shape} vs ({theta.size}, {phi.size})"

    lookup = RegularGridInterpolator((theta, phi), grid, bounds_error=False, fill_value=-40.0)

    def pattern(th, ph):
        scalar_in = np.isscalar(th) and np.isscalar(ph)
        th, ph = np.broadcast_arrays(np.asarray(th, float), np.asarray(ph, float))
        out = lookup(np.column_stack([th.ravel(), ph.ravel()])).reshape(th.shape)
        return float(out) if scalar_in else out

    pattern.theta, pattern.phi, pattern.grid = theta, phi, grid
    return pattern

