"""engine_hybrid — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
from collections import defaultdict
import numpy as np
from constants import C_LIGHT, MAX_PATH_DIST, NORMAL_OFFSET, S_MIN_MAGNITUDE
from em_core import antenna_frame, antenna_gain_pattern_2d, compute_link_angles, get_antenna_local_angles, jones_vector, sionna_hv_basis
from engine_image import _assemble_reflection_path, _backtrace_image_chain, _backtrace_image_chain_batch, _find_first_order_paths
from geometry import _segments_clear, batch_intersect, check_los, generate_launch_directions, generate_pyramid_directions, vec_reflect, generate_surface_directions, generate_surface_equal_directions
from timing import SectionTimer


def _generate_candidate_sequences(
    mesh,
    pos_tx,
    pos_rx,
    launch_dirs,
    max_bounces,
    max_path_distance,
    nee_to_rx=True,
    verbose=False,
    print_hit_fraction=True, 
):
    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)
    launch_dirs = np.asarray(launch_dirs, dtype=np.float64)

    M = len(launch_dirs)
    if M == 0 or max_bounces < 1:
        return set()

    # Prima: float32
    # origins = np.tile(pos_tx.astype(np.float32), (M, 1))
    # dirs    = launch_dirs.astype(np.float32).copy()
    # dist_acc = np.zeros(M, dtype=np.float32)

    origins  = np.tile(pos_tx, (M, 1))
    dirs     = launch_dirs.copy()
    alive    = np.ones(M, dtype=bool)
    bounce   = np.zeros(M, dtype=np.int32)
    dist_acc = np.zeros(M, dtype=np.float64)
    face_hist = np.full((M, max_bounces), -1, dtype=np.int64)

    candidates = set()
    rx_b = np.tile(pos_rx, (M, 1))

    for b in range(max_bounces):
        act = np.where(alive)[0]
        if len(act) == 0:
            break

        o = origins[act]
        d = dirs[act]

        hit_mask, hit_pts, hit_faces, hit_dists = batch_intersect(
        mesh, o, d, max_path_distance
        )

        if b == 0 and verbose and print_hit_fraction:     # gated
            n_hit0 = int(hit_mask.sum())
            print(f"--- Bounce 0: {n_hit0}/{M} launched rays hit the mesh "
                f"({100.0 * n_hit0 / M:.1f}%) ---")

        alive[act[~hit_mask]] = False

        hit_local = np.where(hit_mask)[0]
        if len(hit_local) == 0:
            break

        gi  = act[hit_local]
        inc = d[hit_local]                         # already float64
        hp  = hit_pts[hit_local].astype(np.float64)
        hf  = hit_faces[hit_local]
        hd  = hit_dists[hit_local].astype(np.float64)

        normals = mesh.face_normals[hf].astype(np.float64)
        dot = np.einsum('ij,ij->i', inc, normals)

        backside = dot > 0.0               # entered terrain from underneath (open mesh)
        if backside.any():
            alive[gi[backside]] = False
            keep = ~backside
            gi, inc, hp, hf, hd = gi[keep], inc[keep], hp[keep], hf[keep], hd[keep]
            normals = normals[keep]

        new_dirs = vec_reflect(inc, normals)
        new_orig = hp + normals * (NORMAL_OFFSET * 1000.0)

        dist_acc[gi] += hd
        origins[gi] = new_orig
        dirs[gi] = new_dirs
        bounce[gi] += 1
        face_hist[gi, b] = hf

        if b >= 1:
            if nee_to_rx:
                clear = _segments_clear(
                    mesh, hp, rx_b[:len(gi)], nudge_normals=normals
                )
            else:
                clear = np.ones(len(gi), dtype=bool)

            sel = gi[clear]
            if sel.size:
                seqs2d = face_hist[sel, :b + 1]
                no_adj = np.all(seqs2d[:, 1:] != seqs2d[:, :-1], axis=1)
                seqs2d = seqs2d[no_adj]
                if seqs2d.shape[0]:
                    uniq = np.unique(seqs2d, axis=0)
                    for row in uniq:
                        candidates.add(tuple(int(x) for x in row))

        alive[gi[dist_acc[gi] > max_path_distance]] = False
        alive[gi[bounce[gi] >= max_bounces]] = False

    if verbose:
        by_order: dict = {}
        for s in candidates:
            by_order[len(s)] = by_order.get(len(s), 0) + 1
        print(f"  [candidates] {len(candidates)} unique sequence(s): "
            + ", ".join(f"order-{o}: {n}" for o, n in sorted(by_order.items())))
            
    return candidates


def run_sbr_image_solver(
    mesh:                           trimesh.Trimesh,
    pos_tx:                         np.ndarray,
    pos_rx:                         np.ndarray,
    # ── Antenna configuration ────────────────────────────────────────────
    boresight_tx:                   np.ndarray = None,
    boresight_rx:                   np.ndarray = None,
    up_tx:                          np.ndarray = None,
    up_rx:                          np.ndarray = None,
    tx_pol:                         str = "RHCP",
    rx_pol:                         str = "RHCP",
    G_max_db:                       float = 12.0,
    hpbw_h:                         float = 30.0,
    hpbw_v:                         float = 60.0,
    pattern_tx=                     None,
    pattern_rx=                     None,
    # ── Engine parameters ────────────────────────────────────────────────
    num_rays:                       int = 50_000,
    max_bounces:                    int = 2,
    epsilon_luna:                   complex = 2.87 - 0.01j,
    frequenza:                      float = 2.4e9,
    launch_mode:                    str = "pyramid",   # mesh-targeted by default
    cone_aim_point:                 Optional[np.ndarray] = None,
    horizon_margin_deg:             float = 3.0,
    max_path_distance:              float = MAX_PATH_DIST,
    enable_profiling:               bool = False,
    verbose:                        bool = True,
    isotropic:                      bool = False,
    polarization:                   bool = True,       # False -> pol_loss forced to 0 dB
    debug_ray_direction:            Optional[np.ndarray] = None,
    # ── Hybrid-specific knobs ─────────────────────────────────────────────
    exact_first_order:              bool = True,       # union exact O(1) over all faces
    nee_to_rx:                      bool = True,       # LoS-to-RX candidate pruning
    # ── Polarization convention + occlusion strategy ──────────────────────
    pol_convention:                 str = "fixed",     # "fixed" | "sionna"
    occlusion:                      str = "batched",    # "serial" | "batched" (order>=2)
) -> dict:
    """
    Sionna-style hybrid: SBR discovers candidate facet sequences, the image
    method refines each unique sequence into an exact specular path.

    Same call signature / `results` schema as `run_image_method_engine` and
    `run_complete_multipath_engine_batched_2`, so it is a drop-in `engine_fn`
    for `run_campaign_2(..., engine_fn=run_sbr_image_solver)`.

    Key differences from the pure SBR engine:
      * No reception sphere. `r_influence` and the adaptive-radius parameters
        are accepted but UNUSED. Path vertices and fields are exact.
      * `num_rays` now controls candidate *completeness* (whether a facet
        sequence is discovered), not path accuracy. Once discovered, a path is
        exact regardless of `num_rays`.

    Hybrid knobs:
      * `launch_mode="pyramid"` aims a near-parallel ray grid at the whole mesh
        silhouette (mesh-targeted launch), which is far more efficient than a
        full sphere for a distant terrain patch. Other modes ("full_sphere",
        "lower_flat", "terrain_horizon") fall back to `generate_launch_directions`.
      * `exact_first_order=True` additionally seeds the candidate set with the
        fully-vectorized exact single-bounce solver over ALL facets, so no
        first-order path is missed if the launch under-samples a facet.
    """
    c          = C_LIGHT
    wavelength = c / frequenza
    k          = 2.0 * np.pi / wavelength

    if occlusion not in ("serial", "batched"):
        raise ValueError(f"occlusion must be 'serial' or 'batched', got {occlusion!r}")

    if pattern_tx is None:
       pattern_tx = lambda th, ph: antenna_gain_pattern_2d(th, ph, G_max_db, hpbw_h, hpbw_v)
    if pattern_rx is None:
       pattern_rx = lambda th, ph: antenna_gain_pattern_2d(th, ph, G_max_db, hpbw_h, hpbw_v)

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)

    # ── Antenna frames / polarization (identical setup to the other engines)
    boresight_tx = np.asarray(boresight_tx, dtype=np.float64); boresight_tx /= np.linalg.norm(boresight_tx)
    boresight_rx = np.asarray(boresight_rx, dtype=np.float64); boresight_rx /= np.linalg.norm(boresight_rx)
    up_tx = np.asarray(up_tx, dtype=np.float64); up_tx /= np.linalg.norm(up_tx)
    up_rx = np.asarray(up_rx, dtype=np.float64); up_rx /= np.linalg.norm(up_rx)

    h_tx_ant, v_tx_ant = antenna_frame(boresight_tx, up_tx)
    h_rx_ant, v_rx_ant = antenna_frame(boresight_rx, up_rx)

    J_tx = jones_vector(tx_pol)
    J_rx = jones_vector(rx_pol)
    J_rx_rotated = np.conj(J_rx).T @ np.array([[-1, 0], [0, 1]])

    # EM kwargs bundle for the refiner (kept identical to run_image_method_engine)
    em = dict(
        mesh=mesh, pos_tx=pos_tx, pos_rx=pos_rx,
        wavelength=wavelength, k=k, epsilon=epsilon_luna,
        J_tx=J_tx, J_rx_rotated=J_rx_rotated,
        h_tx_ant=h_tx_ant, v_tx_ant=v_tx_ant, h_rx_ant=h_rx_ant, v_rx_ant=v_rx_ant,
        boresight_tx=boresight_tx, boresight_rx=boresight_rx, up_tx=up_tx,
        G_max_db=G_max_db, hpbw_h=hpbw_h, hpbw_v=hpbw_v, isotropic=isotropic,
        J_rx=J_rx, up_rx=up_rx, pol_convention=pol_convention,
        polarization=polarization, pattern_tx=pattern_tx, pattern_rx=pattern_rx,
    )

    results = {
        "los_segment":           None,
        "los_blocked":           False,
        "los_paths":             [],
        "nlos_paths":            [],
        "keller_events":         [],
        "primary_rays_captured": 0,
        "r_influence_mode":      "hybrid_sbr_image",
    }

    timer = SectionTimer()

    # ── 1. LoS (direct path) — identical treatment to the image engine ────
    with timer("los_check"):
        los_vec  = pos_rx - pos_tx
        los_dist = float(np.linalg.norm(los_vec))
        los_dir  = los_vec / los_dist
        los_blocked, blocking_pt = check_los(mesh, pos_tx, pos_rx)

    if los_blocked:
        results["los_blocked"] = True
        results["los_segment"] = np.vstack((pos_tx, blocking_pt))
        if verbose:
            print(f"\n[LOS INFO] TX and RX are NOT in Line-of-Sight! "
                  f"Blocked at point: {np.round(blocking_pt, 2)}")
    else:
        results["los_segment"] = np.vstack((pos_tx, pos_rx))
        amp_los   = wavelength / (4.0 * np.pi * los_dist)
        fsl_db    = -20.0 * np.log10(amp_los)
        fase_geo  = -k * los_dist
        fase_norm = fase_geo % (2.0 * np.pi)

        if pol_convention == "sionna":
            h_tx_los, v_tx_los = sionna_hv_basis(ray_dir=los_dir, boresight=boresight_tx, up=up_tx)
            E_los = J_tx[0] * h_tx_los + J_tx[1] * v_tx_los
            h_rx_los, v_rx_los = sionna_hv_basis(ray_dir=-los_dir, boresight=boresight_rx, up=up_rx)
            e_rx_los = J_rx[0] * h_rx_los + J_rx[1] * v_rx_los
            pol_factor_los = complex(np.vdot(e_rx_los, E_los))
        else:
            h_ray_los, v_ray_los = antenna_frame(los_dir, up_tx)
            R_los = np.array([
                [np.dot(h_ray_los, h_rx_ant), np.dot(v_ray_los, h_rx_ant)],
                [np.dot(h_ray_los, v_rx_ant), np.dot(v_ray_los, v_rx_ant)],
            ])
            pol_factor_los = complex(np.atleast_1d(J_rx_rotated @ R_los @ J_tx)[0])
        if not polarization:
            _d = abs(pol_factor_los)
            pol_factor_los = pol_factor_los / _d if _d > 1e-12 else complex(1.0)
        IL_los_db = -20.0 * np.log10(np.clip(abs(pol_factor_los), 1e-10, 1.0))

        theta_tx_los, phi_tx_los = get_antenna_local_angles(los_dir, boresight_tx, h_tx_ant, v_tx_ant)
        gain_tx_los = pattern_tx(theta_tx_los, phi_tx_los)
        theta_rx_los, phi_rx_los = get_antenna_local_angles(-los_dir, boresight_rx, h_rx_ant, v_rx_ant)
        gain_rx_los = pattern_rx(theta_rx_los, phi_rx_los)

        if isotropic:
            gain_tx_los = 0.0; gain_rx_los = 0.0

        g_field_los    = 10.0 ** ((gain_tx_los + gain_rx_los) / 20.0)
        campo_los      = amp_los * g_field_los * pol_factor_los * np.exp(1j * fase_geo)
        total_loss_los = fsl_db + IL_los_db - gain_tx_los - gain_rx_los

        aoa_dir_los = -los_dir
        _ang_los = compute_link_angles(
            los_dir, los_dir,
            boresight_tx, h_tx_ant, v_tx_ant,
            boresight_rx, h_rx_ant, v_rx_ant,
        )

        if verbose:
            print(
                f"\n[LOS INFO] LoS CLEAR | "
                f"Dist: {los_dist:.2f} m | FSL: {fsl_db:.2f} dB | "
                f"Pol Loss: {IL_los_db:.2f} dB | "
                f"Gain TX: {gain_tx_los:.2f} dB | Gain RX: {gain_rx_los:.2f} dB | "
                f"Total Loss: {total_loss_los:.2f} dB"
            )

        results["primary_rays_captured"] = 1
        results["nlos_paths"].append({
            "ray_id": -1, "bounces": 0, "has_diffracted": False, "faces_hit": [],
            "points": np.array([pos_tx, pos_rx]), "distanza_totale": los_dist,
            "campo_complesso": campo_los, "fsl_db": fsl_db, "IL_db": float(IL_los_db),
            "gain_tx_db": gain_tx_los, "gain_rx_db": gain_rx_los,
            "reflection_loss_db": 0.0, "diffraction_loss_db": 0.0,
            "path_loss_totale_db": total_loss_los,
            "sfasamento_totale_rad": fase_norm, "sfasamento_totale_deg": np.degrees(fase_norm),
            "ritardo_assoluto_ns": (los_dist / c) * 1e9,
            "aoa_direction": aoa_dir_los, **_ang_los,
            "theta_tx_deg": theta_tx_los, "phi_tx_deg": phi_tx_los,
            "theta_rx_deg": theta_rx_los, "phi_rx_deg": phi_rx_los,
            "dettaglio_rimbalzi": [], "r_influence_used": None,
        })

    ray_id = 0
    found_per_order: dict = {}
    candidates: Set[Tuple[int, ...]] = set()   # order>=2 only (for the report)

    # ── 2. ORDER 1 — exact, fully vectorized, NO SBR ──────────────────────
    # At a single bounce there is no combinatorial explosion to prune, so SBR
    # is pure overhead. `_find_first_order_paths` mirrors TX across every facet,
    # solves the specular point, and validates both legs in batched calls — it
    # *is* the exact first-bounce image method. Its output is already validated
    # (point-in-triangle + clear_in + clear_out), so we assemble straight from
    # it: no per-candidate `_backtrace_image_chain`, no re-running `_segments_clear`.
    if exact_first_order and max_bounces >= 1:
        with timer("order1_vectorized"):
            o1 = _find_first_order_paths(mesh, pos_tx, pos_rx, np.arange(len(mesh.faces)))
            for pts, fseq in o1:
                d = _assemble_reflection_path(pts, list(fseq), ray_id, **em)
                if d is None or d["distanza_totale"] > max_path_distance:
                    continue
                d.setdefault("membro_raggruppamento", [ray_id])
                d.setdefault("potenza_incoerente", abs(d["campo_complesso"]) ** 2)
                found_per_order[1] = found_per_order.get(1, 0) + 1
                if verbose:
                    ray_label = "[K]" if d["has_diffracted"] else "[P]"
                    print(
                        f"Ray ID #{ray_id:5d} | Bounces: {d['bounces']} | {ray_label} | "
                        f"Dist: {d['distanza_totale']:.2f} m | FSL: {d['fsl_db']:.2f} dB | "
                        f"Refl: {d['reflection_loss_db']:.2f} dB | Diff: {d['diffraction_loss_db']:.2f} dB | "
                        f"Pol Loss: {d['pol_loss']:.2f} | "
                        f"IL: {d['IL_db']:.2f} dB | "
                        f"Gain TX: {d['gain_tx_db']:.2f} dB | Gain RX: {d['gain_rx_db']:.2f} dB | "
                        f"Total: {d['path_loss_totale_db']:.2f} dB | Fase: {d['sfasamento_totale_deg']:.2f}°"
                    )
                results["nlos_paths"].append(d)
                ray_id += 1

    # ── 3. ORDER >= 2 — SBR discovers sequences, image method refines ─────
    # Only here does SBR earn its keep: it prunes the F^order sequence space
    # down to the handful actually traversed. Skipped entirely for max_bounces<2.
    #     * `launch_mode="pyramid"` aims a near-parallel ray grid at the whole mesh
    # silhouette.
    # * `launch_mode="surface"` aims rays at sampled points on mesh triangles,
    # weighted by projected triangle area. This is a hybrid candidate-discovery
    # mode, not a physical angular sampler.
    # * `launch_mode="surface_equal"` aims rays at mesh triangles with approximately
    # equal allocation per triangle. This is useful for coverage/debugging.
    # * Other modes ("full_sphere", "lower_flat", "terrain_horizon") fall back to
    # `generate_launch_directions`.

    if max_bounces >= 2:
       with timer("launch"):
        launch_info = None

        if debug_ray_direction is not None:
            d = np.asarray(debug_ray_direction, dtype=np.float64)
            launch_dirs = (d / np.linalg.norm(d)).reshape(1, 3).astype(np.float64)
            n_eff, omega = 1, 0.0

        elif launch_mode == "pyramid":
            launch_dirs, n_eff, omega = generate_pyramid_directions(
                pos_tx,
                num_rays,
                mesh,
                cone_aim_point,
            )

        elif launch_mode == "surface":
            launch_dirs, n_eff, omega, launch_info = generate_surface_directions(
                pos_tx,
                num_rays,
                mesh,
                seed=42,
                include_centroids=True,
                use_projected_area=True,
                use_abs_cos=True,
                aim_point=cone_aim_point,
                return_info=True,
            )

        elif launch_mode == "surface_equal":
            launch_dirs, n_eff, omega, launch_info = generate_surface_equal_directions(
                pos_tx,
                num_rays,
                mesh,
                seed=42,
                use_centroid_first=True,
                visible_only=False,
                use_abs_cos=True,
                aim_point=cone_aim_point,
                return_info=True,
            )

        else:
            launch_dirs, n_eff, omega = generate_launch_directions(
                pos_tx,
                num_rays,
                mesh=mesh,
                mode=launch_mode,
                horizon_margin_deg=horizon_margin_deg,
            )

        launch_dirs = np.asarray(launch_dirs, dtype=np.float64)
        launch_dirs /= np.linalg.norm(launch_dirs, axis=1, keepdims=True)

        if verbose:
            omega_txt = f"{omega:.3f}" if np.isfinite(omega) else "n/a"

            print(
                f"\n--- Hybrid solver | launch={launch_mode} | "
                f"{len(launch_dirs)} rays (n_eff={n_eff}, Ω={omega_txt} sr) | "
                f"max_bounces={max_bounces} ---"
            )

            if launch_info is not None:
                _print_surface_launch_face_stats(launch_mode, launch_info)

        with timer("candidate_gen"):
            all_seqs = _generate_candidate_sequences(
                mesh, pos_tx, pos_rx, launch_dirs,
                max_bounces=max_bounces, max_path_distance=max_path_distance,
                nee_to_rx=nee_to_rx, verbose=verbose, print_hit_fraction=launch_mode not in ("surface", "surface_equal"),

            )
            # Order 1 is owned by the exact vectorized pass above; only refine >=2.
            candidates = {s for s in all_seqs if len(s) >= 2}

        if occlusion == "batched":
            # Same physics and same surviving paths as the serial branch:
            # one backtrace per order, then a SINGLE segments-clear over every
            # leg of every candidate. Only the ray_id labelling order differs
            # (set iteration), which does not affect received power.
            from collections import defaultdict
            with timer("refine_A_backtrace"):
                by_order = defaultdict(list)
                for seq in candidates:
                    by_order[len(seq)].append(seq)

                valid: list = []                # (pts, seq) per surviving candidate
                leg_start_chunks, leg_end_chunks   = [], []
                leg_nudge_chunks, leg_owner_chunks = [], []
                owner_base = 0

                for K in sorted(by_order):
                    seqs_arr = np.asarray(by_order[K], dtype=np.int64)       # (nK, K)
                    pts_b, ok = _backtrace_image_chain_batch(mesh, pos_tx, pos_rx, seqs_arr)
                    keep = np.nonzero(ok)[0]
                    if keep.size == 0:
                        continue
                    pts_k  = pts_b[keep]                                     # (m, K+2, 3)
                    seqs_k = seqs_arr[keep]                                  # (m, K)
                    m = keep.size

                    starts = pts_k[:, :-1, :]                               # (m, K+1, 3)
                    ends   = pts_k[:, 1:, :]
                    nud = np.zeros_like(starts)
                    nud[:, 1:K + 1, :] = mesh.face_normals[seqs_k]
                    owners = owner_base + np.repeat(np.arange(m), K + 1)

                    leg_start_chunks.append(starts.reshape(-1, 3))
                    leg_end_chunks.append(ends.reshape(-1, 3))
                    leg_nudge_chunks.append(nud.reshape(-1, 3))
                    leg_owner_chunks.append(owners.astype(np.int64))
                    for j in range(m):
                        valid.append((pts_k[j], tuple(int(x) for x in seqs_k[j])))
                    owner_base += m

            with timer("refine_B_occlusion"):
                if valid:
                    all_starts = np.concatenate(leg_start_chunks, axis=0)
                    all_ends   = np.concatenate(leg_end_chunks,   axis=0)
                    all_nudges = np.concatenate(leg_nudge_chunks, axis=0)
                    all_owner  = np.concatenate(leg_owner_chunks, axis=0)
                    leg_clear = _segments_clear(mesh, all_starts, all_ends, nudge_normals=all_nudges)
                    cand_ok = np.ones(len(valid), dtype=bool)
                    np.logical_and.at(cand_ok, all_owner, leg_clear)   # survives iff ALL legs clear
                else:
                    cand_ok = np.zeros(0, dtype=bool)

            with timer("refine_C_assemble"):
                for ci, (pts, seq) in enumerate(valid):
                    if not cand_ok[ci]:
                        continue
                    K = len(seq)
                    d = _assemble_reflection_path(pts, list(seq), ray_id, **em)
                    if d is None or d["distanza_totale"] > max_path_distance:
                        continue
                    d.setdefault("membro_raggruppamento", [ray_id])
                    d.setdefault("potenza_incoerente", abs(d["campo_complesso"]) ** 2)
                    found_per_order[K] = found_per_order.get(K, 0) + 1
                    if verbose:
                        ray_label = "[K]" if d["has_diffracted"] else "[P]"
                        print(
                            f"Ray ID #{ray_id:5d} | Bounces: {d['bounces']} | {ray_label} | "
                            f"Dist: {d['distanza_totale']:.2f} m | FSL: {d['fsl_db']:.2f} dB | "
                            f"Refl: {d['reflection_loss_db']:.2f} dB | Diff: {d['diffraction_loss_db']:.2f} dB | "
                            f"Pol Loss: {d['pol_loss']:.2f} | "
                            f"IL: {d['IL_db']:.2f} dB | "
                            f"Gain TX: {d['gain_tx_db']:.2f} dB | Gain RX: {d['gain_rx_db']:.2f} dB | "
                            f"Total: {d['path_loss_totale_db']:.2f} dB | Fase: {d['sfasamento_totale_deg']:.2f}°"
                        )
                    results["nlos_paths"].append(d)
                    ray_id += 1
        else:
            with timer("image_refine"):
                for seq in sorted(candidates, key=lambda s: (len(s), s)):
                    K = len(seq)

                    # Exact specular vertices for this facet chain (or None if invalid).
                    pts = _backtrace_image_chain(mesh, pos_tx, pos_rx, seq)
                    if pts is None:
                        continue

                    # Per-leg occlusion validation (TX->P1, P1->P2, ..., PK->RX).
                    seg_starts = pts[:-1].copy()
                    seg_ends   = pts[1:].copy()
                    nudges = np.zeros_like(seg_starts)
                    for s in range(1, K + 1):
                        nudges[s] = mesh.face_normals[seq[s - 1]]
                    if not np.all(_segments_clear(mesh, seg_starts, seg_ends, nudge_normals=nudges)):
                        continue

                    # Exact complex field (identical EM physics to the other engines).
                    d = _assemble_reflection_path(pts, list(seq), ray_id, **em)
                    if d is None or d["distanza_totale"] > max_path_distance:
                        continue

                    d.setdefault("membro_raggruppamento", [ray_id])
                    d.setdefault("potenza_incoerente", abs(d["campo_complesso"]) ** 2)

                    found_per_order[K] = found_per_order.get(K, 0) + 1
                    if verbose:
                        ray_label = "[K]" if d["has_diffracted"] else "[P]"
                        print(
                            f"Ray ID #{ray_id:5d} | Bounces: {d['bounces']} | {ray_label} | "
                            f"Dist: {d['distanza_totale']:.2f} m | FSL: {d['fsl_db']:.2f} dB | "
                            f"Refl: {d['reflection_loss_db']:.2f} dB | Diff: {d['diffraction_loss_db']:.2f} dB | "
                            f"Pol Loss: {d['pol_loss']:.2f} | "
                            f"IL: {d['IL_db']:.2f} dB | "
                            f"Gain TX: {d['gain_tx_db']:.2f} dB | Gain RX: {d['gain_rx_db']:.2f} dB | "
                            f"Total: {d['path_loss_totale_db']:.2f} dB | Fase: {d['sfasamento_totale_deg']:.2f}°"
                        )
                    results["nlos_paths"].append(d)
                    ray_id += 1

    if enable_profiling:
        timer.report()

    # ── 4. Report ──────────────────────────────────────────────────────────
    if verbose:
        print("\n" + "=" * 60)
        print(f"   HYBRID SBR→IMAGE FINAL REPORT | f = {frequenza/1e9:.2f} GHz")
        print("=" * 60)
        print(f"  TX Pol: {tx_pol} | RX Pol: {rx_pol}")
        print(f"  Direct rays captured (SBR)  : {results['primary_rays_captured']}")
        print("-" * 60)

        for b in range(1, max_bounces + 1):
            comps_b = [p for p in results["nlos_paths"] if p["bounces"] == b]
            r_count = len([p for p in comps_b if not p["has_diffracted"]])
            d_count = len([p for p in comps_b if p["has_diffracted"]])
            total_b = r_count + d_count
            if total_b > 0:
                micro_b = sum(len(p.get("membro_raggruppamento", [])) for p in comps_b)
                print(f"  Paths reaching RX with exactly {b} bounce(s): {total_b} "
                      f"coherent component(s) from {micro_b} micro-ray(s)")
                print(f"     ├─ Pure Reflections: {r_count}")
                print(f"     └─ Diffracted Paths: {d_count}")
                for p in comps_b:
                    tag = "K" if p["has_diffracted"] else "P"
                    print(f"        • [{tag}] faces {tuple(p['faces_hit'])}: "
                          f"{len(p.get('membro_raggruppamento', []))} micro-ray(s) "
                          f"→ {p['path_loss_totale_db']:.2f} dB")

        n_components = len([p for p in results["nlos_paths"] if p["bounces"] > 0])
        n_raw_multipath = sum(
            len(p.get("membro_raggruppamento", []))
            for p in results["nlos_paths"] if p["bounces"] > 0
        )
        print("-" * 60)
        print(f"  Keller Diffraction Events Triggered : 0")
        print(f"  Raw multipath micro-rays captured   : {n_raw_multipath}")
        print(f"  Coherent multipath components at RX : {n_components}")
        print("=" * 60 + "\n")

    return results

def _print_surface_launch_face_stats(launch_mode, launch_info):
    target_faces = np.asarray(launch_info["target_faces"], dtype=np.int64)
    valid_faces = np.asarray(launch_info["valid_faces"], dtype=np.int64)
    num_mesh_faces = int(launch_info["num_mesh_faces"])

    counts = np.bincount(target_faces, minlength=num_mesh_faces)
    targeted = counts > 0

    n_rays = int(target_faces.size)
    n_valid = int(valid_faces.size)
    n_targeted = int(np.sum(targeted))

    avg_per_valid = n_rays / max(n_valid, 1)
    avg_per_targeted = n_rays / max(n_targeted, 1)

    min_targeted = int(counts[targeted].min()) if n_targeted > 0 else 0
    max_targeted = int(counts[targeted].max()) if n_targeted > 0 else 0

    print(
        f"--- {launch_mode} launch allocation: "
        f"{n_rays} rays | "
        f"{n_valid} valid faces | "
        f"{avg_per_valid:.2f} rays/valid face avg | "
        f"{n_targeted} targeted faces | "
        f"min/max targeted={min_targeted}/{max_targeted} ---"
    )