"""engine_image_parallel — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
from concurrent.futures import ProcessPoolExecutor
import itertools
import numpy as np
import trimesh
from constants import C_LIGHT, MAX_PATH_DIST
from em_core import antenna_frame, jones_vector
from engine_image import _assemble_reflection_path, _backtrace_image_chain_batch, run_image_method_engine
from geometry import _segments_clear


def _init_worker(vertices: np.ndarray, faces: np.ndarray,
                 pos_tx: np.ndarray, pos_rx: np.ndarray) -> None:
    """Pool initializer: build the mesh once per child process."""
    global _MESH, _TX, _RX
    _MESH = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    _ = _MESH.face_normals          # force-compute & cache once per process
    _TX = np.asarray(pos_tx, dtype=np.float64)
    _RX = np.asarray(pos_rx, dtype=np.float64)


def _validate_chunk(seqs_chunk: np.ndarray) -> List[Tuple[np.ndarray, List[int]]]:
    """
    Backtrace + occlusion-validate one chunk of equal-length facet sequences.

    Mirrors the body of `utils_image._find_higher_order_paths`, but vectorized
    over the whole chunk: one `_backtrace_image_chain_batch` call + one
    `_segments_clear` call instead of a per-sequence Python loop.

    Returns a list of (pts (K+2,3), face_seq) for sequences that pass BOTH the
    point-in-triangle backtrace test AND the all-segments-clear occlusion test.
    """
    mesh, tx, rx = _MESH, _TX, _RX
    seqs = np.asarray(seqs_chunk, dtype=np.int64)
    if seqs.size == 0:
        return []
    n, K = seqs.shape

    # 1) Exact specular vertices for the whole chunk (point-in-triangle inside).
    pts_b, ok_b = _backtrace_image_chain_batch(mesh, tx, rx, seqs)
    idx = np.nonzero(ok_b)[0]
    if idx.size == 0:
        return []
    pts_v = pts_b[idx]          # (m, K+2, 3)  [TX, P1..PK, RX]
    seqs_v = seqs[idx]          # (m, K)
    m = idx.size

    # 2) Occlusion test on ALL (K+1) sub-segments of ALL m survivors at once.
    #    Segment s starts at pts[s]; for s>=1 that point lies on facet seq[s-1],
    #    so its start is nudged off that facet's plane (segment 0 = TX->P1 isn't).
    starts = pts_v[:, :-1, :].reshape(-1, 3)        # (m*(K+1), 3)
    ends   = pts_v[:, 1:,  :].reshape(-1, 3)
    nudges = np.zeros((m, K + 1, 3), dtype=np.float64)
    fn = mesh.face_normals
    for s in range(1, K + 1):
        nudges[:, s, :] = fn[seqs_v[:, s - 1]]
    nudges = nudges.reshape(-1, 3)

    clear = _segments_clear(mesh, starts, ends, nudge_normals=nudges)  # (m*(K+1),)
    all_clear = clear.reshape(m, K + 1).all(axis=1)                    # (m,)

    out: List[Tuple[np.ndarray, List[int]]] = []
    for j in np.nonzero(all_clear)[0]:
        out.append((pts_v[j].copy(), [int(f) for f in seqs_v[j]]))
    return out


def _gen_chunks(cand_faces: np.ndarray, order: int, chunk_size: int):
    """Yield (chunk_size, order) int arrays of facet permutations, lazily.

    Generating in chunks (instead of materializing all permutations) keeps RAM
    bounded even when the total sequence count is in the millions.
    """
    buf: List[Tuple[int, ...]] = []
    for seq in itertools.permutations(cand_faces.tolist(), order):
        # adjacent identical facets are physically meaningless. (permutations
        # never repeat an element, so this never triggers — kept for parity
        # with the serial _find_higher_order_paths.)
        if any(seq[i] == seq[i + 1] for i in range(order - 1)):
            continue
        buf.append(seq)
        if len(buf) >= chunk_size:
            yield np.asarray(buf, dtype=np.int64)
            buf = []
    if buf:
        yield np.asarray(buf, dtype=np.int64)


def _cull_candidates(mesh: trimesh.Trimesh, pos_tx: np.ndarray,
                     pos_rx: np.ndarray, cand: np.ndarray,
                     order: int, verbose: bool,
                     max_path_distance: float = MAX_PATH_DIST) -> np.ndarray:
    """Stage-1 (normals + ellipsoid distance) + Stage-2 (visibility raycast)
    culling, identical in spirit to the per-order culling inside
    `utils_image.run_image_method_engine`. Shrinks F BEFORE the F^order step."""
    # ── Stage 1: fast cull ────────────────────────────────────────────────
    cents = mesh.triangles_center[cand]
    norms = mesh.face_normals[cand]
    vec_tx = pos_tx - cents
    vec_rx = pos_rx - cents

    dot_tx = np.einsum('ij,ij->i', norms, vec_tx)
    dot_rx = np.einsum('ij,ij->i', norms, vec_rx)
    # NOTE: a planar facet reflects from either side, so a winding-dependent
    # facing test (dot>0) wrongly drops valid reflectors. For order>=2 the facet
    # reflects an IMAGE source, not TX/RX directly, so facing is meaningless here.
    # Keep all facets that are merely non-degenerate; distance is the only safe
    # geometric pre-cull. Backtrace (point-in-triangle) + occlusion validate exactly.
    mask_facing = np.ones(len(cand), dtype=bool)

    los_dist = np.linalg.norm(pos_tx - pos_rx)
    # Correct superset cull for ANY order: dist(F,TX)+dist(F,RX) <= path length
    # <= max_path_distance. The old los_dist*1.2 pruned every off-axis facet,
    # leaving only ~1-bounce-on-the-line candidates (the reported bug).
    max_path_dist = max_path_distance
    dist_tx = np.linalg.norm(vec_tx, axis=1)
    dist_rx = np.linalg.norm(vec_rx, axis=1)
    mask_dist = (dist_tx + dist_rx) <= max_path_dist

    cand_s1 = cand[mask_facing & mask_dist]
    if verbose:
        print(f"  [Stage 1 Fast Cull] order {order}: {len(cand)} -> {len(cand_s1)}")
    # Direct-visibility (Stage 2) is unsafe for order>=2 (a facet reached via
    # another bounce need not be directly visible from an endpoint), so it is
    # skipped here; the per-leg occlusion test inside _validate_chunk is exact.
    return cand_s1


def run_image_method_engine_parallel(
    mesh:                       trimesh.Trimesh,
    pos_tx:                     np.ndarray,
    pos_rx:                     np.ndarray,
    *,
    # ── parallelism knobs ────────────────────────────────────────────────
    n_workers:                  Optional[int] = None,    # None = all cores
    chunk_size:                 int = 20_000,            # permutations per task
    # ── image-method knobs (same meaning as the serial engine) ───────────
    max_bounces:                int = 2,
    image_max_candidate_faces:  Optional[int] = None,
    image_max_sequences:        float = 5_000_000,
    max_path_distance:          float = MAX_PATH_DIST,
    verbose:                    bool = True,
    # ── antenna / physics config — forwarded to the serial engine AND used
    #    for field assembly of the parallel order>=2 paths ─────────────────
    boresight_tx:               np.ndarray = None,
    boresight_rx:               np.ndarray = None,
    up_tx:                      np.ndarray = None,
    up_rx:                      np.ndarray = None,
    tx_pol:                     str = "RHCP",
    rx_pol:                     str = "RHCP",
    G_max_db:                   float = 12.0,
    hpbw_h:                     float = 30.0,
    hpbw_v:                     float = 60.0,
    epsilon_luna:               complex = 2.87 - 0.01j,
    frequenza:                  float = 2.4e9,
    isotropic:                  bool = False,
    pol_convention:             str = "fixed",          # "fixed" | "sionna"
    polarization:               bool = True,            # False -> pol_loss = 0 dB
    **extra_engine_kwargs,
) -> dict:
    """
    Parallel image-method engine. LoS + order-1 are produced by the serial
    `run_image_method_engine`; order>=2 is searched across processes.

    Returns the SAME `results` dict schema as the serial engine.
    """
    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)

    # ── 1) LoS + order-1 via the serial engine (fast, already vectorized) ──
    base_bounces = min(max_bounces, 1)
    results = run_image_method_engine(
        mesh, pos_tx, pos_rx,
        boresight_tx=boresight_tx, boresight_rx=boresight_rx,
        up_tx=up_tx, up_rx=up_rx, tx_pol=tx_pol, rx_pol=rx_pol,
        G_max_db=G_max_db, hpbw_h=hpbw_h, hpbw_v=hpbw_v,
        max_bounces=base_bounces, epsilon_luna=epsilon_luna,
        frequenza=frequenza, isotropic=isotropic,
        max_path_distance=max_path_distance, verbose=verbose,
        image_max_candidate_faces=image_max_candidate_faces,
        image_max_sequences=image_max_sequences,
        pol_convention=pol_convention,
        polarization=polarization,
        **extra_engine_kwargs,
    )
    if max_bounces < 2:
        return results

    # ── 2) Antenna frames / polarization for assembling order>=2 paths ─────
    wavelength = C_LIGHT / frequenza
    k = 2.0 * np.pi / wavelength
    bt = np.asarray(boresight_tx, float); bt /= np.linalg.norm(bt)
    br = np.asarray(boresight_rx, float); br /= np.linalg.norm(br)
    ut = np.asarray(up_tx, float); ut /= np.linalg.norm(ut)
    ur = np.asarray(up_rx, float); ur /= np.linalg.norm(ur)
    h_tx_ant, v_tx_ant = antenna_frame(bt, ut)
    h_rx_ant, v_rx_ant = antenna_frame(br, ur)
    J_tx = jones_vector(tx_pol)
    J_rx = jones_vector(rx_pol)
    J_rx_rotated = np.conj(J_rx).T @ np.array([[-1, 0], [0, 1]])

    # next ray_id continues after the order-1 paths
    existing_ids = [p["ray_id"] for p in results["nlos_paths"] if p["ray_id"] >= 0]
    ray_id = (max(existing_ids) + 1) if existing_ids else 0

    # ── 3) Candidate facet set (same construction as the serial engine) ────
    F_all = len(mesh.faces)
    cand = np.arange(F_all)
    if image_max_candidate_faces is not None and F_all > image_max_candidate_faces:
        cand = np.unique(np.linspace(0, F_all - 1, image_max_candidate_faces).astype(int))
        if verbose:
            print(f"  [image] subsampling facets: {F_all} -> {len(cand)}")

    # ── 4) Order>=2 search, parallelized across processes ──────────────────
    found_per_order = {}
    with ProcessPoolExecutor(
        max_workers=n_workers,
        initializer=_init_worker,
        initargs=(np.asarray(mesh.vertices), np.asarray(mesh.faces), pos_tx, pos_rx),
    ) as pool:
        for order in range(2, max_bounces + 1):
            optimized = _cull_candidates(mesh, pos_tx, pos_rx, cand, order, verbose,
                                         max_path_distance=max_path_distance)
            F = len(optimized)
            n_seq = F ** order
            if F < order or n_seq == 0:
                found_per_order[order] = 0
                continue
            if n_seq > image_max_sequences:
                if verbose:
                    print(f"  [image] order {order}: {F}^{order} = {n_seq:.3e} "
                          f"> cap {image_max_sequences:.1e} — SKIPPED. "
                          f"Lower image_max_candidate_faces or max_bounces.")
                found_per_order[order] = 0
                continue

            if verbose:
                print(f"  [parallel] order {order}: enumerating {n_seq:.3e} "
                      f"sequences over {F} facets ...")

            validated: List[Tuple[np.ndarray, List[int]]] = []
            for chunk_out in pool.map(_validate_chunk,
                                      _gen_chunks(optimized, order, chunk_size)):
                validated.extend(chunk_out)

            # Field assembly is cheap & sequential — only survivors reach here.
            n_added = 0
            for pts, fseq in validated:
                d = _assemble_reflection_path(
                    pts, fseq, ray_id, mesh=mesh, pos_tx=pos_tx, pos_rx=pos_rx,
                    wavelength=wavelength, k=k, epsilon=epsilon_luna,
                    J_tx=J_tx, J_rx_rotated=J_rx_rotated,
                    h_tx_ant=h_tx_ant, v_tx_ant=v_tx_ant,
                    h_rx_ant=h_rx_ant, v_rx_ant=v_rx_ant,
                    boresight_tx=bt, boresight_rx=br, up_tx=ut,
                    G_max_db=G_max_db, hpbw_h=hpbw_h, hpbw_v=hpbw_v,
                    isotropic=isotropic,
                    J_rx=J_rx, up_rx=ur, pol_convention=pol_convention,
                    polarization=polarization,
                )
                if d is None or d["distanza_totale"] > max_path_distance:
                    continue
                results["nlos_paths"].append(d)
                ray_id += 1
                n_added += 1
            found_per_order[order] = n_added
            if verbose:
                print(f"  [parallel] order {order}: {n_added} valid specular paths")

    # ── 5) Re-annotate SBR-compatible grouping fields (parity w/ serial) ───
    for p in results["nlos_paths"]:
        p.setdefault("membro_raggruppamento", [p.get("ray_id", -1)])
        p.setdefault("potenza_incoerente", abs(p["campo_complesso"]) ** 2)

    if verbose:
        print("\n" + "=" * 60)
        print(f"   PARALLEL IMAGE-METHOD REPORT | f = {frequenza/1e9:.2f} GHz")
        print("=" * 60)
        for o in sorted(found_per_order):
            print(f"  Order-{o} specular paths       : {found_per_order[o]}")
        n_comp = len([p for p in results["nlos_paths"] if p["bounces"] > 0])
        print(f"  Total multipath components    : {n_comp}")
        print("=" * 60 + "\n")

    return results