"""engine_sbr — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import numpy as np
from constants import MAX_PATH_DIST, NORMAL_OFFSET, S_MIN_MAGNITUDE
from diffraction import _cronologia_with_utd, _utd_coeff_for_capture, extract_diffraction_edges, generate_keller_cone_rays, inject_keller_children
from em_core import antenna_frame, antenna_frame_batched, antenna_gain_pattern_2d, check_polarization_3d, compute_link_angles, get_antenna_local_angles, jones_vector, sionna_hv_basis, sionna_hv_basis_batched, vec_fresnel_scalar, vec_fresnel_te_tm
from geometry import batch_intersect, check_edge_collision, check_los, generate_launch_directions, generate_pyramid_directions, vec_adaptive_r, vec_reflect


class RayBatch_2:
    """
    Holds the full mutable state of all rays as flat NumPy arrays.
    Fully vectorized — no Python loops anywhere.

    Parameters
    ----------
    origins_init : (N, 3) float32  — all start at TX
    dirs_init    : (N, 3) float32  — Fibonacci sphere directions
    max_bounces  : int             — needed to pre-allocate path_hist
    up_tx        : (3,)  float64  — TX installation up vector
    """

    def __init__(
        self,
        origins_init: np.ndarray,   # (N, 3)
        dirs_init:    np.ndarray,   # (N, 3)
        max_bounces:  int,
        up_tx:        np.ndarray,   # (3,)
    ):
        N = len(origins_init)
        B = max_bounces

        # ── Core per-ray state ────────────────────────────────────────
        self.origins    = origins_init.astype(np.float32).copy()
        self.dirs       = dirs_init.astype(np.float32).copy()

        self.S_real     = np.ones(N,  dtype=np.float32)
        self.S_imag     = np.zeros(N, dtype=np.float32)

        # ── Metadata ──────────────────────────────────────────────────
        self.bounce     = np.zeros(N, dtype=np.int32)
        self.alive      = np.ones(N,  dtype=bool)
        self.diffracted = np.zeros(N, dtype=bool)
        self.dist_acc   = np.zeros(N, dtype=np.float32)

        # ── Initial directions — never mutated ────────────────────────
        self.initial_dirs = dirs_init.astype(np.float32).copy()

        # ── Jones vectors: (N, 2) complex stored as two (N, 2) float32 ─
        self.J_real = np.zeros((N, 2), dtype=np.float32)
        self.J_imag = np.zeros((N, 2), dtype=np.float32)

        # ── Local transverse frames — fully vectorized seed ───────────
        up_tx_f32 = np.asarray(up_tx, dtype=np.float32)
        self.h_vec, self.v_vec = antenna_frame_batched(
            self.dirs.astype(np.float64),
            up_tx_f32.astype(np.float64),
        )                                                             # each (N, 3)

        # ── Path history ──────────────────────────────────────────────
        self.path_hist  = np.zeros((N, B + 2, 3), dtype=np.float32)
        self.path_len   = np.ones(N, dtype=np.int32)
        self.path_hist[:, 0, :] = origins_init.astype(np.float32)

        # ── Face IDs and cronologia (object arrays, unavoidably Python) ─
        self.face_ids   = np.empty(N, dtype=object)
        for i in range(N):
            self.face_ids[i] = []
        self.cronologia = [[] for _ in range(N)]

    # ------------------------------------------------------------------
    # Convenience: S as complex view
    # ------------------------------------------------------------------
    @property
    def S_complex(self) -> np.ndarray:
        return self.S_real.astype(np.complex64) + 1j * self.S_imag.astype(np.complex64)

    def set_S(self, idx: np.ndarray, values: np.ndarray):
        self.S_real[idx] = values.real.astype(np.float32)
        self.S_imag[idx] = values.imag.astype(np.float32)

    # ------------------------------------------------------------------
    # Extend batch (for diffraction child rays)
    # ------------------------------------------------------------------
    def append_rays(
        self,
        new_origins:    np.ndarray,   # (M, 3)
        new_dirs:       np.ndarray,   # (M, 3)
        parent_indices: np.ndarray,   # (M,)
        parent_S:       np.ndarray,   # (M,) complex
        new_bounce:     np.ndarray,   # (M,) int32
        new_diffracted: np.ndarray,   # (M,) bool
        new_dist_acc:   np.ndarray,   # (M,) float32
        new_path_hist:  np.ndarray,   # (M, B+2, 3)
        new_path_len:   np.ndarray,   # (M,)
        new_face_ids:   list,
        new_cronologia: list,
    ):
        M  = len(new_origins)
        B2 = self.path_hist.shape[1]

        # ── Core arrays ───────────────────────────────────────────────
        self.origins    = np.vstack([self.origins,    new_origins.astype(np.float32)])
        self.dirs       = np.vstack([self.dirs,       new_dirs.astype(np.float32)])
        self.S_real     = np.concatenate([self.S_real,  parent_S.real.astype(np.float32)])
        self.S_imag     = np.concatenate([self.S_imag,  parent_S.imag.astype(np.float32)])
        self.bounce     = np.concatenate([self.bounce,   new_bounce.astype(np.int32)])
        self.alive      = np.concatenate([self.alive,    np.ones(M, dtype=bool)])
        self.diffracted = np.concatenate([self.diffracted, new_diffracted])
        self.dist_acc   = np.concatenate([self.dist_acc,   new_dist_acc.astype(np.float32)])

        # ── Path history ──────────────────────────────────────────────
        ph_padded = np.zeros((M, B2, 3), dtype=np.float32)
        src_w = min(new_path_hist.shape[1], B2)
        ph_padded[:, :src_w, :] = new_path_hist[:, :src_w, :]
        self.path_hist = np.vstack([self.path_hist, ph_padded])
        self.path_len  = np.concatenate([self.path_len, new_path_len.astype(np.int32)])

        # ── Face IDs ──────────────────────────────────────────────────
        new_fi = np.empty(M, dtype=object)
        for i, fi in enumerate(new_face_ids):
            new_fi[i] = list(fi)
        self.face_ids   = np.concatenate([self.face_ids, new_fi])
        self.cronologia += new_cronologia

        # ── Polarization — children inherit parent state ──────────────
        self.J_real       = np.vstack([self.J_real,       self.J_real[parent_indices]])
        self.J_imag       = np.vstack([self.J_imag,       self.J_imag[parent_indices]])
        self.h_vec        = np.vstack([self.h_vec,        self.h_vec[parent_indices]])
        self.v_vec        = np.vstack([self.v_vec,        self.v_vec[parent_indices]])
        self.initial_dirs = np.vstack([self.initial_dirs, self.initial_dirs[parent_indices]])


def run_SBR(
    mesh:                           trimesh.Trimesh,
    pos_tx:                         np.ndarray,       # (3,)
    pos_rx:                         np.ndarray,       # (3,)
    r_influence,                                      # float | None (adaptive)
    # ── Antenna configuration ────────────────────────────────────────────
    boresight_tx:                   np.ndarray,       # (3,) TX boresight direction
    boresight_rx:                   np.ndarray,       # (3,) RX boresight direction
    up_tx:                          np.ndarray,       # (3,) TX installation up vector
    up_rx:                          np.ndarray,       # (3,) RX installation up vector
    tx_pol:                         str = "RHCP",     # "RHCP","LHCP","H","V"
    rx_pol:                         str = "RHCP",
    G_max_db:                       float = 12.0,     # peak antenna gain [dBi]
    hpbw_h:                         float = 30.0,     # horizontal HPBW [deg]
    hpbw_v:                         float = 60.0,     # vertical HPBW [deg]
    pattern_tx=                     None,
    pattern_rx=                     None,
    # ── Engine parameters ────────────────────────────────────────────────
    num_rays:                       int   = 5_000,
    max_bounces:                    int   = 3,
    epsilon_luna:                   complex = 2.87 - 0.01j,
    frequenza:                      float = 2.4e9,
    enable_diffractions:            bool  = True,
    edge_tolerance:                 float = 0.01,
    adaptive_min_wavelength_factor: float = 0.5,
    adaptive_max_cap_meters:        float = 20.0,
    launch_mode:        str   = "full_sphere",   # "full_sphere" | "lower_flat" | "terrain_horizon" | "piramid"
    cone_aim_point: Optional[np.ndarray] = None,   # None ⇒ aim at mesh.centroid
    horizon_margin_deg: float = 3.0,
    # ── HPC extras ───────────────────────────────────────────────────────
    energy_threshold:               float = S_MIN_MAGNITUDE,
    max_path_distance:              float = MAX_PATH_DIST,
    num_diff_rays:                  int   = 6,
    verbose:                        bool  = True,   # captured-ray lines print by default
    isotropic:                      bool  = False,  # paper mode: 0 dBi + co-pol capture
    # ── External helpers ─────────────────────────────────────────────────
    extract_diffraction_edges:      Optional[Callable] = None,
    generate_keller_cone_rays:      Optional[Callable] = None,
    check_edge_collision:           Optional[Callable] = None,
    # ── Debug mode ───────────────────────────────────────────────────────
    debug_ray_direction:            Optional[np.ndarray] = None,
    # ── Polarization convention ───────────────────────────────────────────
    pol_convention:                 str = "fixed",   # "fixed" | "sionna"
    # ── Nullify polarization-mismatch loss at capture (keeps bounce physics) ──
    polarization:                   bool = True,     # False -> pol_loss forced to 0 dB
) -> dict:
    """
    Vectorized SBR Multipath Engine with full polarization support.

    Extends the scalar engine with:
    - Per-ray Jones vector propagation (2-component complex)
    - Local transverse frame (h_vec, v_vec) carried forward across bounces
    - TX/RX antenna frames built from boresight + up vectors
    - Polarization mismatch loss (IL) at capture
    - TX departure gain and RX arrival gain from pattern model
    - Full TE/TM Fresnel matrix at each reflection (not scalar average)

    Parameters
    ----------
    boresight_tx/rx : (3,) unit vectors pointing in the antenna's look direction
    up_tx/rx        : (3,) installation up vectors — encodes antenna roll
    tx_pol/rx_pol   : polarization string, one of "RHCP","LHCP","H","V"
    G_max_db        : peak gain [dBi], same model applied to both antennas
    hpbw_h/v        : half-power beamwidths [deg] for horizontal/vertical planes
    """

    # ------------------------------------------------------------------
    # 0. Setup
    # ------------------------------------------------------------------
    adaptive_mode = r_influence is None
    r_cfg         = "adaptive" if adaptive_mode else float(r_influence)

    if pol_convention not in ("fixed", "sionna"):
        raise ValueError(f"pol_convention must be 'fixed' or 'sionna', got {pol_convention!r}")
    
    if pattern_tx is None:
        pattern_tx = lambda th, ph: antenna_gain_pattern_2d(th, ph, G_max_db, hpbw_h, hpbw_v)
    if pattern_rx is None:
        pattern_rx = lambda th, ph: antenna_gain_pattern_2d(th, ph, G_max_db, hpbw_h, hpbw_v)

    c          = 299_792_458.0
    wavelength = c / frequenza
    k          = 2.0 * np.pi / wavelength

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)
    pos_rx_f32 = pos_rx.astype(np.float32)

    # ------------------------------------------------------------------
    # 0b. Antenna frames and polarization — built once, reused everywhere
    # ------------------------------------------------------------------
    boresight_tx = np.asarray(boresight_tx, dtype=np.float64)
    boresight_rx = np.asarray(boresight_rx, dtype=np.float64)
    up_tx        = np.asarray(up_tx,        dtype=np.float64)
    up_rx        = np.asarray(up_rx,        dtype=np.float64)

    boresight_tx = boresight_tx / np.linalg.norm(boresight_tx)
    boresight_rx = boresight_rx / np.linalg.norm(boresight_rx)
    up_tx        = up_tx        / np.linalg.norm(up_tx)
    up_rx        = up_rx        / np.linalg.norm(up_rx)

    h_tx_ant, v_tx_ant = antenna_frame(boresight_tx, up_tx)   # (3,) each
    h_rx_ant, v_rx_ant = antenna_frame(boresight_rx, up_rx)   # (3,) each

    J_tx         = jones_vector(tx_pol)                                    # (2,) complex
    J_rx         = jones_vector(rx_pol)                                    # (2,) complex
    J_rx_rotated = np.conj(J_rx).T @ np.array([[-1, 0], [0, 1]])          # (1,2) complex

    results = {
        "los_segment":           None,
        "los_blocked":           False,
        "los_paths":             [],
        "nlos_paths":            [],
        "keller_events":         [],
        "primary_rays_captured": 0,
        "r_influence_mode":      r_cfg,
    }

    # ------------------------------------------------------------------
    # Optional cProfile wrapper
    # ------------------------------------------------------------------
   

    # ------------------------------------------------------------------
    # 1. LoS check + full polarization treatment
    # ------------------------------------------------------------------
    los_vec  = pos_rx - pos_tx
    los_dist = float(np.linalg.norm(los_vec))
    los_dir  = los_vec / los_dist

    los_blocked, blocking_pt = check_los(mesh, pos_tx, pos_rx)

    if los_blocked:
        results["los_blocked"] = True
        results["los_segment"] = np.vstack((pos_tx, blocking_pt))
        print(f"\n[LOS INFO] TX and RX are NOT in Line-of-Sight! "
              f"Blocked at point: {np.round(blocking_pt, 2)}")
    else:
        results["los_blocked"] = False
        results["los_segment"] = np.vstack((pos_tx, pos_rx))

        amp_los   = wavelength / (4.0 * np.pi * los_dist)
        fsl_db    = -20.0 * np.log10(amp_los)
        fase_geo  = -k * los_dist
        fase_norm = fase_geo % (2.0 * np.pi)

        # ── Polarization ─────────────────────────────────────────────
        # Free space: P = I, so the ray's local frame == TX antenna frame
        if pol_convention == "sionna":
            h_tx_los, v_tx_los = sionna_hv_basis(ray_dir=los_dir, boresight=boresight_tx, up=up_tx)
            E_los = J_tx[0] * h_tx_los + J_tx[1] * v_tx_los
            h_rx_los, v_rx_los = sionna_hv_basis(ray_dir=-los_dir, boresight=boresight_rx, up=up_rx)
            e_rx_los = J_rx[0] * h_rx_los + J_rx[1] * v_rx_los
            pol_factor_los = complex(np.vdot(e_rx_los, E_los))
        else:
            h_ray_los, v_ray_los = antenna_frame(los_dir, up_tx)

            R_los = np.array([
                [np.dot(h_ray_los, h_rx_ant), np.dot(v_ray_los, h_rx_ant)],
                [np.dot(h_ray_los, v_rx_ant), np.dot(v_ray_los, v_rx_ant)],
            ])
            pol_factor_los = J_rx_rotated @ R_los @ J_tx           # complex scalar
        if not polarization:
            # Nullify polarization-mismatch loss only: free-space LoS has unit
            # field magnitude and |R|=1, so the captured magnitude is 1 (0 dB
            # mismatch). Phase preserved for coherent combining.
            _d = abs(complex(np.atleast_1d(pol_factor_los)[0]))
            pol_factor_los = (complex(np.atleast_1d(pol_factor_los)[0]) / _d
                              if _d > 1e-12 else complex(1.0))
        IL_los_db      = -20.0 * np.log10(
            np.clip(abs(pol_factor_los), 1e-10, 1.0)
        )

        # ── Antenna gains ─────────────────────────────────────────────
        # TX: ray departs along los_dir — angle wrt TX boresight
        theta_tx_los, phi_tx_los = get_antenna_local_angles(
            los_dir, boresight_tx, h_tx_ant, v_tx_ant
        )
        gain_rx_los = pattern_tx(theta_tx_los, phi_tx_los)

        # RX: ray arrives from TX — negate so vector points away from RX
        theta_rx_los, phi_rx_los = get_antenna_local_angles(
            -los_dir, boresight_rx, h_rx_ant, v_rx_ant
        )
        gain_tx_los = pattern_tx(theta_rx_los, phi_rx_los)


        # ── Isotropic / paper-validation mode ─────────────────────────
        if isotropic:
            gain_tx_los    = 0.0
            gain_rx_los    = 0.0

        # Field carries antenna gains so |campo|^2 is the end-to-end power
        g_field_los    = 10.0 ** ((gain_tx_los + gain_rx_los) / 20.0)
        campo_los      = amp_los * g_field_los * pol_factor_los * np.exp(1j * fase_geo)
        total_loss_los = fsl_db + IL_los_db - gain_tx_los - gain_rx_los

        # AoA at RX: ray arrives from TX direction, so "came from" = -los_dir
        aoa_dir_los = -los_dir
        # Global (travel-dir) + local (came-from, true elevation) angles, TX & RX
        _ang_los = compute_link_angles(
            los_dir, los_dir,
            boresight_tx, h_tx_ant, v_tx_ant,
            boresight_rx, h_rx_ant, v_rx_ant,
        )

        print(
            f"\n[LOS INFO] LoS CLEAR | "
            f"Dist: {los_dist:.2f} m | FSL: {fsl_db:.2f} dB | "
            f"Pol Loss: {IL_los_db:.2f} dB | "
            f"Gain TX: {gain_tx_los:.2f} dB | Gain RX: {gain_rx_los:.2f} dB | "
            f"Total Loss: {total_loss_los:.2f} dB"
        )

        results["nlos_paths"].append({
            "ray_id":                -1,
            "bounces":               0,
            "has_diffracted":        False,
            "faces_hit":             [],
            "points":                np.array([pos_tx, pos_rx]),
            "distanza_totale":       los_dist,
            "campo_complesso":       campo_los,
            "fsl_db":                fsl_db,
            "IL_db":                 float(IL_los_db),
            "gain_tx_db":            gain_tx_los,
            "gain_rx_db":            gain_rx_los,
            "reflection_loss_db":    0.0,
            "diffraction_loss_db":   0.0,
            "path_loss_totale_db":   total_loss_los,
            "sfasamento_totale_rad": fase_norm,
            "sfasamento_totale_deg": np.degrees(fase_norm),
            "ritardo_assoluto_ns":   (los_dist / c) * 1e9,
            "aoa_direction":         aoa_dir_los,
            **_ang_los,
            # "theta_tx_deg":          theta_tx_los,
            # "phi_tx_deg":            phi_tx_los,
            # "theta_rx_deg":          theta_rx_los,
            # "phi_rx_deg":            phi_rx_los,
            "dettaglio_rimbalzi":    [],
            "r_influence_used":      None,
        })

    # ------------------------------------------------------------------
    # 2. Diffraction edge pre-processing
    # ------------------------------------------------------------------
    diff_edges = []
    if enable_diffractions and extract_diffraction_edges is not None:
        diff_edges = extract_diffraction_edges(mesh)

    if diff_edges:
        _e_p0  = np.array([e['p0']  for e in diff_edges], dtype=np.float32)
        _e_dir = np.array([e['dir'] for e in diff_edges], dtype=np.float32)
        _e_len = np.array([e['len'] for e in diff_edges], dtype=np.float32)
        _e_n0  = np.array([e['n0']  for e in diff_edges], dtype=np.float32)
        _e_n1  = np.array([e['n1']  for e in diff_edges], dtype=np.float32)
        _e_cvx = np.array([e['is_convex'] for e in diff_edges], dtype=bool)
    else:
        _e_p0 = _e_dir = _e_len = _e_n0 = _e_n1 = None

    # ------------------------------------------------------------------
    # 3. Initialise RayBatch
    # ------------------------------------------------------------------
    debug_mode = debug_ray_direction is not None

    if debug_mode:
        d          = np.asarray(debug_ray_direction, dtype=np.float32)
        d          = d / np.linalg.norm(d)
        dirs_np    = d.reshape(1, 3)
        origins_np = pos_tx.astype(np.float32).reshape(1, 3)
        batch      = RayBatch_2(origins_np, dirs_np, max_bounces, up_tx)
        n_eff = 1
        print(f"\n--- [DEBUG MODE] Single ray from TX | "
              f"Direction: [{d[0]:.4f}, {d[1]:.4f}, {d[2]:.4f}] ---")
    else:
        if launch_mode == "pyramid":
            dirs_np, n_eff, omega = generate_pyramid_directions(
                pos_tx, num_rays, mesh, cone_aim_point
            )
        else:
            dirs_np, n_eff, omega = generate_launch_directions(
                pos_tx, num_rays, mesh=mesh, mode=launch_mode,
                horizon_margin_deg=horizon_margin_deg,
            )

        origins_np = np.tile(pos_tx.astype(np.float32), (len(dirs_np), 1))
        batch      = RayBatch_2(origins_np, dirs_np, max_bounces, up_tx)   # _2 variant: add up_tx
        print(f"--- Launching {len(dirs_np)} rays (n_eff={n_eff}, Ω={omega:.2f} sr, mode={launch_mode}) ---")
    print(f"\n--- Launching Combined Ray-Tracing Engine | "
            f"({num_rays} Rays) ---")

    # Seed Jones vectors — all rays start with TX polarization state
    batch.J_real[:, 0] = float(J_tx[0].real)
    batch.J_imag[:, 0] = float(J_tx[0].imag)
    batch.J_real[:, 1] = float(J_tx[1].real)
    batch.J_imag[:, 1] = float(J_tx[1].imag)

    # In the Sionna convention the launch field lives in the ray-dependent
    # spherical V/H basis (theta_hat/phi_hat) rather than the fixed antenna
    # frame. RayBatch_2 seeds (h_vec, v_vec) with antenna_frame_batched; here we
    # overwrite that seed so E0 = J_tx[0]*h + J_tx[1]*v equals the Sionna launch
    # field. Reflections re-express the basis-independent physical field, so
    # only this launch seed (and the RX capture below) carry the convention.
    if pol_convention == "sionna":
        h_sio, v_sio = sionna_hv_basis_batched(
            batch.initial_dirs.astype(np.float64), boresight_tx, up_tx
        )
        batch.h_vec = h_sio.astype(np.float32)
        batch.v_vec = v_sio.astype(np.float32)

    total_edges_triggered = 0

    # ------------------------------------------------------------------
    # 4. BOUNCE LOOP
    # ------------------------------------------------------------------
    for bounce in range(max_bounces + 1):

        # ── 4a. Build active index ────────────────────────────────────
        active = np.where(batch.alive)[0]

        if len(active) == 0:
            break

        N_act    = len(active)
        orig_act = batch.origins[active]   # (N_act, 3)
        dirs_act = batch.dirs[active]      # (N_act, 3)

        # ── 4b. Batch ray-mesh intersection ───────────────────────────
        hit_mask, hit_pts, hit_faces, hit_dists = batch_intersect(mesh, orig_act, dirs_act, max_path_distance)

        if bounce == 0:
            n_hit = int(hit_mask.sum())
            print(f"--- Bounce 0: {n_hit}/{len(hit_mask)} launched rays hit the mesh "
                  f"({100.0 * n_hit / len(hit_mask):.1f}%) ---")
            
        seg_b = hit_pts

        # ── Debug printout ────────────────────────────────────────────
        if debug_mode:
            o = orig_act[0]
            d = dirs_act[0]
            print(f"\n  [DEBUG] Bounce {bounce}")
            print(f"    Origin    : [{o[0]:.4f}, {o[1]:.4f}, {o[2]:.4f}]")
            print(f"    Direction : [{d[0]:.4f}, {d[1]:.4f}, {d[2]:.4f}]")
            if hit_mask[0]:
                hp = hit_pts[0]
                print(f"    Mesh hit  : YES — Face {hit_faces[0]} at "
                      f"[{hp[0]:.4f}, {hp[1]:.4f}, {hp[2]:.4f}] "
                      f"(dist {hit_dists[0]:.4f} m)")
                n = mesh.face_normals[hit_faces[0]]
                print(f"    Normal    : [{n[0]:.4f}, {n[1]:.4f}, {n[2]:.4f}]")
                gi    = int(active[0])
                S_val = complex(batch.S_real[gi]) + 1j * complex(batch.S_imag[gi])
                print(f"    S_accum   : {S_val:.6f}  |S| = {abs(S_val):.6f}")
            else:
                print(f"    Mesh hit  : NO — ray exits scene")

        # ── 4c. Edge collision check ───────────────────────────────────
        edge_kill_local = np.zeros(N_act, dtype=bool)

        if enable_diffractions and diff_edges and check_edge_collision and generate_keller_cone_rays:
            non_diff_mask = ~batch.diffracted[active]
            non_diff_li   = np.where(non_diff_mask)[0]

            edge_local_idx_list = []
            ep_list, ed_list    = [], []

            if len(non_diff_li) > 0:
                seg_ends = np.where(
                    hit_mask[non_diff_li, None],
                    hit_pts[non_diff_li],
                    orig_act[non_diff_li] + dirs_act[non_diff_li] * max_path_distance
                )

                ray_vecs  = seg_ends - orig_act[non_diff_li]
                ray_lens  = np.linalg.norm(ray_vecs, axis=1)
                valid_ray = ray_lens > 0
                ray_dirs  = np.where(
                    valid_ray[:, None],
                    ray_vecs / np.where(valid_ray[:, None], ray_lens[:, None], 1.0),
                    0.0
                ).astype(np.float32)

                E = _e_p0.shape[0]
                M = len(non_diff_li)
                w = _e_p0[None, :, :] - orig_act[non_diff_li, None, :]

                a_me = np.einsum('ei,ei->e', _e_dir, _e_dir)[None, :] \
                        * np.ones((M, 1), dtype=np.float32)
                b_me = np.einsum('mi,ei->me', ray_dirs, _e_dir)
                c_me = np.einsum('mi,mi->m', ray_dirs, ray_dirs)[:, None] \
                        * np.ones((1, E), dtype=np.float32)
                d_me = np.einsum('mei,ei->me', w, _e_dir)
                e_me = np.einsum('mei,mi->me', w, ray_dirs)

                denom       = a_me * c_me - b_me * b_me
                valid_denom = np.abs(denom) >= 1e-6

                tc = np.where(valid_denom,
                                (a_me * e_me - b_me * d_me) / np.where(valid_denom, denom, 1.0),
                                -1.0)
                sc = np.where(valid_denom,
                                (b_me * e_me - c_me * d_me) / np.where(valid_denom, denom, 1.0),
                                -1.0)

                rl_me    = ray_lens[:, None] * np.ones((1, E), dtype=np.float32)
                in_range = ((tc >= 0) & (tc <= rl_me)
                            & (sc >= 0) & (sc <= _e_len[None, :]))

                pt_on_edge = (_e_p0[None, :, :]
                                + sc[:, :, None] * _e_dir[None, :, :])
                pt_on_ray  = (orig_act[non_diff_li, None, :]
                                + tc[:, :, None] * ray_dirs[:, None, :])
                gap        = np.linalg.norm(pt_on_edge - pt_on_ray, axis=2)

                hit_me    = in_range & (gap <= edge_tolerance)
                tc_masked = np.where(hit_me, tc, np.inf)
                best_e    = np.argmin(tc_masked, axis=1)
                best_tc   = tc_masked[np.arange(M), best_e]
                any_hit   = np.isfinite(best_tc)

                mesh_dist_m = np.where(
                    hit_mask[non_diff_li],
                    hit_dists[non_diff_li].astype(np.float32),
                    np.inf
                )
                EDGE_MESH_EPSILON   = 1e-4
                closer_than_mesh    = best_tc <= (mesh_dist_m + EDGE_MESH_EPSILON)
                fired               = any_hit & closer_than_mesh & valid_ray

                edge_starts_list, edge_ends_list               = [], []
                edge_n0_list, edge_n1_list, edge_cvx_list      = [], [], []

                for idx_m in np.where(fired)[0]:
                    li      = int(non_diff_li[idx_m])
                    e_i     = int(best_e[idx_m])
                    gi      = int(active[li])
                    ep      = pt_on_edge[idx_m, e_i].astype(np.float64)
                    ed      = _e_dir[e_i].astype(np.float64)
                    e_start = _e_p0[e_i].astype(np.float64)
                    e_end   = e_start + ed * float(_e_len[e_i])

                    edge_local_idx_list.append(li)
                    edge_starts_list.append(e_start)
                    edge_ends_list.append(e_end)
                    edge_n0_list.append(_e_n0[e_i].astype(np.float64))
                    edge_n1_list.append(_e_n1[e_i].astype(np.float64))
                    edge_cvx_list.append(_e_cvx[e_i])
                    ep_list.append(ep)
                    ed_list.append(ed)
                    edge_kill_local[li] = True

                if edge_local_idx_list:
                    eli_arr = np.array(edge_local_idx_list)
                    total_edges_triggered += len(eli_arr)

                    inject_keller_children(
                        batch                     = batch,
                        edge_local_idx            = eli_arr,
                        active_global_idx         = active,
                        edge_pts                  = np.array(ep_list,          dtype=np.float32),
                        edge_dirs                 = np.array(ed_list,          dtype=np.float32),
                        incoming_dirs             = dirs_act[eli_arr],
                        edge_starts               = np.array(edge_starts_list, dtype=np.float32),
                        edge_ends                 = np.array(edge_ends_list,   dtype=np.float32),
                        edge_n0                   = np.array(edge_n0_list,     dtype=np.float32),
                        edge_n1                   = np.array(edge_n1_list,     dtype=np.float32),
                        edge_is_convex            = np.array(edge_cvx_list,    dtype=bool),
                        keller_events             = results["keller_events"],
                        k_wave                    = k,
                        generate_keller_cone_rays = generate_keller_cone_rays,
                        num_diff_rays             = num_diff_rays,
                    )
                    batch.alive[active[eli_arr]] = False

        # ── 4d. Vectorized RX sphere check ────────────────────────────
     
        if adaptive_mode:
            dist_to_rx     = np.linalg.norm(orig_act - pos_rx_f32, axis=1).astype(np.float32)
            total_dist_est = batch.dist_acc[active] + dist_to_rx
            r_check = vec_adaptive_r(total_dist_est, n_eff, 
                                        wavelength, adaptive_min_wavelength_factor, adaptive_max_cap_meters)
        else:
            r_check = float(r_influence)

        w_rx        = pos_rx_f32 - orig_act
        seg_vecs    = seg_b - orig_act
        seg_lens    = np.linalg.norm(seg_vecs, axis=1)
        safe_lens   = np.where(seg_lens > 0, seg_lens, 1.0)
        dirs_norm   = seg_vecs / safe_lens[:, None]
        proj        = np.einsum('ij,ij->i', w_rx, dirs_norm)
        proj_cl     = np.clip(proj, 0.0, seg_lens)
        closest_pts = orig_act + proj_cl[:, None] * dirs_norm
        dist_to_cls = np.linalg.norm(pos_rx_f32 - closest_pts, axis=1)
        rx_hit_mask = dist_to_cls <= (r_check if adaptive_mode else float(r_influence))
        rx_pts      = closest_pts

        # ── 4e. Process captured rays ─────────────────────────────────
        
        captured_local = np.where(rx_hit_mask & ~edge_kill_local)[0]

        for li in captured_local:
            gi = int(active[li])
            if not batch.alive[gi]:
                continue

            b_count = int(batch.bounce[gi])

            # ── Direct rays (bounce == 0): SBR quasi-LoS ─────────
            # These are kept for counting only — the analytical LoS
            # in section 1 is the authoritative direct-path result.
            if b_count == 0:
                results["primary_rays_captured"] += 1
                batch.alive[gi] = False

                closest_pt  = rx_pts[li].astype(np.float64)
                dist_direct = float(np.linalg.norm(closest_pt - pos_tx))
                amp_direct  = wavelength / (4.0 * np.pi * dist_direct)
                fase_direct = -k * dist_direct
                fsl_direct  = -20.0 * np.log10(amp_direct)

                # ── Antenna gains for this direct ray ────────────────
                dir_dep = batch.initial_dirs[gi].astype(np.float64)
                dir_dep /= np.linalg.norm(dir_dep)
                theta_tx_d, phi_tx_d = get_antenna_local_angles(
                    dir_dep, boresight_tx, h_tx_ant, v_tx_ant)
                gain_tx_d = pattern_tx(theta_tx_d, phi_tx_d)

                arr_dir = dirs_act[li].astype(np.float64)
                arr_dir /= np.linalg.norm(arr_dir)
                theta_rx_d, phi_rx_d = get_antenna_local_angles(
                    -arr_dir, boresight_rx, h_rx_ant, v_rx_ant)
                gain_rx_d = pattern_tx(theta_rx_d, phi_rx_d)


                if isotropic:
                    gain_tx_d = 0.0
                    gain_rx_d = 0.0

                if verbose or debug_mode:
                    print(
                        f"Ray ID #{gi:5d} | Bounces: 0 | [D] "
                        f"Dist: {dist_direct:.2f} m | "
                        f"FSL: {fsl_direct:.2f} dB | "
                        f"Gain TX: {gain_tx_d:.2f} dB | Gain RX: {gain_rx_d:.2f} dB | "
                        f"Fase: {np.degrees(fase_direct % (2*np.pi)):.2f}°"
                    )

                results["los_paths"].append({
                    **compute_link_angles(
                        dir_dep, arr_dir,
                        boresight_tx, h_tx_ant, v_tx_ant,
                        boresight_rx, h_rx_ant, v_rx_ant,
                    ),
                    "distanza_totale":       dist_direct,
                    "campo_complesso":       amp_direct * 10.0 ** ((gain_tx_d + gain_rx_d) / 20.0) * np.exp(1j * fase_direct),
                    "fsl_db":                fsl_direct,
                    "gain_tx_db":            gain_tx_d,
                    "gain_rx_db":            gain_rx_d,
                    "sfasamento_totale_rad": fase_direct % (2.0 * np.pi),
                    "sfasamento_totale_deg": np.degrees(fase_direct % (2.0 * np.pi)),
                    "ritardo_assoluto_ns":   (dist_direct / c) * 1e9,
                })
                continue

            # ── Bounced/diffracted rays (bounce >= 1) ─────────────
            is_keller = bool(batch.diffracted[gi])
            ray_label = "[K]" if is_keller else "[P]"

            pl         = int(batch.path_len[gi])
            closest_pt = rx_pts[li].astype(np.float64)
            path_arr   = np.vstack([
                batch.path_hist[gi, :pl, :].astype(np.float64),
                closest_pt,
            ])
            segs     = np.diff(path_arr, axis=0)
            dist_tot = float(np.sum(np.linalg.norm(segs, axis=1)))

            # ── FSL ───────────────────────────────────────────────
            if is_keller:
                s_prime  = float(batch.dist_acc[gi])
                edge_pt  = batch.path_hist[gi, pl - 1, :].astype(np.float64)
                s_child  = float(np.linalg.norm(pos_rx - edge_pt))
                if s_prime < 1e-9 or s_child < 1e-9:
                    batch.alive[gi] = False
                    continue
                A_spread     = np.sqrt(s_prime / (s_child * (s_prime + s_child)))
                amp_incident = wavelength / (4.0 * np.pi * s_prime)
                amp          = amp_incident * A_spread

                # ── UTD diffraction coefficient (exact edge→RX geometry) ──
                # Folded into the field via pol_factor below, so it reaches
                # `campo`; diff_db is derived from the SAME coefficient so
                # the log and the field stay consistent.
                D_diff  = _utd_coeff_for_capture(
                    batch.cronologia[gi], pos_rx, s_prime, s_child,
                    k, epsilon_luna)
                diff_db = -20.0 * np.log10(abs(D_diff) + 1e-30)
            else:
                amp     = wavelength / (4.0 * np.pi * dist_tot)
                D_diff  = 1.0 + 0.0j
                diff_db = 0.0

            fsl_db = -20.0 * np.log10(amp)

            # ── Phase reference (reflection phase, for logging only) ──
            S_val   = complex(batch.S_real[gi]) + 1j * complex(batch.S_imag[gi])
            refl_db = 0.0   # overwritten below by the true 3D value

            # ── Phase ─────────────────────────────────────────────
            fase_geo = -k * dist_tot
            fase_die = float(np.angle(S_val))
            fase_tot = (fase_geo + fase_die) % (2.0 * np.pi)

            # ── AoA in global frame: direction the ray CAME FROM ──
            aoa_dir  = -dirs_act[li].astype(np.float64)   # came-from = -travel
            aoa_dir /= np.linalg.norm(aoa_dir)
            aoa_el, aoa_az = get_antenna_local_angles(aoa_dir, boresight_rx, h_rx_ant, v_rx_ant)


            # ── Polarization projection onto RX frame ─────────────
            J_ray = (batch.J_real[gi] + 1j * batch.J_imag[gi]).astype(np.complex128)
            h_ray = batch.h_vec[gi].astype(np.float64)
            v_ray = batch.v_vec[gi].astype(np.float64)

            # 1. Ricostruzione del VERO campo elettrico 3D in arrivo
            E_incident = J_ray[0] * h_ray + J_ray[1] * v_ray  # (3,) complex

            # 2. Estrazione della VERA Reflection Loss 3D (sostituisce l'approssimazione scalare)
            amp_E_inc = np.clip(np.linalg.norm(E_incident), 1e-12, 1.0)
            refl_db_true = -20.0 * np.log10(amp_E_inc)

            # 3-4. RX projection onto the antenna (convention-dependent)
            if pol_convention == "sionna":
                # Ray-dependent spherical V/H at the came-from direction; the
                # coherent receive voltage is vdot(e_rx, E) (e_rx conjugated).
                h_rx_ray, v_rx_ray = sionna_hv_basis(
                    ray_dir=aoa_dir, boresight=boresight_rx, up=up_rx
                )
                e_rx = J_rx[0] * h_rx_ray + J_rx[1] * v_rx_ray
                pol_factor = complex(np.vdot(e_rx, E_incident))
            else:
                # Fixed antenna-axis projection captured through the rotated RX
                # Jones. J_rx_rotated ha shape (1, 2) e np.array ha shape (2,).
                V_h = np.dot(E_incident, h_rx_ant)
                V_v = np.dot(E_incident, v_rx_ant)
                pol_factor = J_rx_rotated @ np.array([V_h, V_v])

            # ── Nullify the polarization-mismatch loss (keep reflection ──────
            # magnitude AND phase). Analogous to isotropic zeroing the gains:
            # the field still carries the full complex bounce physics, but the
            # receiver captures all of its power regardless of polarization, so
            # pol_loss -> 0 while FSL, reflection loss and diffraction stay.
            if not polarization:
                _denom = abs(complex(np.atleast_1d(pol_factor)[0]))
                pol_factor = (complex(np.atleast_1d(pol_factor)[0]) / _denom * amp_E_inc
                              if _denom > 1e-12 else complex(amp_E_inc))

            # 5. Scorporo delle perdite per i log
            total_IL_and_refl_db = -20.0 * np.log10(np.clip(abs(pol_factor), 1e-12, 1.0))
            pol_loss = total_IL_and_refl_db - refl_db_true

            # Sovrascriviamo le variabili originali!
            # In questo modo la riga successiva "pl_db = fsl_db + IL_db + refl_db..." 
            # e il dizionario "results" useranno in automatico i valori 3D esatti.
            refl_db = float(refl_db_true)
            pol_los_db   = float(pol_loss)

            # ── TX departure gain ─────────────────────────────────
            ray_dir_initial = batch.initial_dirs[gi].astype(np.float64)
            # Global (travel-dir) + local (came-from, true elevation) angles.
            # arr_dir = travel into RX = -aoa_dir (aoa_dir is the came-from vector)
            _ang_nlos = compute_link_angles(
                ray_dir_initial, -aoa_dir,
                boresight_tx, h_tx_ant, v_tx_ant,
                boresight_rx, h_rx_ant, v_rx_ant,
            )
            theta_tx, phi_tx = get_antenna_local_angles(
                ray_dir_initial, boresight_tx, h_tx_ant, v_tx_ant
            )

            gain_tx_db = pattern_tx(theta_tx, phi_tx)

            # ── RX arrival gain ───────────────────────────────────
            # aoa_dir already points where the ray came from (look direction)
            theta_rx, phi_rx = get_antenna_local_angles(
                aoa_dir, boresight_rx, h_rx_ant, v_rx_ant
            )

            gain_rx_db = pattern_tx(theta_rx, phi_rx)


            # ── Isotropic / paper-validation mode ─────────────────
            # No antenna directivity (0 dBi) and co-polar capture:
            # keep the reflection magnitude |E_incident| (the paper's
            # scalar |Gamma|), drop the polarization mismatch.
            if isotropic:
                gain_tx_db           = 0.0
                gain_rx_db           = 0.0

            # ── Inject diffraction coefficient into the field ─────
            # D_diff carries both the diffraction magnitude and phase, and
            # is 1+0j for non-diffracted rays. Applied after the isotropic
            # branch so it survives in paper mode too.
            pol_factor = pol_factor * D_diff

            # ── Final field and total loss ─────────────────────────
            # Field carries antenna gains so |campo|^2 is the end-to-end
            # power and path_loss_totale_db (= -20log10|Sum campo|) matches
            # the per-ray Total. In isotropic mode gains are 0 -> factor 1.
            g_field = 10.0 ** ((gain_tx_db + gain_rx_db) / 20.0)
            campo  = amp * g_field * pol_factor * np.exp(1j * fase_geo)
            total_loss_db  = fsl_db + pol_los_db + refl_db + diff_db - gain_tx_db - gain_rx_db
            r_used = float(r_check[li]) if adaptive_mode else float(r_influence)

            if verbose or debug_mode:
                print(
                    f"Ray ID #{gi:5d} | Bounces: {b_count} | {ray_label} | "
                    f"Dist: {dist_tot:.2f} m | FSL: {fsl_db:.2f} dB | "
                    f"Refl: {refl_db:.2f} dB | Diff: {diff_db:.2f} dB | Pol Loss: {(pol_los_db):.2f} | "
                    f"IL: {total_IL_and_refl_db:.2f} dB | "
                    f"Gain TX: {gain_tx_db:.2f} dB | Gain RX: {gain_rx_db:.2f} dB | "
                    f"Total: {total_loss_db:.2f} dB | Fase: {np.degrees(fase_tot):.2f}°"
                )

            results["nlos_paths"].append({
                "ray_id":                gi,
                "bounces":               b_count,
                "has_diffracted":        bool(batch.diffracted[gi]),
                "faces_hit":             list(batch.face_ids[gi]),
                "points":                path_arr,
                "distanza_totale":       dist_tot,
                "campo_complesso":       campo,
                "fsl_db":                fsl_db,
                "pol_loss":              pol_los_db,
                "IL_db":                 float(total_IL_and_refl_db),
                "gain_tx_db":            gain_tx_db,
                "gain_rx_db":            gain_rx_db,
                "reflection_loss_db":    refl_db,
                "diffraction_loss_db":   diff_db,
                "path_loss_totale_db":   total_loss_db,
                "sfasamento_totale_rad": fase_tot,
                "sfasamento_totale_deg": np.degrees(fase_tot),
                "ritardo_assoluto_ns":   (dist_tot / c) * 1e9,
                "aoa_direction":         aoa_dir,
                **_ang_nlos,
                # "theta_tx_deg":          theta_tx,
                # "phi_tx_deg":            phi_tx,
                # "theta_rx_deg":          theta_rx,
                # "phi_rx_deg":            phi_rx,
                "dettaglio_rimbalzi":    _cronologia_with_utd(batch.cronologia[gi], D_diff),
                "r_influence_used":      round(r_used, 6),
            })

            batch.alive[gi] = False

        # ── 4f. Vectorized Fresnel reflection + Jones update ──────────
        
        refl_local_mask = (
            hit_mask
            & ~rx_hit_mask
            & ~edge_kill_local
            & batch.alive[active]
        )
        refl_local = np.where(refl_local_mask)[0]

        if len(refl_local) > 0:
            r_orig  = orig_act[refl_local]       # (M, 3)
            r_dirs  = dirs_act[refl_local]       # (M, 3)
            r_hpts  = hit_pts[refl_local]        # (M, 3)
            r_dists = hit_dists[refl_local]      # (M,)
            r_faces = hit_faces[refl_local]      # (M,)
            r_gi    = active[refl_local]         # (M,) global indices

            normals   = mesh.face_normals[r_faces].astype(np.float32)  # (M, 3)
            dot_signs = np.einsum('ij,ij->i', r_dirs, normals)         # (M,)
            flip      = dot_signs > 0.0
            normals[flip] = -normals[flip]

            # Scalar S accumulation (kept for energy pruning in 4g)
            R_vec = vec_fresnel_scalar(r_dirs, normals, epsilon_luna)
            S_old = batch.S_real[r_gi] + 1j * batch.S_imag[r_gi]
            S_new = S_old * R_vec
            batch.S_real[r_gi] = S_new.real.astype(np.float32)
            batch.S_imag[r_gi] = S_new.imag.astype(np.float32)

            # Reflected directions
            new_dirs  = vec_reflect(r_dirs, normals)                   # (M, 3)
            new_origs = r_hpts + normals * NORMAL_OFFSET               # (M, 3)

            batch.dist_acc[r_gi] += r_dists.astype(np.float32)
            batch.origins[r_gi]   = new_origs
            batch.dirs[r_gi]      = new_dirs
            batch.bounce[r_gi]   += 1

            # ── Jones vector + frame update (fully vectorized) ────
            n_f64  = normals.astype(np.float64)    # (M, 3)
            ki_f64 = r_dirs.astype(np.float64)     # (M, 3)
            ko_f64 = new_dirs.astype(np.float64)   # (M, 3)

            h_old  = batch.h_vec[r_gi].astype(np.float64)             # (M, 3)
            v_old  = batch.v_vec[r_gi].astype(np.float64)             # (M, 3)
            J_old  = (batch.J_real[r_gi]
                        + 1j * batch.J_imag[r_gi]).astype(np.complex128) # (M, 2)

            # Reconstruct 3D field: E[i] = J[i,0]*h[i] + J[i,1]*v[i]
            E_in_3d = (J_old[:, 0:1] * h_old
                        + J_old[:, 1:2] * v_old)                       # (M, 3) complex

            # TE/TM bases at each bounce — all vectorized
            # s = TE axis = normalize(cross(k_in, n))
            s_in = np.cross(ki_f64, n_f64)
            s_in_norm = np.linalg.norm(s_in, axis=1, keepdims=True)
            # Degenerate: k parallel to n (normal incidence) → pick arbitrary perp
            degen = s_in_norm[:, 0] < 1e-8
            if np.any(degen):
                fallback        = np.zeros_like(ki_f64)
                fallback[:, 0]  = 1.0
                s_in_fallback   = np.cross(fallback, n_f64)
                s_in_fallback  /= np.linalg.norm(s_in_fallback,
                                                    axis=1, keepdims=True).clip(1e-8)
                s_in = np.where(degen[:, None], s_in_fallback,
                                s_in / s_in_norm.clip(1e-8))
            else:
                s_in = s_in / s_in_norm

            p_in = np.cross(s_in, ki_f64)
            p_in = p_in / np.linalg.norm(p_in, axis=1, keepdims=True).clip(1e-8)

            s_out = np.cross(ko_f64, n_f64)
            s_out_norm = np.linalg.norm(s_out, axis=1, keepdims=True)
            if np.any(degen):
                s_out_fallback  = np.cross(fallback, n_f64)
                s_out_fallback /= np.linalg.norm(s_out_fallback,
                                                    axis=1, keepdims=True).clip(1e-8)
                s_out = np.where(degen[:, None], s_out_fallback,
                                    s_out / s_out_norm.clip(1e-8))
            else:
                s_out = s_out / s_out_norm

            p_out = np.cross(s_out, ko_f64)
            p_out = p_out / np.linalg.norm(p_out, axis=1, keepdims=True).clip(1e-8)

            # Full TE/TM Fresnel coefficients per ray
            R_TE_vec, R_TM_vec = vec_fresnel_te_tm(ki_f64, n_f64, epsilon_luna)

            # Project E onto TE/TM axes, apply coefficients, reproject
            E_te_in  = np.einsum('mi,mi->m', E_in_3d, s_in)           # (M,) complex
            E_tm_in  = np.einsum('mi,mi->m', E_in_3d, p_in)           # (M,) complex
            E_out_3d = (E_te_in[:, None] * R_TE_vec[:, None] * s_out
                        + E_tm_in[:, None] * R_TM_vec[:, None] * p_out)  # (M, 3) complex

            # Update local frame for outgoing ray
            # Use old v as up hint — ensures frame continuity across bounces
            h_new, v_new = antenna_frame_batched(ko_f64, up_tx)

            # Decompose outgoing field onto new frame
            J_new_h = np.einsum('mi,mi->m', E_out_3d,
                                h_new.astype(np.float64))              # (M,) complex
            J_new_v = np.einsum('mi,mi->m', E_out_3d,
                                v_new.astype(np.float64))              # (M,) complex

            batch.J_real[r_gi, 0] = J_new_h.real.astype(np.float32)
            batch.J_imag[r_gi, 0] = J_new_h.imag.astype(np.float32)
            batch.J_real[r_gi, 1] = J_new_v.real.astype(np.float32)
            batch.J_imag[r_gi, 1] = J_new_v.imag.astype(np.float32)
            batch.h_vec[r_gi]     = h_new.astype(np.float32)
            batch.v_vec[r_gi]     = v_new.astype(np.float32)

            # Per-bounce field magnitudes (for reflection-loss diagnostics)
            E_in_mag  = np.linalg.norm(E_in_3d,  axis=1)                # (M,)
            E_out_mag = np.linalg.norm(E_out_3d, axis=1)               # (M,)

            # Path history update (unavoidably a Python loop —
            # object arrays can't be written with pure NumPy indexing)
            for ii, gi in enumerate(r_gi):
                pl = int(batch.path_len[gi])
                if pl < batch.path_hist.shape[1]:
                    batch.path_hist[gi, pl, :] = r_hpts[ii]
                    batch.path_len[gi] = pl + 1
                batch.face_ids[gi] = list(batch.face_ids[gi]) + [int(r_faces[ii])]

                # ── Polarization state before / after this reflection ──
                pol_b, ar_b, dl_b = check_polarization_3d(
                    E_in_3d[ii],  h_old[ii], v_old[ii])
                pol_a, ar_a, dl_a = check_polarization_3d(
                    E_out_3d[ii], h_new[ii], v_new[ii])

                rl = (-20.0 * np.log10(E_out_mag[ii] / E_in_mag[ii])
                        if E_in_mag[ii] > 1e-12 and E_out_mag[ii] > 1e-12
                        else float('inf'))

                batch.cronologia[gi].append({
                    "tipo":                 "reflection",
                    "num_rimbalzo":         int(batch.bounce[gi]),
                    "face_id":              int(r_faces[ii]),
                    "punto_impatto":        r_hpts[ii].astype(np.float64).copy(),
                    "angolo_incidenza_deg": float(np.degrees(
                        np.arccos(np.clip(abs(dot_signs[ii]), 0.0, 1.0))
                    )),
                    # ── new diagnostics ──────────────────────────────
                    "R_TE":                 complex(R_TE_vec[ii]),
                    "R_TM":                 complex(R_TM_vec[ii]),
                    "refl_loss_db":         float(rl),
                    "pol_before":           pol_b,
                    "ar_before_db":         ar_b,
                    "phase_delta_before_deg": dl_b,
                    "pol_after":            pol_a,
                    "ar_after_db":          ar_a,
                    "phase_delta_after_deg":  dl_a,
                })

                # ── Debug-mode per-bounce printout ───────────────────
                if debug_mode:
                    print(
                        f"    [BOUNCE {int(batch.bounce[gi])}] face {int(r_faces[ii])} | "
                        f"inc {np.degrees(np.arccos(np.clip(abs(dot_signs[ii]),0,1))):.1f}° | "
                        f"R_TE={R_TE_vec[ii]:.3f} R_TM={R_TM_vec[ii]:.3f} | "
                        f"refl {rl:.2f} dB"
                    )
                    print(
                        f"             pol {pol_b} (AR {ar_b:.1f} dB, Δφ {dl_b:.0f}°)"
                        f"  ->  {pol_a} (AR {ar_a:.1f} dB, Δφ {dl_a:.0f}°)"
                    )

        # ── 4g. Early-out pruning ──────────────────────────────────────
        S_mag       = np.sqrt(batch.S_real[active] ** 2
                                + batch.S_imag[active] ** 2)
        low_energy  = active[S_mag < energy_threshold]
        batch.alive[low_energy] = False

        over_dist   = active[batch.dist_acc[active] > max_path_distance]
        batch.alive[over_dist] = False

        over_bounce = active[batch.bounce[active] > max_bounces]
        batch.alive[over_bounce] = False

        missed = active[~hit_mask]
        batch.alive[missed] = False

    # ------------------------------------------------------------------
    # 5. Profiling output
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    # 6. Coherent grouping + final report
    # ------------------------------------------------------------------
    # Raw micro-ray count (before coherent grouping) for diagnostics
    n_raw_multipath = len([p for p in results["nlos_paths"] if p["bounces"] > 0])

    seen_signatures = {}

    for p in results["nlos_paths"]:
        current_gi = p.get("ray_id", -1)
        sig = (p["bounces"], tuple(p["faces_hit"]), p["has_diffracted"])

        if sig not in seen_signatures:
            seen_signatures[sig] = p.copy()
            seen_signatures[sig]["membro_raggruppamento"] = [current_gi]
            seen_signatures[sig]["potenza_incoerente"] = abs(p["campo_complesso"]) ** 2
        else:
            seen_signatures[sig]["campo_complesso"] += p["campo_complesso"]
            seen_signatures[sig]["membro_raggruppamento"].append(current_gi)
            seen_signatures[sig]["potenza_incoerente"] += abs(p["campo_complesso"]) ** 2

    for sig, p in seen_signatures.items():
        # Redundant micro-rays sample the SAME physical path -> average the
        # coherently-summed field (mean is the unbiased per-path estimate;
        # summing would over-count by 20log10(N)). The coherent sum is still
        # recoverable as N * campo_complesso for the interference diagnostic.
        n_micro = len(p["membro_raggruppamento"])
        if n_micro > 1:
            p["campo_complesso"] = p["campo_complesso"] / n_micro
        mag_final = abs(p["campo_complesso"])
        p["path_loss_totale_db"] = (
            -20.0 * np.log10(mag_final) if mag_final > 1e-15 else float('inf')
        )

    results["nlos_paths"] = list(seen_signatures.values())

    print("\n" + "=" * 60)
    print(f"   RAY TRACING FINAL REPORT | f = {frequenza/1e9:.2f} GHz")
    print("=" * 60)
    print(f"  TX Pol: {tx_pol} | RX Pol: {rx_pol}"
          + ("" if polarization else "  [POL-MISMATCH LOSS NULLED — bounce physics intact]"))
    print(f"  Direct rays captured (SBR)  : {results['primary_rays_captured']}")
    print("-" * 60)

    for b in range(1, max_bounces + 1):
        comps_b = [p for p in results["nlos_paths"] if p["bounces"] == b]
        r_count = len([p for p in comps_b if not p["has_diffracted"]])
        d_count = len([p for p in comps_b if p["has_diffracted"]])
        total_b = r_count + d_count
        if total_b > 0:
            micro_b = sum(len(p.get("membro_raggruppamento", [])) for p in comps_b)
            print(f"  Paths reaching RX with exactly {b} bounce(s): {total_b} "
                  f"coherent component(s) from {micro_b} micro-ray(s)")
            print(f"     ├─ Pure Reflections: {r_count}")
            print(f"     └─ Diffracted Paths: {d_count}")
            for p in comps_b:
                tag = "K" if p["has_diffracted"] else "P"
                print(f"        • [{tag}] faces {tuple(p['faces_hit'])}: "
                      f"{len(p.get('membro_raggruppamento', []))} micro-ray(s) "
                      f"→ {p['path_loss_totale_db']:.2f} dB")

    n_components = len([p for p in results["nlos_paths"] if p["bounces"] > 0])
    print("-" * 60)
    print(f"  Keller Diffraction Events Triggered : {total_edges_triggered}")
    print(f"  Raw multipath micro-rays captured   : {n_raw_multipath}")
    print(f"  Coherent multipath components at RX : {n_components}")
    print("=" * 60 + "\n")

    return results