"""engine_image — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import itertools
import numpy as np
from constants import C_LIGHT, MAX_PATH_DIST, S_MIN_MAGNITUDE
from em_core import antenna_frame, antenna_gain_pattern_2d, check_polarization_3d, compute_link_angles, get_antenna_local_angles, jones_vector, sionna_hv_basis, vec_fresnel_te_tm
from geometry import _point_in_triangle, _segment_plane_intersection, _segments_clear, check_los
from timing import SectionTimer


def _assemble_reflection_path(
    pts:        np.ndarray,        # (K+2, 3): TX, P1, ..., PK, RX
    face_seq:   List[int],
    ray_id:     int,
    *,
    mesh:       trimesh.Trimesh,
    pos_tx:     np.ndarray,
    pos_rx:     np.ndarray,
    wavelength: float,
    k:          float,
    epsilon:    complex,
    J_tx:       np.ndarray,
    J_rx_rotated: np.ndarray,
    h_tx_ant: np.ndarray, v_tx_ant: np.ndarray,
    h_rx_ant: np.ndarray, v_rx_ant: np.ndarray,
    boresight_tx: np.ndarray, boresight_rx: np.ndarray,
    up_tx: np.ndarray,
    G_max_db: float, hpbw_h: float, hpbw_v: float,
    isotropic: bool,
    pattern_tx = None,
    pattern_rx = None,
    # ── Polarization convention toggle ────────────────────────────────────
    pol_convention: str = "fixed",     # "fixed" (antenna-axis) | "sionna" (ray-spherical)
    J_rx:   np.ndarray = None,         # raw RX Jones — required for "sionna"
    up_rx:  np.ndarray = None,         # RX up axis    — required for "sionna"
    polarization: bool = True,         # False -> pol_loss forced to 0 dB
) -> dict:
    """Compute the full complex field and the SBR-compatible result dict for a
    deterministic specular path. Mirrors the capture block (4e) + Jones update
    (4f) of the SBR engine, but driven by known geometry instead of bounces.

    The launch basis and the RX projection are the ONLY places the EM
    polarization convention enters:

      * pol_convention="fixed"  — V/H are the antenna-frame axes (a physical,
        ray-independent vertical), captured via J_rx_rotated. This is the
        original fixed-axis model.
      * pol_convention="sionna" — V/H are the local spherical theta_hat/phi_hat
        of each ray direction (Sionna's ideal isotropic V/H antenna), captured
        via vdot with the ray-dependent receive vector. Requires J_rx, up_rx.

    Everything else (geometry, Fresnel, gains, FSL, phase, return schema) is
    identical between the two conventions."""
    if pol_convention not in ("fixed", "sionna"):
        raise ValueError(f"pol_convention must be 'fixed' or 'sionna', got {pol_convention!r}")
    if pol_convention == "sionna" and (J_rx is None or up_rx is None):
        raise ValueError("pol_convention='sionna' requires J_rx and up_rx")
    pts = np.asarray(pts, dtype=np.float64)
    K = len(face_seq)

    # Segment directions: K+1 of them (TX->P1, ..., PK->RX)
    seg = np.diff(pts, axis=0)
    seg_len = np.linalg.norm(seg, axis=1)
    if np.any(seg_len < 1e-9):
        return None
    dirs = seg / seg_len[:, None]
    dist_tot = float(seg_len.sum())

    # ── Launch field: Jones in the basis transverse to the launch dir ─────
    if pol_convention == "sionna":
        h0, v0 = sionna_hv_basis(ray_dir=dirs[0], boresight=boresight_tx, up=up_tx)
    else:
        h0, v0 = antenna_frame(dirs[0], up_tx)
    E = J_tx[0] * h0 + J_tx[1] * v0          # (3,) complex 3D field, |E|=1

    cronologia = []
    for b in range(K):
        fid   = int(face_seq[b])
        n     = mesh.face_normals[fid].astype(np.float64)
        k_in  = dirs[b]
        if np.dot(k_in, n) > 0.0:
            n = -n
        k_out = dirs[b + 1]                  # geometric (== specular) outgoing

        # TE/TM bases at incidence and reflection
        s_in = np.cross(k_in, n)
        ni = np.linalg.norm(s_in)
        if ni < 1e-8:                        # normal incidence: pick arbitrary perp
            s_in = np.cross(np.array([1.0, 0.0, 0.0]), n)
            s_in /= max(np.linalg.norm(s_in), 1e-8)
        else:
            s_in /= ni
        p_in = np.cross(s_in, k_in); p_in /= max(np.linalg.norm(p_in), 1e-8)

        s_out = np.cross(k_out, n)
        no = np.linalg.norm(s_out)
        if no < 1e-8:
            s_out = s_in.copy()
        else:
            s_out /= no
        p_out = np.cross(s_out, k_out); p_out /= max(np.linalg.norm(p_out), 1e-8)

        R_TE, R_TM = vec_fresnel_te_tm(k_in[None, :], n[None, :], epsilon)
        R_TE = complex(R_TE[0]); R_TM = complex(R_TM[0])

        E_te = np.dot(E, s_in)
        E_tm = np.dot(E, p_in)
        E_before = E
        E = E_te * R_TE * s_out + E_tm * R_TM * p_out

        # Per-bounce diagnostics (frames consistent with SBR's antenna_frame)
        h_b, v_b = antenna_frame(k_in,  up_tx)
        h_a, v_a = antenna_frame(k_out, up_tx)
        pol_b, ar_b, dl_b = check_polarization_3d(E_before, h_b, v_b)
        pol_a, ar_a, dl_a = check_polarization_3d(E,        h_a, v_a)
        e_in_mag  = np.linalg.norm(E_before)
        e_out_mag = np.linalg.norm(E)
        rl = (-20.0 * np.log10(e_out_mag / e_in_mag)
              if e_in_mag > 1e-12 and e_out_mag > 1e-12 else float('inf'))
        cos_inc = np.clip(abs(np.dot(k_in, n)), 0.0, 1.0)
        cronologia.append({
            "tipo":                 "reflection",
            "num_rimbalzo":         b + 1,
            "face_id":              fid,
            "punto_impatto":        pts[b + 1].copy(),
            "angolo_incidenza_deg": float(np.degrees(np.arccos(cos_inc))),
            "R_TE":                 R_TE,
            "R_TM":                 R_TM,
            "refl_loss_db":         float(rl),
            "pol_before":           pol_b, "ar_before_db": ar_b,
            "phase_delta_before_deg": dl_b,
            "pol_after":            pol_a, "ar_after_db": ar_a,
            "phase_delta_after_deg":  dl_a,
        })

    # ── Capture at RX (mirrors SBR section 4e) ─────────────────────────────
    amp = wavelength / (4.0 * np.pi * dist_tot)
    fsl_db = -20.0 * np.log10(amp)

    amp_E = np.clip(np.linalg.norm(E), 1e-12, 1.0)
    refl_db = -20.0 * np.log10(amp_E)          # reflection loss embedded in |E|

    if pol_convention == "sionna":
        # Ray-dependent spherical V/H at the came-from direction; coherent
        # complex receive voltage via vdot (conjugates the receive vector).
        h_rx_ray, v_rx_ray = sionna_hv_basis(
            ray_dir=-dirs[-1], boresight=boresight_rx, up=up_rx
        )
        e_rx = J_rx[0] * h_rx_ray + J_rx[1] * v_rx_ray
        pol_factor = complex(np.vdot(e_rx, E))
    else:
        # Fixed antenna-axis projection captured through the rotated RX Jones.
        V_h = np.dot(E, h_rx_ant)
        V_v = np.dot(E, v_rx_ant)
        pol_factor = (J_rx_rotated @ np.array([V_h, V_v]))
        pol_factor = complex(np.atleast_1d(pol_factor)[0])

    # ── Nullify the polarization-mismatch loss (keep reflection magnitude +
    # phase). The complex bounce field is untouched; only the antenna mismatch
    # at capture is removed, so pol_loss -> 0 and refl_db is preserved.
    if not polarization:
        _denom = abs(pol_factor)
        pol_factor = (pol_factor / _denom * amp_E if _denom > 1e-12 else complex(amp_E))
    total_IL_and_refl_db = -20.0 * np.log10(np.clip(abs(pol_factor), 1e-12, 1.0))
    pol_loss = total_IL_and_refl_db - refl_db

    # Antenna gains
    theta_tx, phi_tx = get_antenna_local_angles(dirs[0], boresight_tx, h_tx_ant, v_tx_ant)
    gain_tx_db = antenna_gain_pattern_2d(theta_tx, phi_tx, G_max_db, hpbw_h, hpbw_v)
    aoa_dir = dirs[-1]                          # travel direction at RX
    theta_rx, phi_rx = get_antenna_local_angles(-aoa_dir, boresight_rx, h_rx_ant, v_rx_ant)
    gain_rx_db = antenna_gain_pattern_2d(theta_rx, phi_rx, G_max_db, hpbw_h, hpbw_v)

    if isotropic:
        gain_tx_db           = 0.0
        gain_rx_db           = 0.0

    
    fase_geo = -k * dist_tot
    fase_geo_norm = fase_geo % (2.0 * np.pi)

    g_field = 10.0 ** ((gain_tx_db + gain_rx_db) / 20.0)

    campo = amp * g_field * pol_factor * np.exp(1j * fase_geo)

    total_loss_db = fsl_db + pol_loss + refl_db - gain_tx_db - gain_rx_db

    # Extra phase diagnostics
    phase_campo_rad = np.angle(campo)
    phase_campo_deg = np.angle(campo, deg=True)

    # Sionna-style coefficient phase: remove geometric propagation phase
    campo_no_geo = campo * np.exp(1j * k * dist_tot)
    phase_no_geo_rad = np.angle(campo_no_geo)
    phase_no_geo_deg = np.angle(campo_no_geo, deg=True)

    # Global (travel-dir) + local (came-from, true elevation) angles, TX & RX.
    # dirs[0] = departure travel, dirs[-1] = arrival travel.
    _ang = compute_link_angles(
        dirs[0], dirs[-1],
        boresight_tx, h_tx_ant, v_tx_ant,
        boresight_rx, h_rx_ant, v_rx_ant,
    )

    return {
        "ray_id":                ray_id,
        "bounces":               K,
        "has_diffracted":        False,
        "faces_hit":             list(int(f) for f in face_seq),
        "points":                pts.copy(),
        "distanza_totale":       dist_tot,
        "campo_complesso":       campo,

        "campo_no_geo":          campo_no_geo,

        "fsl_db":                fsl_db,
        "pol_loss":              float(pol_loss),
        "IL_db":                 float(total_IL_and_refl_db),
        "gain_tx_db":            gain_tx_db,
        "gain_rx_db":            gain_rx_db,
        "reflection_loss_db":    float(refl_db),
        "diffraction_loss_db":   0.0,
        "path_loss_totale_db":   total_loss_db,

        # Old fields, kept for compatibility
        "sfasamento_totale_rad": fase_geo_norm,
        "sfasamento_totale_deg": np.degrees(fase_geo_norm),

        # Clearer names
        "sfasamento_geometrico_rad": fase_geo_norm,
        "sfasamento_geometrico_deg": np.degrees(fase_geo_norm),

        # Actual complex-field phase
        "phase_campo_rad":       phase_campo_rad,
        "phase_campo_deg":       phase_campo_deg,

        # Sionna-comparable phase
        "phase_no_geo_rad":      phase_no_geo_rad,
        "phase_no_geo_deg":      phase_no_geo_deg,

        "ritardo_assoluto_ns":   (dist_tot / C_LIGHT) * 1e9,
        "aoa_direction":         aoa_dir,
        **_ang,
        "theta_tx_deg":          theta_tx,
        "phi_tx_deg":            phi_tx,
        "theta_rx_deg":          theta_rx,
        "phi_rx_deg":            phi_rx,
        "dettaglio_rimbalzi":    cronologia,
        "r_influence_used":      None,
    }


def _find_first_order_paths(
    mesh:    trimesh.Trimesh,
    pos_tx:  np.ndarray,
    pos_rx:  np.ndarray,
    cand_faces: np.ndarray,     # (F,) candidate face indices
) -> List[Tuple[np.ndarray, List[int]]]:
    """Fully vectorized single-bounce image method over all candidate facets.
    Returns a list of (points (3,3): [TX,P,RX], [face_id])."""
    if len(cand_faces) == 0:
        return []

    tri = mesh.vertices[mesh.faces[cand_faces]].astype(np.float64)   # (F,3,3)
    N   = mesh.face_normals[cand_faces].astype(np.float64)           # (F,3)
    V0  = tri[:, 0, :]                                               # (F,3)

    d_tx = np.einsum('fi,fi->f', pos_tx[None] - V0, N)               # (F,)
    d_rx = np.einsum('fi,fi->f', pos_rx[None] - V0, N)               # (F,)

    same_side = (d_tx * d_rx) > 0.0
    denom     = d_tx + d_rx
    t = np.where(np.abs(denom) > 1e-12, d_tx / np.where(np.abs(denom) > 1e-12, denom, 1.0), -1.0)

    TX_img = pos_tx[None] - 2.0 * d_tx[:, None] * N                  # (F,3)
    P = TX_img + t[:, None] * (pos_rx[None] - TX_img)                # (F,3)

    inside = _point_in_triangle(P, tri)
    geo_ok = same_side & (t > 1e-6) & (t < 1.0 - 1e-6) & inside
    idx = np.where(geo_ok)[0]
    if len(idx) == 0:
        return []

    Pg   = P[idx]
    Ng   = N[idx]
    fids = cand_faces[idx]

    tx_b = np.tile(pos_tx, (len(idx), 1))
    rx_b = np.tile(pos_rx, (len(idx), 1))
    clear_in  = _segments_clear(mesh, tx_b, Pg)                      # TX -> P
    clear_out = _segments_clear(mesh, Pg, rx_b, nudge_normals=Ng)    # P  -> RX
    keep = clear_in & clear_out

    out = []
    for j in np.where(keep)[0]:
        out.append((np.vstack([pos_tx, Pg[j], pos_rx]), [int(fids[j])]))
    return out


def _backtrace_image_chain(
    mesh:    trimesh.Trimesh,
    pos_tx:  np.ndarray,
    pos_rx:  np.ndarray,
    face_seq: Tuple[int, ...],
) -> Optional[np.ndarray]:
    """Given an ordered facet sequence (f1..fK), build the image chain and
    back-trace the reflection points. Returns points (K+2,3) [TX,P1..PK,RX]
    or None if the sequence yields no valid specular path."""
    K = len(face_seq)
    V0 = np.array([mesh.vertices[mesh.faces[f]][0] for f in face_seq], dtype=np.float64)  # (K,3)
    N  = mesh.face_normals[list(face_seq)].astype(np.float64)                              # (K,3)

    # Forward image chain: I_0 = TX, I_i = mirror(I_{i-1}, plane f_i)
    images = [pos_tx.astype(np.float64)]
    cur = pos_tx.astype(np.float64)
    for i in range(K):
        d = np.dot(cur - V0[i], N[i])
        cur = cur - 2.0 * d * N[i]
        images.append(cur)                  # images[i+1] = image after facet f_{i+1}

    # Backward back-trace: reflection point on f_i from segment I_i -> target
    pts = [None] * (K + 2)
    pts[0] = pos_tx.astype(np.float64)
    pts[K + 1] = pos_rx.astype(np.float64)
    target = pos_rx.astype(np.float64)
    for i in range(K, 0, -1):               # i = K .. 1
        Ai = images[i]                      # image of TX through f_1..f_i
        P, t = _segment_plane_intersection(
            Ai[None, :], target[None, :], V0[i - 1][None, :], N[i - 1][None, :]
        )
        P = P[0]; t = float(t[0])
        if not (1e-6 < t < 1.0 - 1e-6):
            return None
        tri = mesh.vertices[mesh.faces[face_seq[i - 1]]].astype(np.float64)[None]
        if not _point_in_triangle(P[None, :], tri)[0]:
            return None
        pts[i] = P
        target = P
    return np.array(pts, dtype=np.float64)


def _find_higher_order_paths(
    mesh:    trimesh.Trimesh,
    pos_tx:  np.ndarray,
    pos_rx:  np.ndarray,
    cand_faces: np.ndarray,
    order:   int,
    image_max_sequences: int,
    verbose: bool,
) -> List[Tuple[np.ndarray, List[int]]]:
    """Image-tree enumeration for `order` >= 2. Correct but O(F^order)."""
    F = len(cand_faces)
    n_seq = F ** order
    if n_seq > image_max_sequences:
        if verbose:
            print(f"  [image] order {order}: {F}^{order} = {n_seq:.3e} sequences "
                  f"> cap {image_max_sequences:.1e} — SKIPPED. "
                  f"Lower image_max_candidate_faces or max_bounces.")
        return []

    out = []
    for seq in itertools.permutations(cand_faces, order):
        # adjacent identical facets are physically meaningless
        if any(seq[i] == seq[i + 1] for i in range(order - 1)):
            continue
        # Exact specular vertices for this facet chain (None if invalid / off-facet).
        pts = _backtrace_image_chain(mesh, pos_tx, pos_rx, seq)
        if pts is None:
            continue
        K = len(seq)
        # Per-leg occlusion: segment s starts at pts[s]; for s>=1 that point lies
        # on facet seq[s-1], so nudge its start off that facet's plane.
        seg_starts = pts[:-1].copy()
        seg_ends   = pts[1:].copy()
        nudges = np.zeros_like(seg_starts)
        for s in range(1, K + 1):
            nudges[s] = mesh.face_normals[seq[s - 1]]
        if np.all(_segments_clear(mesh, seg_starts, seg_ends, nudge_normals=nudges)):
            out.append((pts, [int(f) for f in seq]))
    return out


def run_image_method_engine(
    mesh:                           trimesh.Trimesh,
    pos_tx:                         np.ndarray,
    pos_rx:                         np.ndarray,
    r_influence=None,                                  # accepted, unused (kept for drop-in parity)
    # ── Antenna configuration ────────────────────────────────────────────
    boresight_tx:                   np.ndarray = None,
    boresight_rx:                   np.ndarray = None,
    up_tx:                          np.ndarray = None,
    up_rx:                          np.ndarray = None,
    tx_pol:                         str = "RHCP",
    rx_pol:                         str = "RHCP",
    G_max_db:                       float = 12.0,
    hpbw_h:                         float = 30.0,
    hpbw_v:                         float = 60.0,
    # ── Engine parameters ────────────────────────────────────────────────
    num_rays:                       int = 0,           # accepted, unused
    max_bounces:                    int = 1,
    epsilon_luna:                   complex = 2.87 - 0.01j,
    frequenza:                      float = 2.4e9,
    enable_diffractions:            bool = False,      # not modeled here
    edge_tolerance:                 float = 0.01,
    adaptive_min_wavelength_factor: float = 0.5,
    adaptive_max_cap_meters:        float = 20.0,
    launch_mode:                    str = "full_sphere",
    horizon_margin_deg:             float = 3.0,
    energy_threshold:               float = S_MIN_MAGNITUDE,
    max_path_distance:              float = MAX_PATH_DIST,
    num_diff_rays:                  int = 6,
    enable_profiling:               bool = False,
    verbose:                        bool = True,
    isotropic:                      bool = False,
    extract_diffraction_edges:      Optional[Callable] = None,
    generate_keller_cone_rays:      Optional[Callable] = None,
    check_edge_collision:           Optional[Callable] = None,
    debug_ray_direction:            Optional[np.ndarray] = None,
    # ── Image-method specific knobs ───────────────────────────────────────
    image_max_candidate_faces:      Optional[int] = None,   # subsample facets
    image_max_sequences:            float = 5_000_000,      # guard for order>=2
    # ── Polarization convention ───────────────────────────────────────────
    pol_convention:                 str = "fixed",          # "fixed" | "sionna"
    polarization:                   bool = True,            # False -> pol_loss = 0 dB
) -> dict:
    """
    Deterministic image-method multipath engine. Same call signature and
    `results` schema as `run_complete_multipath_engine_batched_2`, so it can be
    passed to `run_campaign_2(..., engine_fn=run_image_method_engine)`.

    Differences from SBR:
      * `num_rays`, `r_influence`, `launch_mode`, the adaptive-sphere and
        Keller-cone parameters are accepted (for drop-in parity) but unused.
      * Paths are exact specular reflections, not reception-sphere captures —
        each facet sequence yields at most one coherent path (no micro-rays,
        no coherent-grouping step needed).
      * Diffraction is not modeled here (the UTD machinery could be bolted on
        as a separate edge pass; see module docstring).
    """
    c          = C_LIGHT
    wavelength = c / frequenza
    k          = 2.0 * np.pi / wavelength

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)

    # ── Antenna frames / polarization (identical to SBR setup) ────────────
    boresight_tx = np.asarray(boresight_tx, dtype=np.float64); boresight_tx /= np.linalg.norm(boresight_tx)
    boresight_rx = np.asarray(boresight_rx, dtype=np.float64); boresight_rx /= np.linalg.norm(boresight_rx)
    up_tx = np.asarray(up_tx, dtype=np.float64); up_tx /= np.linalg.norm(up_tx)
    up_rx = np.asarray(up_rx, dtype=np.float64); up_rx /= np.linalg.norm(up_rx)

    h_tx_ant, v_tx_ant = antenna_frame(boresight_tx, up_tx)
    h_rx_ant, v_rx_ant = antenna_frame(boresight_rx, up_rx)

    J_tx = jones_vector(tx_pol)
    J_rx = jones_vector(rx_pol)
    J_rx_rotated = np.conj(J_rx).T @ np.array([[-1, 0], [0, 1]])

    results = {
        "los_segment":           None,
        "los_blocked":           False,
        "los_paths":             [],
        "nlos_paths":            [],
        "keller_events":         [],
        "primary_rays_captured": 0,
        "r_influence_mode":      "image_method",
    }

    timer = SectionTimer()

    # ── 1. LoS (direct path) — same treatment as SBR section 1 ────────────
    with timer("los_check"):
        los_vec  = pos_rx - pos_tx
        los_dist = float(np.linalg.norm(los_vec))
        los_dir  = los_vec / los_dist
        los_blocked, blocking_pt = check_los(mesh, pos_tx, pos_rx)

    if los_blocked:
        results["los_blocked"] = True
        results["los_segment"] = np.vstack((pos_tx, blocking_pt))
        if verbose:
            print(f"\n[LOS INFO] Blocked at {np.round(blocking_pt, 2)}")
    else:
        results["los_segment"] = np.vstack((pos_tx, pos_rx))
        amp_los  = wavelength / (4.0 * np.pi * los_dist)
        fsl_db   = -20.0 * np.log10(amp_los)
        fase_geo = -k * los_dist
        fase_norm = fase_geo % (2.0 * np.pi)

        if pol_convention == "sionna":
            h_tx_los, v_tx_los = sionna_hv_basis(ray_dir=los_dir, boresight=boresight_tx, up=up_tx)
            E_los = J_tx[0] * h_tx_los + J_tx[1] * v_tx_los
            h_rx_los, v_rx_los = sionna_hv_basis(ray_dir=-los_dir, boresight=boresight_rx, up=up_rx)
            e_rx_los = J_rx[0] * h_rx_los + J_rx[1] * v_rx_los
            pol_factor_los = complex(np.vdot(e_rx_los, E_los))
        else:
            h_ray_los, v_ray_los = antenna_frame(los_dir, up_tx)
            R_los = np.array([
                [np.dot(h_ray_los, h_rx_ant), np.dot(v_ray_los, h_rx_ant)],
                [np.dot(h_ray_los, v_rx_ant), np.dot(v_ray_los, v_rx_ant)],
            ])
            pol_factor_los = complex(np.atleast_1d(J_rx_rotated @ R_los @ J_tx)[0])
        if not polarization:
            _d = abs(pol_factor_los)
            pol_factor_los = pol_factor_los / _d if _d > 1e-12 else complex(1.0)
        IL_los_db = -20.0 * np.log10(np.clip(abs(pol_factor_los), 1e-10, 1.0))

        theta_tx_los, phi_tx_los = get_antenna_local_angles(los_dir, boresight_tx, h_tx_ant, v_tx_ant)
        gain_tx_los = antenna_gain_pattern_2d(theta_tx_los, phi_tx_los, G_max_db, hpbw_h, hpbw_v)
        theta_rx_los, phi_rx_los = get_antenna_local_angles(-los_dir, boresight_rx, h_rx_ant, v_rx_ant)
        gain_rx_los = antenna_gain_pattern_2d(theta_rx_los, phi_rx_los, G_max_db, hpbw_h, hpbw_v)

        if isotropic:
            gain_tx_los = 0.0; gain_rx_los = 0.0

        g_field_los = 10.0 ** ((gain_tx_los + gain_rx_los) / 20.0)
        campo_los   = amp_los * g_field_los * pol_factor_los * np.exp(1j * fase_geo)
        total_loss_los = fsl_db + IL_los_db - gain_tx_los - gain_rx_los

        aoa_dir_los = -los_dir
        aoa_az = np.degrees(np.arctan2(aoa_dir_los[1], aoa_dir_los[0]))
        aoa_el = np.degrees(np.arcsin(np.clip(aoa_dir_los[2], -1.0, 1.0)))

        if verbose:
            print(f"\n[LOS INFO] LoS CLEAR | Dist: {los_dist:.2f} m | FSL: {fsl_db:.2f} dB | "
                  f"Total Loss: {total_loss_los:.2f} dB")

        results["primary_rays_captured"] = 1
        results["nlos_paths"].append({
            "ray_id": -1, "bounces": 0, "has_diffracted": False, "faces_hit": [],
            "points": np.array([pos_tx, pos_rx]), "distanza_totale": los_dist,
            "campo_complesso": campo_los, "fsl_db": fsl_db, "IL_db": float(IL_los_db),
            "gain_tx_db": gain_tx_los, "gain_rx_db": gain_rx_los,
            "reflection_loss_db": 0.0, "diffraction_loss_db": 0.0,
            "path_loss_totale_db": total_loss_los,
            "sfasamento_totale_rad": fase_norm, "sfasamento_totale_deg": np.degrees(fase_norm),
            "ritardo_assoluto_ns": (los_dist / c) * 1e9,
            "aoa_direction": aoa_dir_los, "aoa_azimuth_deg": aoa_az, "aoa_elevation_deg": aoa_el,
            "theta_tx_deg": theta_tx_los, "phi_tx_deg": phi_tx_los,
            "theta_rx_deg": theta_rx_los, "phi_rx_deg": phi_rx_los,
            "dettaglio_rimbalzi": [], "r_influence_used": None,
        })

    # ── 2. Candidate facet set ────────────────────────────────────────────
    F_all = len(mesh.faces)
    print(f"Total number of meshes: {F_all}")
    cand = np.arange(F_all)
    if image_max_candidate_faces is not None and F_all > image_max_candidate_faces:
        # deterministic uniform subsample (keeps geometry coverage)
        cand = np.linspace(0, F_all - 1, image_max_candidate_faces).astype(int)
        cand = np.unique(cand)
        if verbose:
            print(f"  [image] subsampling facets: {F_all} -> {len(cand)}")

    if verbose:
        print(f"\n--- Launching Image-Method Engine | "
              f"{len(cand)} candidate facets | max_bounces={max_bounces} ---")

    # ── 3. Specular path search per order ─────────────────────────────────
    ray_id = 0
    found_per_order = {}

    if max_bounces >= 1:
        with timer("order_1"):
            o1 = _find_first_order_paths(mesh, pos_tx, pos_rx, cand)
        found_per_order[1] = len(o1)
        for pts, fseq in o1:
            d = _assemble_reflection_path(
                pts, fseq, ray_id, mesh=mesh, pos_tx=pos_tx, pos_rx=pos_rx,
                wavelength=wavelength, k=k, epsilon=epsilon_luna,
                J_tx=J_tx, J_rx_rotated=J_rx_rotated,
                h_tx_ant=h_tx_ant, v_tx_ant=v_tx_ant, h_rx_ant=h_rx_ant, v_rx_ant=v_rx_ant,
                boresight_tx=boresight_tx, boresight_rx=boresight_rx, up_tx=up_tx,
                G_max_db=G_max_db, hpbw_h=hpbw_h, hpbw_v=hpbw_v, isotropic=isotropic,
                J_rx=J_rx, up_rx=up_rx, pol_convention=pol_convention,
                polarization=polarization,
            )
            if d is None or d["distanza_totale"] > max_path_distance:
                continue
            if verbose:
                print(f"Ray #{ray_id:5d} | Bounces: 1 | [P] face {fseq} | "
                      f"Dist: {d['distanza_totale']:.2f} m | FSL: {d['fsl_db']:.2f} dB | "
                      f"Refl: {d['reflection_loss_db']:.2f} dB | "
                      f"Total: {d['path_loss_totale_db']:.2f} dB")
            results["nlos_paths"].append(d)
            ray_id += 1

    for order in range(2, max_bounces + 1):
        
        # =================================================================
        # STAGE 1: FAST CULLING (Normals + Ellipsoid Distance)
        # =================================================================
        cents_full = mesh.triangles_center[cand]
        norms_full = mesh.face_normals[cand]
        
        vec_tx_full = pos_tx - cents_full
        vec_rx_full = pos_rx - cents_full
        
        # 1A. Normal Culling — DISABLED for the candidate pre-cull. A planar
        # facet reflects from either side (the assembler flips the normal as
        # needed), so a winding-dependent dot>0 test wrongly drops valid
        # reflectors; for order>=2 the facet reflects an IMAGE source, not TX/RX
        # directly, so facing is meaningless. Distance is the only safe geometric
        # pre-cull; backtrace (point-in-triangle) + occlusion validate exactly.
        dot_tx = np.einsum('ij,ij->i', norms_full, vec_tx_full)
        dot_rx = np.einsum('ij,ij->i', norms_full, vec_rx_full)
        mask_facing = np.ones(len(cand), dtype=bool)
        
        # 1B. Distance / Ellipsoid Culling
        los_dist = np.linalg.norm(pos_tx - pos_rx)
        # Valid for ANY order: straight-line dist(F,TX)+dist(F,RX) can't exceed
        # the path length, so this is a correct superset cull when the budget is
        # the engine's real max_path_distance (the old los_dist*1.2 wrongly
        # pruned every genuine >=1-bounce facet that sits off the TX-RX line).
        max_path_dist = max_path_distance
        
        dist_tx_full = np.linalg.norm(vec_tx_full, axis=1)
        dist_rx_full = np.linalg.norm(vec_rx_full, axis=1)
        mask_dist = (dist_tx_full + dist_rx_full) <= max_path_dist

        # Apply the fast masks to create a much smaller candidate list
        cand_stage1 = cand[mask_facing & mask_dist]
        
        if verbose:
            print(f"  [Stage 1 Fast Cull] order {order}: reduced from {len(cand)} to {len(cand_stage1)}")

        # =================================================================
        # STAGE 2: visibility/shadow cull — SKIPPED for order>=2. A facet
        # reached via an earlier bounce need not be directly visible from an
        # endpoint, so the direct-visibility raycast can prune valid multi-bounce
        # reflectors. The per-leg occlusion test inside _find_higher_order_paths
        # is exact, so we pass the distance-culled set straight through.
        # =================================================================
        optimized_cand = cand_stage1
        with timer(f"order_{order}"):
            ok = _find_higher_order_paths(
                mesh, pos_tx, pos_rx, optimized_cand, order, image_max_sequences, verbose
            )
        found_per_order[order] = len(ok)
        for pts, fseq in ok:
            d = _assemble_reflection_path(
                pts, fseq, ray_id, mesh=mesh, pos_tx=pos_tx, pos_rx=pos_rx,
                wavelength=wavelength, k=k, epsilon=epsilon_luna,
                J_tx=J_tx, J_rx_rotated=J_rx_rotated,
                h_tx_ant=h_tx_ant, v_tx_ant=v_tx_ant, h_rx_ant=h_rx_ant, v_rx_ant=v_rx_ant,
                boresight_tx=boresight_tx, boresight_rx=boresight_rx, up_tx=up_tx,
                G_max_db=G_max_db, hpbw_h=hpbw_h, hpbw_v=hpbw_v, isotropic=isotropic,
                J_rx=J_rx, up_rx=up_rx, pol_convention=pol_convention,
                polarization=polarization,
            )
            if d is None or d["distanza_totale"] > max_path_distance:
                continue
            if verbose:
                print(f"Ray #{ray_id:5d} | Bounces: {order} | [P] faces {fseq} | "
                      f"Dist: {d['distanza_totale']:.2f} m | "
                      f"Total: {d['path_loss_totale_db']:.2f} dB")
            results["nlos_paths"].append(d)
            ray_id += 1

    # Each specular path is already a unique coherent component — annotate so
    # downstream code that expects the SBR grouping fields keeps working.
    for p in results["nlos_paths"]:
        p.setdefault("membro_raggruppamento", [p.get("ray_id", -1)])
        p.setdefault("potenza_incoerente", abs(p["campo_complesso"]) ** 2)

    if enable_profiling:
        timer.report()

    # ── Report ─────────────────────────────────────────────────────────────
    if verbose:
        print("\n" + "=" * 60)
        print(f"   IMAGE-METHOD FINAL REPORT | f = {frequenza/1e9:.2f} GHz")
        print("=" * 60)
        print(f"  TX Pol: {tx_pol} | RX Pol: {rx_pol}")
        print(f"  Direct (LoS) path captured  : {results['primary_rays_captured']}")
        for o in sorted(found_per_order):
            n_specular = len([p for p in results['nlos_paths'] if p['bounces'] == o])
            print(f"  Order-{o} specular paths       : {n_specular}")
        n_components = len([p for p in results["nlos_paths"] if p["bounces"] > 0])
        print(f"  Total multipath components    : {n_components}")
        print("=" * 60 + "\n")

    return results


def _backtrace_image_chain_batch(
    mesh:    "trimesh.Trimesh",
    pos_tx:  np.ndarray,
    pos_rx:  np.ndarray,
    seqs:    np.ndarray,        # (n, K) int — n candidate facet-sequences, all order K
):
    """
    Vectorized image-chain backtrace for n sequences that ALL have length K.
 
    Returns
    -------
    pts : (n, K+2, 3) float64   — [TX, P1..PK, RX] per candidate (rows where
                                  ok is False contain garbage and must be ignored)
    ok  : (n,) bool             — True iff every reflection point is valid
                                  (0<t<1 on its plane AND inside its triangle),
                                  i.e. exactly the candidates the scalar version
                                  would NOT have returned None for.
    """
    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)
    n, K = seqs.shape
 
    faces = mesh.faces[seqs]                                   # (n, K, 3) vertex ids
    V0    = mesh.vertices[faces[..., 0]].astype(np.float64)    # (n, K, 3) a vertex per facet
    Nrm   = mesh.face_normals[seqs].astype(np.float64)         # (n, K, 3) facet normals
 
    # ── Forward image chain: images[:, i] = TX mirrored through f_1..f_i ──
    images = np.empty((n, K + 1, 3), dtype=np.float64)
    images[:, 0] = pos_tx
    cur = np.broadcast_to(pos_tx, (n, 3)).copy()
    for i in range(K):
        d = np.einsum('ni,ni->n', cur - V0[:, i], Nrm[:, i])   # signed dist to plane i
        cur = cur - 2.0 * d[:, None] * Nrm[:, i]
        images[:, i + 1] = cur
 
    # ── Backward back-trace: reflection point on f_i from image_i -> target ──
    pts = np.empty((n, K + 2, 3), dtype=np.float64)
    pts[:, 0]     = pos_tx
    pts[:, K + 1] = pos_rx
    target = np.broadcast_to(pos_rx, (n, 3)).copy()
    ok = np.ones(n, dtype=bool)
 
    for i in range(K, 0, -1):
        Ai = images[:, i]                                      # (n, 3)
        P, t = _segment_plane_intersection(Ai, target, V0[:, i - 1], Nrm[:, i - 1])
        valid_t = (t > 1e-6) & (t < 1.0 - 1e-6)
        tri = mesh.vertices[mesh.faces[seqs[:, i - 1]]].astype(np.float64)  # (n, 3, 3)
        inside = _point_in_triangle(P, tri)                    # (n,)
        ok &= valid_t & inside
        pts[:, i] = P
        target = P                                             # next target = this P
 
    return pts, ok