"""geometry — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import numpy as np
from constants import NORMAL_OFFSET, SELF_INTERSECT_EPSILON, _OCCLUSION_SLACK


def generate_isotropic_rays(N):
    """Fibonacci Lattice for uniform spherical ray generation."""
    indices = np.arange(0, N, dtype=float) + 0.5
    phi = np.arccos(1 - 2 * indices / N)
    golden_ratio = (1 + 5**0.5) / 2
    theta = 2 * np.pi * indices / golden_ratio
    return np.vstack((np.sin(phi) * np.cos(theta), np.sin(phi) * np.sin(theta), np.cos(phi))).T


def check_sphere_intersection(p_start, p_end, p_rx, r_influence):
    """
    Controlla se il segmento 1D (da p_start a p_end) cattura la sfera del ricevitore.
    Ottimizzato per l'esecuzione raggio per raggio nella coda asincrona.
    """
    v = p_end - p_start
    w = p_rx - p_start
    
    # Calcolo della norma per un singolo vettore 1D (rimosso axis=1 e keepdims)
    v_len = np.linalg.norm(v)
    if v_len == 0: 
        return False, None
        
    v_norm = v / v_len
    projection = np.dot(w, v_norm)
    
    # Vincola la proiezione entro la lunghezza effettiva del segmento di volo
    projection_clamped = np.clip(projection, 0, v_len)
    
    # Punto sul raggio più vicino al centro del ricevitore
    closest_point = p_start + projection_clamped * v_norm
    
    # Verifica la distanza geometrica rispetto al raggio di influenza
    if np.linalg.norm(p_rx - closest_point) <= r_influence:
        return True, closest_point
        
    return False, None


def check_edge_collision(p_start, p_end, diff_edges, tolerance=0.01):
    """
    Verifica se il segmento di un raggio passa vicino ad un bordo diffrangente.
    Ritorna il punto esatto dello spigolo (D), il vettore del bordo e la distanza dal p_start.
    """
    ray_vec = p_end - p_start
    ray_len = np.linalg.norm(ray_vec)
    if ray_len == 0: return None, None, None
    ray_dir = ray_vec / ray_len
    
    for edge in diff_edges:
        u = edge['dir']
        v = ray_dir
        w = p_start - edge['p0']
        
        a = np.dot(u, u)
        b = np.dot(u, v)
        c = np.dot(v, v)
        d = np.dot(u, w)
        e = np.dot(v, w)
        
        denom = a * c - b * b
        if np.abs(denom) < 1e-6: continue 
        
        tc = (a * e - b * d) / denom  
        sc = (b * e - c * d) / denom  
        
        if 0 <= tc <= ray_len and 0 <= sc <= edge['len']:
            intersection_on_edge = edge['p0'] + sc * u
            intersection_on_ray = p_start + tc * v
            
            if np.linalg.norm(intersection_on_edge - intersection_on_ray) <= tolerance:
                return intersection_on_edge, edge['dir'], tc
                
    return None, None, None


def generate_grids(trimesh_mesh, center, n=15, spacing=200, height=8.0, bounded=True):
    """
    Genera una griglia di posizioni 3D risolte sulla superficie della mesh.
    
    Args:
        trimesh_mesh : mesh trimesh della scena
        center       : (x, y) — punto centrale della griglia in coordinate mesh
        n            : numero di punti per lato (totale = n²)
        spacing      : distanza tra i punti [m]
        height       : offset verticale assoluto sopra la superficie [m]
    
    Returns:
        positions : lista di np.ndarray (3,) — posizioni 3D reali già sulla superficie
                    Pronte per essere passate direttamente all'engine e al visualizer.
    """
    cx, cy = center[0], center[1]

    def make_offsets(n, spacing):
        half = (n - 1) / 2
        return np.arange(-half, half + 1) * spacing

    offsets = make_offsets(n, spacing)

    # Genera tutte le coppie (x, y) candidate
    candidates = [
        (cx + dx, cy + dy)
        for dx in offsets
        for dy in offsets
    ]

    # Bounds check + proiezione sulla superficie
    bounds = trimesh_mesh.bounds
    x_min, y_min = bounds[0][0], bounds[0][1]
    x_max, y_max = bounds[1][0], bounds[1][1]

    positions = []
    skipped   = 0

    for x, y in candidates:
        # Fuori bounds → scarta
        if not (x_min <= x <= x_max and y_min <= y <= y_max):
            skipped += 1
            continue

        # Ray casting verticale per trovare la superficie
        ray_origin    = np.array([[x, y, bounds[1][2] + 1.0]])
        ray_direction = np.array([[0.0, 0.0, -1.0]])

        locations, _, _ = trimesh_mesh.ray.intersects_location(
            ray_origins=ray_origin,
            ray_directions=ray_direction,
            multiple_hits=False,
        )

        if len(locations) == 0:
            skipped += 1
            continue

        # Offset verticale assoluto sopra il punto di superficie
        surface_pt = locations[0]
        final_pos  = surface_pt + np.array([0.0, 0.0, height])
        positions.append(final_pos)

    area = (n - 1) * spacing
    print(f"Grid: {len(positions)}/{n*n} punti risolti  "
          f"(n={n}, spacing={spacing}m, height={height}m, "
          f"area={area}x{area}m)")
    if skipped > 0:
        print(f"  ⚠️  {skipped} punti scartati (fuori bounds o no intersection)")

    return positions

def generate_grid_nodes(trimesh_mesh, center, n=15, spacing=200, height=8.0, 
                        mode='terrain', bounded=True):
    """
    Genera una griglia di posizioni 3D per nodi TX o RX.
    
    Args:
        trimesh_mesh : mesh trimesh del terreno (usata per bounds e proiezioni)
        center       : (x, y) — centro della griglia
        n            : numero di punti per lato (totale nodi = n²)
        spacing      : distanza tra i nodi [m]
        height       : altezza/offset dal terreno o quota assoluta del piano [m]
        mode         : 'terrain' (segue il terreno) o 'plane' (griglia piatta a quota z=height)
        bounded      : se True, scarta i punti fuori dai confini XY della mesh
        
    Returns:
        positions : lista di np.ndarray (3,) — coordinate 3D dei nodi risolti
    """
    if center is None:
        bounds = trimesh_mesh.bounds
        x_min, y_min, z_min = bounds[0]
        x_max, y_max, z_max = bounds[1]   
        cx, cy = (x_max+x_min) / 2, (y_max+y_min) / 2
    else:
        cx, cy = center[0], center[1]
        bounds = trimesh_mesh.bounds
        x_min, y_min, z_min = bounds[0]
        x_max, y_max, z_max = bounds[1]
    
    # 1. Generazione geometrica dei punti XY della griglia
    half = (n - 1) / 2
    offsets = np.arange(-half, half + 1) * spacing
    grid_x, grid_y = np.meshgrid(cx + offsets, cy + offsets)
    candidates = np.stack([grid_x.ravel(), grid_y.ravel()], axis=-1)
    
    positions = []
    skipped = 0
    
    # 2. Processamento dei nodi
    for x, y in candidates:
        # Vincolo sui confini XY della mesh (se attivo)
        if bounded:
            if not (x_min <= x <= x_max and y_min <= y <= y_max):
                skipped += 1
                continue
                
        # MODALITÀ PIANO: Quota Z fissa indipendente dalla mesh
        if mode == 'plane':
            positions.append(np.array([x, y, height]))
            
        # MODALITÀ TERRENO: Vincolata alla geometria della mesh tramite ray casting
        elif mode == 'terrain':
            # Raggio dall'alto verso il basso
            ray_origin = np.array([[x, y, z_max + 1.0]])
            ray_direction = np.array([[0.0, 0.0, -1.0]])
            
            locations, _, _ = trimesh_mesh.ray.intersects_location(
                ray_origins=ray_origin,
                ray_directions=ray_direction,
                multiple_hits=False
            )
            
            # Se il raggio manca la mesh (es. punto non vincolato fuori dalla geometria)
            if len(locations) == 0:
                skipped += 1
                continue
                
            # Nodo sulla superficie + offset verticale
            final_pos = locations[0] + np.array([0.0, 0.0, height])
            positions.append(final_pos)
            
    # 3. Log e diagnostica
    area = (n - 1) * spacing
    print(f"Griglia ({mode}): {len(positions)}/{n*n} nodi generati "
          f"(n={n}, spacing={spacing}m, area={area}x{area}m)")
    if skipped > 0:
        print(f"  ⚠️  {skipped} nodi esclusi (fuori bounds o nessuna intersezione)")
        
    return positions

def compute_adaptive_r_influence(
    distanza_percorsa: float,
    num_rays: int,
    lunghezza_d_onda: float,
    min_wavelength_factor: float = 0.5,   # r >= 0.5 * lambda
    max_cap_meters: float = 20.0,         # clamp superiore opzionale
) -> float:
    """
    Calcola il raggio della sfera di ricezione (reception sphere) in modo
    adattivo per il metodo SBR (Shooting and Bouncing Rays).

    Formula:
        r_adaptive = d * sqrt(4 / N_rays)

    Derivazione: ogni raggio copre un'area solida 4*pi/N steradianti;
    a distanza d quella calotta vale A = (4*pi*d^2) / N.
    Il raggio della sfera equivalente (A = pi*r^2) è r = d*sqrt(4/N).

    Args:
        distanza_percorsa:     distanza totale percorsa dal raggio [m]
        num_rays:              numero totale di raggi lanciati
        lunghezza_d_onda:      lambda [m]
        min_wavelength_factor: fattore minimo rispetto a lambda (default 0.5)
        max_cap_meters:        clamp superiore in metri (default 20 m)

    Returns:
        r [m]
    """
    r_adaptive = distanza_percorsa * np.sqrt(4.0 / num_rays)
    r_min      = min_wavelength_factor * lunghezza_d_onda
    return float(np.clip(r_adaptive, r_min, max_cap_meters))


def vec_normalize(v: np.ndarray) -> np.ndarray:
    """Row-wise L2 normalization of (N,3) array.  Safe against zero rows."""
    norms = np.linalg.norm(v, axis=1, keepdims=True)
    norms = np.where(norms < 1e-12, 1.0, norms)
    return v / norms


def vec_reflect(
    dirs:    np.ndarray,   # (M, 3)
    normals: np.ndarray,   # (M, 3)
) -> np.ndarray:           # (M, 3) reflected directions, unit
    """d - 2*(d·n)*n — vectorized for M rays."""
    dot  = np.einsum('ij,ij->i', dirs, normals)           # (M,)
    refl = dirs - 2.0 * dot[:, None] * normals            # (M,3)
    return vec_normalize(refl)


def vec_sphere_intersect(
    seg_a:  np.ndarray,   # (M, 3)  segment start
    seg_b:  np.ndarray,   # (M, 3)  segment end
    center: np.ndarray,   # (3,)    sphere centre
    radius: float | np.ndarray,   # scalar or (M,) array
) -> tuple[np.ndarray, np.ndarray]:
    """
    Vectorized ray-sphere intersection for finite segments [A, B].

    Solves  |A + t*(B-A) - C|² = r²  for t ∈ [0,1].
    Returns:
        hit_mask  (M,) bool
        hit_pts   (M,3) intersection points (undefined where hit_mask=False)
    """
    d    = seg_b - seg_a                                     # (M,3)
    oc   = seg_a - center                                    # (M,3)
    a    = np.einsum('ij,ij->i', d, d)                      # (M,)
    b    = 2.0 * np.einsum('ij,ij->i', oc, d)               # (M,)
    c    = np.einsum('ij,ij->i', oc, oc) - np.asarray(radius) ** 2
    disc = b * b - 4.0 * a * c                              # (M,)

    hit  = disc >= 0.0
    safe_disc = np.where(hit, disc, 0.0)
    t    = np.where(hit,
                    np.clip((-b - np.sqrt(safe_disc)) / (2.0 * np.maximum(a, 1e-30)),
                            0.0, 1.0),
                    0.0)
    hit  = hit & (t >= 0.0) & (t <= 1.0)
    pts  = seg_a + t[:, None] * d
    return hit, pts


def vec_adaptive_r(
    dist_total: np.ndarray,   # (M,) accumulated + current-segment distance
    num_rays:   int,
    wavelength: float,
    min_factor: float,
    max_cap:    float,
) -> np.ndarray:              # (M,)
    """Adaptive reception sphere radius — vectorized."""
    r = dist_total * np.sqrt(4.0 / num_rays)
    return np.clip(r, min_factor * wavelength, max_cap)


def batch_intersect(mesh, origins, directions, max_dist):
    """
    Fire ALL N rays against the mesh in a SINGLE trimesh call, numerically
    robust to far-away origins.
 
    Returns (per-ray arrays, length N), identical contract to the original:
        hit_mask  (N,)   bool       — True if ray hit something
        hit_pts   (N,3)  float32    — closest hit position (or origin+dir*max_dist)
        hit_faces (N,)   int32      — face index (-1 if miss)
        hit_dists (N,)   float32    — distance to hit (max_dist if miss),
                                      measured from the TRUE origin
    """
    origins64 = np.asarray(origins, dtype=np.float64)
    dirs64    = np.asarray(directions, dtype=np.float64)
    norms     = np.linalg.norm(dirs64, axis=1, keepdims=True)
    dirs64    = dirs64 / np.where(norms < 1e-12, 1.0, norms)
    N         = len(origins64)
 
    # ── Advance origins to the mesh bounding sphere (float64) ──────────────
    # Sphere: centre = mesh centroid, radius = max vertex distance (+ tiny pad).
    c = np.asarray(mesh.centroid, dtype=np.float64)
    R = float(np.linalg.norm(np.asarray(mesh.vertices, np.float64) - c,
                             axis=1).max()) * 1.001 + 1e-8
 
    oc   = origins64 - c
    b    = np.einsum('ij,ij->i', oc, dirs64)            # oc · d
    cc   = np.einsum('ij,ij->i', oc, oc) - R * R
    disc = b * b - cc
    t_enter = -b - np.sqrt(np.maximum(disc, 0.0))       # near root
    # advance only if the ray actually enters the sphere ahead of the origin
    t0 = np.where((disc >= 0.0) & (t_enter > 0.0), t_enter, 0.0)
    adv = origins64 + t0[:, None] * dirs64              # near the mesh: small magnitude
 
    # ── Single vectorized intersection from the advanced origins ───────────
    pts_all, ray_idx, face_idx = mesh.ray.intersects_location(
        ray_origins=adv.astype(np.float32),
        ray_directions=dirs64.astype(np.float32),
        multiple_hits=False,
    )
 
    # Defaults: all rays miss. Fallback point/dist measured from the TRUE origin.
    hit_mask  = np.zeros(N, dtype=bool)
    hit_pts   = origins64 + dirs64 * max_dist
    hit_faces = np.full(N, -1, dtype=np.int32)
    hit_dists = np.full(N, float(max_dist), dtype=np.float64)
 
    if len(pts_all) > 0:
        # distance from the ADVANCED origin (small numbers -> precise)
        dists_adv = np.linalg.norm(pts_all - adv[ray_idx], axis=1)
        valid = dists_adv > SELF_INTERSECT_EPSILON
        if np.any(valid):
            vp = pts_all[valid]
            vr = ray_idx[valid]
            vf = face_idx[valid]
            vd = dists_adv[valid]
 
            order = np.argsort(vd)                      # closest first
            vp, vr, vf, vd = vp[order], vr[order], vf[order], vd[order]
 
            _, first = np.unique(vr, return_index=True) # first = closest per ray
            r0 = vr[first]
            hit_mask[r0]  = True
            hit_pts[r0]   = vp[first]
            hit_faces[r0] = vf[first]
            # total distance from the TRUE origin = advance + remaining
            hit_dists[r0] = vd[first] + t0[r0]
 
    return hit_mask, hit_pts.astype(np.float32), hit_faces, hit_dists.astype(np.float32)


def check_los(mesh, pos_tx, pos_rx):
    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)

    los_vec = pos_rx - pos_tx
    los_dist = float(np.linalg.norm(los_vec))
    los_dir = los_vec / los_dist

    origins = pos_tx.reshape(1, 3)
    directions = los_dir.reshape(1, 3)

    hit_mask, hit_pts, _, hit_dists = batch_intersect(
        mesh, origins, directions, los_dist * 2.0
    )

    if hit_mask[0]:
        t = float(hit_dists[0])
        if SELF_INTERSECT_EPSILON < t < (los_dist - SELF_INTERSECT_EPSILON):
            return True, hit_pts[0].astype(np.float64)

    return False, None


def fibonacci_sphere(n: int) -> np.ndarray:
    """Returns (N, 3) unit directions, uniform on the sphere."""
    idx   = np.arange(0, n, dtype=np.float64) + 0.5
    phi   = np.arccos(1.0 - 2.0 * idx / n)
    theta = 2.0 * np.pi * idx / ((1.0 + 5.0 ** 0.5) / 2.0)
    dirs  = np.column_stack((
        np.sin(phi) * np.cos(theta),
        np.sin(phi) * np.sin(theta),
        np.cos(phi),
    ))
    return dirs.astype(np.float32)


def terrain_horizon_profile(pos_tx, mesh, n_az_bins=180):
    """
    Skyline as seen from the TX: for each azimuth bin, the highest elevation
    angle (deg) of any terrain vertex. Vertices below the TX give negative
    elevations (e.g. a basin floor); a nearby peak gives a positive one.
    Empty bins are filled by circular interpolation so a sparsely-sampled
    azimuth never accidentally kills all its rays.
    """
    v = np.asarray(mesh.vertices, float) - np.asarray(pos_tx, float)
    horiz = np.hypot(v[:, 0], v[:, 1])
    elev = np.degrees(np.arctan2(v[:, 2], np.maximum(horiz, 1e-9)))
    az = np.degrees(np.arctan2(v[:, 1], v[:, 0])) % 360.0
    bins = np.minimum((az / (360.0 / n_az_bins)).astype(int), n_az_bins - 1)
 
    horizon = np.full(n_az_bins, -np.inf)
    np.maximum.at(horizon, bins, elev)
 
    filled = np.isfinite(horizon)
    if not filled.all():
        idx = np.arange(n_az_bins)
        if filled.any():
            horizon = np.interp(idx, idx[filled], horizon[filled], period=n_az_bins)
        else:
            horizon[:] = -90.0
    return horizon


def generate_launch_directions(
    pos_tx,
    num_rays_full_sphere,
    mesh=None,
    mode="terrain_horizon",          # "full_sphere" | "lower_flat" | "terrain_horizon"
    horizon_margin_deg=3.0,
    n_az_bins=180,
    precomputed_horizon=None, 
):
    """
    SBR launch directions with optional ground-only restriction.
 
    Always lays down `num_rays_full_sphere` near-uniform directions over the
    whole sphere, then DISCARDS the ones aimed at empty sky. Kept rays keep
    full-sphere spacing, so the reception-sphere radius must use n_eff
    (= num_rays_full_sphere), NOT len(dirs).
 
    Returns
    -------
    dirs        : (M, 3) unit launch directions, M <= num_rays_full_sphere
    n_eff       : int   — feed THIS to the adaptive-r law, not len(dirs)
    solid_angle : float — steradians actually covered (diagnostic)
    """
    dirs = fibonacci_sphere(num_rays_full_sphere)
    n_eff = int(num_rays_full_sphere)
 
    if mode == "full_sphere":
        keep = np.ones(len(dirs), bool)
 
    elif mode == "lower_flat":
        keep = dirs[:, 2] <= np.sin(np.radians(horizon_margin_deg))
 
    elif mode == "terrain_horizon":
        if precomputed_horizon is not None:
            horizon   = precomputed_horizon
            n_az_bins = len(horizon)               # keep binning consistent
        elif mesh is not None:
            horizon = terrain_horizon_profile(pos_tx, mesh, n_az_bins)
        else:
            raise ValueError("terrain_horizon needs a mesh or precomputed_horizon")
        elev = np.degrees(np.arcsin(np.clip(dirs[:, 2], -1.0, 1.0)))
        az   = np.degrees(np.arctan2(dirs[:, 1], dirs[:, 0])) % 360.0
        bins = np.minimum((az / (360.0 / n_az_bins)).astype(int), n_az_bins - 1)
        keep = elev <= (horizon[bins] + horizon_margin_deg)
 
    else:
        raise ValueError(f"unknown mode {mode!r}")
 
    dirs = dirs[keep]
    solid_angle = 4.0 * np.pi * len(dirs) / n_eff
    return dirs, n_eff, solid_angle

def generate_surface_directions(
    pos_tx,
    num_rays,
    mesh,
    seed=42,
    include_centroids=True,
    use_projected_area=True,
    use_abs_cos=True,
    aim_point=None,
    return_info=False,
):
    """
    Surface-targeted launch mode for HYBRID candidate discovery.

    Returns either:
        dirs, count, omega

    or, if return_info=True:
        dirs, count, omega, launch_info
    """
    rng = np.random.default_rng(seed)

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    num_rays = int(num_rays)

    if num_rays <= 0:
        raise ValueError("num_rays must be > 0.")

    V = np.asarray(mesh.vertices, dtype=np.float64)
    F = np.asarray(mesh.faces, dtype=np.int64)

    tri = V[F]
    v0 = tri[:, 0]
    v1 = tri[:, 1]
    v2 = tri[:, 2]

    e1 = v1 - v0
    e2 = v2 - v0

    cross = np.cross(e1, e2)
    double_area = np.linalg.norm(cross, axis=1)
    areas = 0.5 * double_area

    valid = areas > 1e-12
    centers = (v0 + v1 + v2) / 3.0

    # ------------------------------------------------------------------
    # Pyramid-style front-of-view failsafe, inline
    # ------------------------------------------------------------------
    if aim_point is None:
        aim_ref = np.asarray(mesh.centroid, dtype=np.float64)
    else:
        aim_ref = np.asarray(aim_point, dtype=np.float64)

    aim = aim_ref - pos_tx
    aim_norm = np.linalg.norm(aim)

    if aim_norm < 1e-12:
        raise ValueError("Invalid aim direction: aim_point coincides with pos_tx.")

    aim = aim / aim_norm

    d_center = centers - pos_tx[None, :]
    za = d_center @ aim

    front = za > 1e-6
    valid = valid & front
    # ------------------------------------------------------------------

    if not np.any(valid):
        raise ValueError(
            "generate_surface_directions(): no valid triangles after pyramid-style front test."
        )

    normals = np.zeros_like(cross)
    ok_area = areas > 1e-12
    normals[ok_area] = cross[ok_area] / double_area[ok_area, None]

    to_tx = pos_tx[None, :] - centers
    dist = np.linalg.norm(to_tx, axis=1)
    s_hat = to_tx / np.maximum(dist[:, None], 1e-30)

    cos_term = np.einsum("ij,ij->i", normals, s_hat)

    if use_abs_cos:
        cos_term = np.abs(cos_term)
    else:
        cos_term = np.maximum(0.0, cos_term)

    if use_projected_area:
        weights = areas * cos_term / np.maximum(dist**2, 1e-30)
    else:
        weights = areas.copy()

    valid = valid & np.isfinite(weights) & (weights > 0.0)

    if not np.any(valid):
        raise ValueError(
            "generate_surface_directions(): no valid triangles after weighting. "
            "Try use_abs_cos=True or check mesh normals."
        )

    weights = np.where(valid, weights, 0.0)
    weights = weights / weights.sum()

    target_chunks = []
    face_chunks = []

    valid_faces = np.where(valid)[0]

    # Guarantee one centroid ray per valid triangle if budget allows.
    if include_centroids and num_rays >= len(valid_faces):
        target_chunks.append(centers[valid_faces])
        face_chunks.append(valid_faces.astype(np.int64))
        n_remaining = num_rays - len(valid_faces)
    else:
        n_remaining = num_rays

    if n_remaining > 0:
        face_ids = rng.choice(len(F), size=n_remaining, replace=True, p=weights)

        u = rng.random(n_remaining)
        v = rng.random(n_remaining)

        flip = (u + v) > 1.0
        u[flip] = 1.0 - u[flip]
        v[flip] = 1.0 - v[flip]

        pts = (
            v0[face_ids]
            + u[:, None] * e1[face_ids]
            + v[:, None] * e2[face_ids]
        )

        target_chunks.append(pts)
        face_chunks.append(face_ids.astype(np.int64))

    target_pts = np.vstack(target_chunks).astype(np.float64)
    target_faces = np.concatenate(face_chunks).astype(np.int64)

    dirs = target_pts - pos_tx[None, :]
    norms = np.linalg.norm(dirs, axis=1, keepdims=True)
    dirs = dirs / np.maximum(norms, 1e-30)

    dirs = dirs.astype(np.float64)

    if return_info:
        launch_info = {
            "target_faces": target_faces,
            "valid_faces": valid_faces,
            "num_mesh_faces": len(F),
        }
        return dirs, len(dirs), np.nan, launch_info

    return dirs, len(dirs), np.nan

def generate_surface_equal_directions(
    pos_tx,
    num_rays,
    mesh,
    seed=42,
    use_centroid_first=True,
    visible_only=False,
    use_abs_cos=True,
    aim_point=None,
    return_info=False,
):
    """
    Equal-triangle surface launch mode for HYBRID candidate discovery.

    Returns either:
        dirs, count, omega

    or, if return_info=True:
        dirs, count, omega, launch_info
    """
    rng = np.random.default_rng(seed)

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    num_rays = int(num_rays)

    if num_rays <= 0:
        raise ValueError("num_rays must be > 0.")

    V = np.asarray(mesh.vertices, dtype=np.float64)
    F = np.asarray(mesh.faces, dtype=np.int64)

    tri = V[F]
    v0 = tri[:, 0]
    v1 = tri[:, 1]
    v2 = tri[:, 2]

    e1 = v1 - v0
    e2 = v2 - v0

    cross = np.cross(e1, e2)
    double_area = np.linalg.norm(cross, axis=1)
    areas = 0.5 * double_area

    valid = areas > 1e-12
    centers = (v0 + v1 + v2) / 3.0

    # ------------------------------------------------------------------
    # Pyramid-style front-of-view failsafe, inline
    # ------------------------------------------------------------------
    if aim_point is None:
        aim_ref = np.asarray(mesh.centroid, dtype=np.float64)
    else:
        aim_ref = np.asarray(aim_point, dtype=np.float64)

    aim = aim_ref - pos_tx
    aim_norm = np.linalg.norm(aim)

    if aim_norm < 1e-12:
        raise ValueError("Invalid aim direction: aim_point coincides with pos_tx.")

    aim = aim / aim_norm

    d_center = centers - pos_tx[None, :]
    za = d_center @ aim

    front = za > 1e-6
    valid = valid & front
    # ------------------------------------------------------------------

    if visible_only:
        normals = np.zeros_like(cross)
        ok_area = areas > 1e-12
        normals[ok_area] = cross[ok_area] / double_area[ok_area, None]

        to_tx = pos_tx[None, :] - centers
        dist = np.linalg.norm(to_tx, axis=1)
        s_hat = to_tx / np.maximum(dist[:, None], 1e-30)

        cos_term = np.einsum("ij,ij->i", normals, s_hat)

        if use_abs_cos:
            cos_term = np.abs(cos_term)
        else:
            cos_term = np.maximum(0.0, cos_term)

        valid = valid & (cos_term > 1e-9)

    face_pool = np.where(valid)[0]

    if len(face_pool) == 0:
        raise ValueError(
            "generate_surface_equal_directions(): no valid triangles after pyramid-style front test."
        )

    if num_rays <= len(face_pool):
        selected_faces = rng.choice(face_pool, size=num_rays, replace=False)
        counts = np.ones(num_rays, dtype=np.int64)
    else:
        base = num_rays // len(face_pool)
        rem = num_rays % len(face_pool)

        selected_faces = face_pool
        counts = np.full(len(face_pool), base, dtype=np.int64)

        if rem > 0:
            extra_idx = rng.choice(len(face_pool), size=rem, replace=False)
            counts[extra_idx] += 1

    target_chunks = []
    face_chunks = []

    for fid, n in zip(selected_faces, counts):
        fid = int(fid)
        n = int(n)

        if n <= 0:
            continue

        if use_centroid_first:
            target_chunks.append(centers[fid][None, :])
            face_chunks.append(np.array([fid], dtype=np.int64))
            n_random = n - 1
        else:
            n_random = n

        if n_random > 0:
            u = rng.random(n_random)
            v = rng.random(n_random)

            flip = (u + v) > 1.0
            u[flip] = 1.0 - u[flip]
            v[flip] = 1.0 - v[flip]

            pts = (
                v0[fid]
                + u[:, None] * e1[fid]
                + v[:, None] * e2[fid]
            )

            target_chunks.append(pts)
            face_chunks.append(np.full(n_random, fid, dtype=np.int64))

    target_pts = np.vstack(target_chunks).astype(np.float64)
    target_faces = np.concatenate(face_chunks).astype(np.int64)

    dirs = target_pts - pos_tx[None, :]
    norms = np.linalg.norm(dirs, axis=1, keepdims=True)
    dirs = dirs / np.maximum(norms, 1e-30)

    dirs = dirs.astype(np.float64)

    if return_info:
        launch_info = {
            "target_faces": target_faces,
            "valid_faces": face_pool,
            "num_mesh_faces": len(F),
        }
        return dirs, len(dirs), np.nan, launch_info

    return dirs, len(dirs), np.nan

def generate_pyramid_directions(
    pos_tx,
    num_rays,
    mesh,
    aim_point=None,        # default = mesh.centroid
    margin_frac=0.00,      # pad the window so the silhouette rim is inside it
):
    """
    Rectangular-pyramid SBR launch. Returns a grid of ~num_rays directions whose
    angular footprint from TX bounds the ENTIRE mesh silhouette. Near-parallel
    for a distant mesh, by design.

    Returns (dirs, count, omega):
      dirs  : (count, 3) float32 unit directions
      count : actual number generated (nx*ny, ~num_rays)
      omega : pyramid solid angle [sr], diagnostic only
    """
    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    V      = np.asarray(mesh.vertices, dtype=np.float64)

    # ── aim + orthonormal frame (right, up, aim) ───────────────────────
    aim = (mesh.centroid if aim_point is None else np.asarray(aim_point, float)) - pos_tx
    aim /= np.linalg.norm(aim)
    world_up = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(aim, world_up)) > 0.999:          # looking straight down/up
        world_up = np.array([0.0, 1.0, 0.0])
    right = np.cross(world_up, aim); right /= np.linalg.norm(right)
    up    = np.cross(aim, right)

    # ── project vertices onto the unit image plane along aim ───────────
    d  = V - pos_tx
    za = d @ aim
    front = za > 1e-6
    d, za = d[front], za[front]
    x = (d @ right) / za
    y = (d @ up)    / za

    x_min, x_max = x.min(), x.max()
    y_min, y_max = y.min(), y.max()
    px = (x_max - x_min) * margin_frac + 1e-9
    py = (y_max - y_min) * margin_frac + 1e-9
    x_min, x_max = x_min - px, x_max + px
    y_min, y_max = y_min - py, y_max + py

    # ── grid sized to num_rays, proportioned to the window aspect ──────
    aspect = (x_max - x_min) / (y_max - y_min)
    ny = max(1, int(round(np.sqrt(num_rays / aspect))))
    nx = max(1, int(round(num_rays / ny)))
    XX, YY = np.meshgrid(np.linspace(x_min, x_max, nx),
                         np.linspace(y_min, y_max, ny))
    XX, YY = XX.ravel(), YY.ravel()

    dirs = aim[None, :] + XX[:, None] * right[None, :] + YY[:, None] * up[None, :]
    dirs /= np.linalg.norm(dirs, axis=1, keepdims=True)

    omega = float((np.arctan(x_max) - np.arctan(x_min)) *
                  (np.arctan(y_max) - np.arctan(y_min)))
    return dirs.astype(np.float64), len(dirs), omega


def _mirror_points_across_plane(
    pts: np.ndarray,   # (3,) or (P, 3)
    V0:  np.ndarray,   # (F, 3) a point on each facet plane
    N:   np.ndarray,   # (F, 3) unit facet normals
) -> np.ndarray:
    """Mirror point(s) across each of F planes. Returns (F, 3) when `pts` is a
    single point, else (P, F, 3)."""
    pts = np.asarray(pts, dtype=np.float64)
    if pts.ndim == 1:
        d = np.einsum('fi,fi->f', pts[None, :] - V0, N)          # (F,)
        return pts[None, :] - 2.0 * d[:, None] * N               # (F, 3)
    d = np.einsum('pfi,fi->pf', pts[:, None, :] - V0[None], N)   # (P, F)
    return pts[:, None, :] - 2.0 * d[:, :, None] * N[None]


def _point_in_triangle(P: np.ndarray, tri: np.ndarray) -> np.ndarray:
    """Barycentric inside-test. P (M,3) already coplanar with tri (M,3,3)."""
    a = tri[:, 0, :]
    v0 = tri[:, 2, :] - a
    v1 = tri[:, 1, :] - a
    v2 = P - a
    d00 = np.einsum('mi,mi->m', v0, v0)
    d01 = np.einsum('mi,mi->m', v0, v1)
    d11 = np.einsum('mi,mi->m', v1, v1)
    d20 = np.einsum('mi,mi->m', v2, v0)
    d21 = np.einsum('mi,mi->m', v2, v1)
    denom = d00 * d11 - d01 * d01
    denom = np.where(np.abs(denom) < 1e-30, 1e-30, denom)
    u = (d11 * d20 - d01 * d21) / denom
    v = (d00 * d21 - d01 * d20) / denom
    eps = 1e-7
    return (u >= -eps) & (v >= -eps) & (u + v <= 1.0 + eps)


def _segment_plane_intersection(
    A: np.ndarray,    # (M, 3)  image point
    B: np.ndarray,    # (M, 3)  target point (RX or next reflection point)
    V0: np.ndarray,   # (M, 3)  point on plane
    N: np.ndarray,    # (M, 3)  unit normal
) -> Tuple[np.ndarray, np.ndarray]:
    """Where does segment A->B cross each plane? Returns (P (M,3), t (M,)).
    Valid specular point requires 0 < t < 1 (A and B on opposite sides of the
    plane — which is exactly the mirror geometry)."""
    AB = B - A
    denom = np.einsum('mi,mi->m', AB, N)
    denom = np.where(np.abs(denom) < 1e-30, 1e-30, denom)
    t = np.einsum('mi,mi->m', V0 - A, N) / denom
    P = A + t[:, None] * AB
    return P, t


def _segments_clear(
    mesh: trimesh.Trimesh,
    starts: np.ndarray,    # (M, 3)
    ends:   np.ndarray,    # (M, 3)
    nudge_normals: Optional[np.ndarray] = None,  # (M,3) push start off surface
) -> np.ndarray:
    """Vectorized line-of-sight test for M segments. Returns (M,) bool, True if
    nothing blocks the segment before its endpoint."""
    M = len(starts)
    if M == 0:
        return np.zeros(0, dtype=bool)

    o = starts.astype(np.float64).copy()
    if nudge_normals is not None:
        o = o + nudge_normals * (NORMAL_OFFSET * 1000.0)

    seg = ends.astype(np.float64) - o
    seg_len = np.linalg.norm(seg, axis=1)
    safe = np.where(seg_len > 1e-12, seg_len, 1.0)
    dirs = seg / safe[:, None]

    march = SELF_INTERSECT_EPSILON * 2.0          # ~0.10 m
    o = o + dirs * march                          # step off the origin facet
    seg_len = seg_len - march                     # endpoint stays put

    safe = np.where(seg_len > 1e-12, seg_len, 1.0)
    dirs = (seg / safe[:, None]).astype(np.float32)

    big = float(seg_len.max()) + 1.0 if M else 1.0
    hit_mask, _, _, hit_dists = batch_intersect(
        mesh, o.astype(np.float32), dirs, big
    )
    # Blocked if a hit occurs strictly before the endpoint.
    blocked = hit_mask & (hit_dists < (seg_len.astype(np.float32) - _OCCLUSION_SLACK))
    return ~blocked
