"""legacy — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
import cProfile
import io
import numpy as np
import pstats
from constants import MAX_PATH_DIST, NORMAL_OFFSET, S_MIN_MAGNITUDE
from diffraction import extract_diffraction_edges, generate_keller_cone_rays, inject_keller_children
from em_core import vec_fresnel_scalar
from geometry import batch_intersect, check_edge_collision, check_los, check_sphere_intersection, compute_adaptive_r_influence, fibonacci_sphere, vec_adaptive_r, vec_reflect
from timing import SectionTimer


def run_complete_multipath_engine(
    mesh,
    pos_tx,
    pos_rx,
    r_influence,                        # float  → valore fisso
                                        # None   → modalità adattiva
    num_rays=5000,
    max_bounces=3,
    epsilon_luna=3.0 - 0.01j,
    frequenza=2.4e9,
    enable_diffractions=True,
    # --- Parametri esclusivi della modalità adattiva ---
    adaptive_min_wavelength_factor=0.5, # r >= factor * lambda
    adaptive_max_cap_meters=20.0,       # clamp superiore [m]
):
    """
    Motore di Ray Tracing (SBR) con approccio scalare (No 3D Polarization).

    r_influence:
        - float  → sfera di ricezione fissa per tutti i raggi
        - None   → sfera adattiva: r = d * sqrt(4/N), con clamp su lambda
                   (vedi compute_adaptive_r_influence)
    """

    # Determina la modalità del raggio di influenza
    adaptive_mode = r_influence is None
    r_influence_config = "adaptive" if adaptive_mode else float(r_influence)

    results = {
        "los_segment":          None,
        "los_blocked":          False,
        "nlos_paths":           [],
        "keller_events":        [],
        "primary_rays_captured": 0,
        "r_influence_mode":     r_influence_config,   # "adaptive" | float
    }

    c = 299792458
    lunghezza_d_onda = c / frequenza
    k = 2 * np.pi / lunghezza_d_onda

    # =============================================================================
    # 1. CONTROLLO PREVENTIVO LINE-OF-SIGHT (CALCOLO DETERMINISTICO)
    # =============================================================================
    los_vector   = pos_rx - pos_tx
    los_distance = np.linalg.norm(los_vector)
    los_ray_dir  = los_vector / los_distance

    locs, _, index_tri = mesh.ray.intersects_location([pos_tx], [los_ray_dir])

    valid_los_hits  = []
    valid_los_faces = []
    for l_idx, pt in enumerate(locs):
        dist_from_tx = np.linalg.norm(pt - pos_tx)
        if 0.05 < dist_from_tx < (los_distance - 0.05):
            valid_los_hits.append(pt)
            valid_los_faces.append(index_tri[l_idx])

    if len(valid_los_hits) > 0:
        results["los_blocked"] = True
        closest_idx = np.argmin([np.linalg.norm(pt - pos_tx) for pt in valid_los_hits])
        results["los_segment"] = np.vstack((pos_tx, valid_los_hits[closest_idx]))
        print(f"\n[LOS INFO] TX and RX are NOT in Line-of-Sight! "
              f"Blocked by Face ID: {valid_los_faces[closest_idx]}")
    else:
        results["los_blocked"] = False
        results["los_segment"] = np.vstack((pos_tx, pos_rx))
        print(f"\n[LOS INFO] Direct Line-of-Sight (LoS) is CLEAR. Appending analytic LoS path.")
        
        # --- CALCOLO ANALITICO DEL PERCORSO LoS PERFETTO ---
        ampiezza_fsl = lunghezza_d_onda / (4 * np.pi * los_distance)
        fsl_db = -20.0 * np.log10(ampiezza_fsl)
        fase_geometrica = -k * los_distance
        fase_rad_norm = fase_geometrica % (2 * np.pi)
        campo_complesso_los = ampiezza_fsl * np.exp(1j * fase_geometrica)
        
        aoa_azimuth_deg = np.degrees(np.arctan2(los_ray_dir[1], los_ray_dir[0]))
        aoa_elevation_deg = np.degrees(np.arcsin(np.clip(los_ray_dir[2], -1.0, 1.0)))

        results["nlos_paths"].append({
            "bounces":               0,
            "has_diffracted":        False,
            "faces_hit":             [],
            "points":                np.array([pos_tx, pos_rx]), # Coordinate ESATTE
            "distanza_totale":       los_distance,
            "campo_complesso":       campo_complesso_los,
            "fsl_db":                fsl_db,
            "reflection_loss_db":    0.0,
            "path_loss_totale_db":   fsl_db,
            "sfasamento_totale_rad": fase_rad_norm,
            "sfasamento_totale_deg": np.degrees(fase_rad_norm),
            "ritardo_assoluto_ns":   (los_distance / c) * 1e9,
            "aoa_direction":         los_ray_dir,
            "aoa_azimuth_deg":       aoa_azimuth_deg,
            "aoa_elevation_deg":     aoa_elevation_deg,
            "dettaglio_rimbalzi":    [],
            "r_influence_used":      None,   # LoS è deterministico, nessuna sfera usata
        })

    # =============================================================================
    # 2. PRE-PROCESSING SPIGOLI E INIZIALIZZAZIONE CODA (SBR)
    # =============================================================================
    if enable_diffractions:
        # Assumendo che la funzione extract_diffraction_edges esista nel tuo ambiente
        diff_edges = extract_diffraction_edges(mesh)
    else:
        diff_edges = []   

    indices   = np.arange(0, num_rays, dtype=float) + 0.5
    phi       = np.arccos(1 - 2 * indices / num_rays)
    theta     = 2 * np.pi * indices / ((1 + 5**0.5) / 2)
    ray_dirs  = np.vstack((
        np.sin(phi) * np.cos(theta),
        np.sin(phi) * np.sin(theta),
        np.cos(phi),
    )).T

    max_distance = 500.0
    total_edges_triggered = 0

    ray_queue = []
    for r_id, d in enumerate(ray_dirs):
        S_0 = 1.0 + 0.0j
        ray_queue.append((
            r_id, np.array(pos_tx), d,
            [np.array(pos_tx)], 0, False,
            [], [], S_0, [],
        ))

    # Raggio deterministico per test analitico
    # raggio_perfetto_dir = np.array([0.0, 0.0, -1.0])
    # ray_queue.insert(0, (
    #     99, np.array(pos_tx), raggio_perfetto_dir,
    #     [np.array(pos_tx)], 0, False,
    #     [], [], 1.0 + 0.0j, [],
    # ))

    print(f"\n--- Launching Combined Ray-Tracing Engine | "
          f"({num_rays} Rays) ---")

    # =============================================================================
    # 3. LOOP PRINCIPALE SBR
    # =============================================================================
    while len(ray_queue) > 0:
        (ray_id, current_origin, current_dir, path_pts, bounce_count,
         has_diffracted, face_ids, impact_pts,
         S_accumulata, cronologia_rimbalzi) = ray_queue.pop(0)

        if bounce_count > max_bounces:
            continue

        points, _, cells = mesh.ray.intersects_location(
            [current_origin], [current_dir]
        )

        terrain_hit = False
        next_vertex = current_origin + current_dir * max_distance
        cell_id     = -1
        hit_dist    = max_distance

        if len(points) > 0:
            distances  = np.linalg.norm(points - current_origin, axis=1)
            valid_mask = distances > 0.05
            if np.any(valid_mask):
                closest_idx = np.argmin(distances[valid_mask])
                next_vertex = points[valid_mask][closest_idx]
                cell_id     = cells[valid_mask][closest_idx]
                hit_dist    = distances[valid_mask][closest_idx]
                terrain_hit = True

        # --- Controllo priorità: spigolo vs faccia piana ---
        if enable_diffractions:
            edge_pt, edge_dir, edge_ray_dist = check_edge_collision(
                current_origin, next_vertex, diff_edges
            )
        else:
            edge_pt, edge_dir, edge_ray_dist = None, None, float('inf')

        if edge_pt is not None and edge_ray_dist < hit_dist:
            if not has_diffracted:
                total_edges_triggered += 1
                child_dirs = generate_keller_cone_rays(
                    edge_pt, current_dir, edge_dir, num_diff_rays=6
                )

                results["keller_events"].append({
                    "trigger_ray_id": ray_id,
                    "bounce_occurred": bounce_count,
                    "hit_point":       edge_pt.copy(),
                    "edge_dir":        edge_dir.copy(),
                    "incoming_dir":    current_dir.copy(),
                    "child_dirs":      [cd.copy() for cd in child_dirs],
                    "path_to_edge":    list(path_pts) + [edge_pt],
                })

                updated_pts   = list(impact_pts) + [np.round(edge_pt, 2)]
                updated_faces = list(face_ids)   + ["Edge"]

                for cd in child_dirs:
                    new_path   = list(path_pts) + [edge_pt]
                    new_origin = edge_pt + cd * 1e-6
                    ray_queue.append((
                        ray_id, new_origin, cd, new_path,
                        bounce_count + 1, True,
                        updated_faces, updated_pts,
                        S_accumulata, cronologia_rimbalzi,
                    ))
            continue

        # --- Verifica intercettazione RX ---
        
        if adaptive_mode:
            # dist_percorsa = segmenti già completati (path_pts)
            dist_percorsa = sum(
                np.linalg.norm(np.array(path_pts[i+1]) - np.array(path_pts[i]))
                for i in range(len(path_pts) - 1)
            )
            # segmento corrente: da current_origin fino al punto di check RX
            # usiamo hit_dist (distanza fino alla mesh) come proxy del segmento corrente
            dist_segmento_corrente = np.linalg.norm(pos_rx - current_origin)
            dist_totale_stimata = dist_percorsa + dist_segmento_corrente

            r_check = compute_adaptive_r_influence(
                dist_totale_stimata,
                num_rays,
                lunghezza_d_onda,
                adaptive_min_wavelength_factor,
                adaptive_max_cap_meters,
            )
        else:
            r_check = r_influence   # valore fisso passato dall'utente

        rx_hit, rx_pt = check_sphere_intersection(
            current_origin, next_vertex, pos_rx, r_check   # ← usa r_check
        )

        if rx_hit:
            if bounce_count == 0:
                results["primary_rays_captured"] += 1
                rx_hit = False
                continue

            final_path      = list(path_pts) + [rx_pt]
            path_array      = np.array(final_path)
            segmenti        = np.diff(path_array, axis=0)
            distanza_totale = np.sum(np.linalg.norm(segmenti, axis=1))

            # 1. Free Space Loss (Friis)
            ampiezza_spazio_libero = lunghezza_d_onda / (4 * np.pi * distanza_totale)
            fsl_db = -20.0 * np.log10(ampiezza_spazio_libero)

            # 2. Reflection Loss (dal coefficiente scalare accumulato)
            mag_S = np.abs(S_accumulata)
            if mag_S > 1e-12:
                reflection_loss_db = -20.0 * np.log10(mag_S)
            else:
                reflection_loss_db   = float('inf')

            path_loss_totale = fsl_db + reflection_loss_db

            # 3. Fase e Ritardo
            fase_geometrica = -k * distanza_totale
            fase_dielettrica = np.angle(S_accumulata)
            fase_totale_rad = fase_geometrica + fase_dielettrica
            fase_totale_rad_norm = fase_totale_rad % (2 * np.pi)
            fase_totale_gradi = np.degrees(fase_totale_rad_norm)

            ritardo_assoluto_ns = (distanza_totale / c) * 1e9

            aoa_dir           = current_dir / np.linalg.norm(current_dir)
            aoa_azimuth_deg   = np.degrees(np.arctan2(aoa_dir[1], aoa_dir[0]))
            aoa_elevation_deg = np.degrees(np.arcsin(np.clip(aoa_dir[2], -1.0, 1.0)))
            
            # 4. Fasore finale per la Channel Impulse Response (CIR)
            campo_complesso_finale = ampiezza_spazio_libero * S_accumulata * np.exp(1j * fase_geometrica)

            if bounce_count > 0:
                print(
                    f"Ray ID #{ray_id:5d} | Bounces: {bounce_count} | "
                    f"Dist: {distanza_totale:.2f} m | "
                    f"FSL: {fsl_db:.2f} dB | "
                    f"Refl Loss: {reflection_loss_db:.2f} dB | "
                    f"Totale: {path_loss_totale:.2f} dB | "
                    f"Fase: {fase_totale_gradi:.2f}°"
                )

            results["nlos_paths"].append({
                "bounces":               bounce_count,
                "has_diffracted":        has_diffracted,
                "faces_hit":             list(face_ids),
                "points":                path_array,
                "distanza_totale":       distanza_totale,
                "campo_complesso":       campo_complesso_finale,
                "fsl_db":                fsl_db,
                "reflection_loss_db":    reflection_loss_db,
                "path_loss_totale_db":   path_loss_totale,
                "sfasamento_totale_rad": fase_totale_rad_norm,
                "sfasamento_totale_deg": fase_totale_gradi,
                "ritardo_assoluto_ns":   ritardo_assoluto_ns,
                "aoa_direction":         aoa_dir,
                "aoa_azimuth_deg":       aoa_azimuth_deg,
                "aoa_elevation_deg":     aoa_elevation_deg,
                "dettaglio_rimbalzi":    list(cronologia_rimbalzi),
                "r_influence_used":      round(r_check, 6),

            })
            continue

        # --- Riflessione speculare sulla faccia ---
        if terrain_hit:
            normal = mesh.face_normals[cell_id]
            if np.dot(current_dir, normal) > 0:
                normal = -normal

            reflected_dir  = current_dir - 2 * np.dot(current_dir, normal) * normal
            reflected_dir /= np.linalg.norm(reflected_dir)

            # Calcolo di Fresnel Scalare
            cos_theta = np.clip(np.abs(np.dot(current_dir, normal)), 0.0, 1.0)
            angolo_incidenza_deg = np.degrees(np.arccos(cos_theta))
            
            sin2 = np.clip(1.0 - cos_theta**2, 0.0, 1.0)
            sqrt_term = np.sqrt(epsilon_luna - sin2)
            
            R_TE = (cos_theta - sqrt_term) / (cos_theta + sqrt_term)
            R_TM = (epsilon_luna * cos_theta - sqrt_term) / (epsilon_luna * cos_theta + sqrt_term)
            R_scalar = (R_TE + R_TM) / 2.0
            
            S_accumulata_new = S_accumulata * R_scalar

            dati_questo_rimbalzo = {
                "num_rimbalzo":       bounce_count + 1,
                "face_id":            int(cell_id),
                "punto_impatto":      next_vertex.copy(),
                "angolo_incidenza_deg": angolo_incidenza_deg,
            }
            nuova_cronologia = list(cronologia_rimbalzi) + [dati_questo_rimbalzo]

            new_path      = list(path_pts) + [next_vertex]
            new_origin    = next_vertex + normal * 1e-6
            updated_faces = list(face_ids) + [int(cell_id)]
            updated_pts   = list(impact_pts) + [np.round(next_vertex, 2)]

            ray_queue.append((
                ray_id, new_origin, reflected_dir, new_path,
                bounce_count + 1, has_diffracted,
                updated_faces, updated_pts,
                S_accumulata_new, nuova_cronologia,
            ))

    # =============================================================================
    # 4. REPORT FINALE
    # =============================================================================
    print("\n" + "=" * 60)
    print(f"   RAY TRACING FINAL REPORT | f = {frequenza/1e9:.2f} GHz")
    print("=" * 60)
    print(f"  Primary SBR rays hitting RX directly: {results['primary_rays_captured']}")
    bounces_distribution = [p["bounces"] for p in results["nlos_paths"]]
    for b in range(1, max_bounces + 1):
        count = bounces_distribution.count(b)
        print(f"  Paths reaching RX with exactly {b} bounce(s): {count}")

    print("-" * 60)
    print(f"  Keller Diffraction Events Triggered : {total_edges_triggered}")
    print(f"  Total Multipath Signals at RX       : "
          f"{len([p for p in results['nlos_paths'] if p['bounces'] > 0])}")
    print("=" * 60 + "\n")

    return results


class RayBatch:
    """
    Holds the full mutable state of all rays as flat NumPy arrays.
    Avoids any Python-level list allocation during the bounce loop.

    Parameters
    ----------
    origins_init : (N, 3) float32  — all start at TX
    dirs_init    : (N, 3) float32  — Fibonacci sphere directions
    max_bounces  : int             — needed to pre-allocate path_hist
    """

    def __init__(
        self,
        origins_init: np.ndarray,   # (N, 3)
        dirs_init:    np.ndarray,   # (N, 3)
        max_bounces:  int,
    ):
        N = len(origins_init)
        B = max_bounces

        # Core per-ray state
        self.origins    = origins_init.astype(np.float32).copy()  # (N, 3)
        self.dirs       = dirs_init.astype(np.float32).copy()     # (N, 3)

        # Split complex S into two float arrays — avoids complex64 overhead
        self.S_real     = np.ones(N,  dtype=np.float32)
        self.S_imag     = np.zeros(N, dtype=np.float32)

        # Metadata
        self.bounce     = np.zeros(N, dtype=np.int32)
        self.alive      = np.ones(N,  dtype=bool)
        self.diffracted = np.zeros(N, dtype=bool)
        self.dist_acc   = np.zeros(N, dtype=np.float32)   # accumulated metres

        # Pre-allocated path history: waypoints[i, b, :] = b-th waypoint of ray i
        # Slot 0 = TX (initial origin), slots 1…B+1 = bounce/capture points
        self.path_hist  = np.zeros((N, B + 2, 3), dtype=np.float32)
        self.path_len   = np.ones(N, dtype=np.int32)  # how many pts filled so far

        # face_ids stored as object array (can hold "Edge" strings too)
        self.face_ids   = np.empty(N, dtype=object)
        for i in range(N):
            self.face_ids[i] = []

        # Bounce detail log (list of dicts per ray)
        self.cronologia = [[] for _ in range(N)]

        # Initialise slot 0 with TX position
        self.path_hist[:, 0, :] = origins_init.astype(np.float32)

    # ------------------------------------------------------------------
    # Convenience: S as complex view (read-only, for output assembly)
    # ------------------------------------------------------------------
    @property
    def S_complex(self) -> np.ndarray:
        return self.S_real.astype(np.complex64) + 1j * self.S_imag.astype(np.complex64)

    def set_S(self, idx: np.ndarray, values: np.ndarray):
        """Write complex S values back into split arrays."""
        self.S_real[idx] = values.real.astype(np.float32)
        self.S_imag[idx] = values.imag.astype(np.float32)

    # ------------------------------------------------------------------
    # Extend batch (for diffraction child rays)
    # ------------------------------------------------------------------
    def append_rays(
        self,
        new_origins:    np.ndarray,   # (M, 3)
        new_dirs:       np.ndarray,   # (M, 3)
        parent_indices: np.ndarray,   # (M,)  which parent ray each child came from
        parent_S:       np.ndarray,   # (M,)  complex
        new_bounce:     np.ndarray,   # (M,)  int32
        new_diffracted: np.ndarray,   # (M,)  bool
        new_dist_acc:   np.ndarray,   # (M,)  float32
        new_path_hist:  np.ndarray,   # (M, B+2, 3)
        new_path_len:   np.ndarray,   # (M,)
        new_face_ids:   list,         # list of lists
        new_cronologia: list,         # list of lists
    ):
        M  = len(new_origins)
        B2 = self.path_hist.shape[1]

        self.origins    = np.vstack([self.origins,    new_origins.astype(np.float32)])
        self.dirs       = np.vstack([self.dirs,       new_dirs.astype(np.float32)])
        self.S_real     = np.concatenate([self.S_real,  parent_S.real.astype(np.float32)])
        self.S_imag     = np.concatenate([self.S_imag,  parent_S.imag.astype(np.float32)])
        self.bounce     = np.concatenate([self.bounce,   new_bounce.astype(np.int32)])
        self.alive      = np.concatenate([self.alive,    np.ones(M, dtype=bool)])
        self.diffracted = np.concatenate([self.diffracted, new_diffracted])
        self.dist_acc   = np.concatenate([self.dist_acc,   new_dist_acc.astype(np.float32)])

        # Pad / truncate new_path_hist to match existing B+2 width
        ph_padded = np.zeros((M, B2, 3), dtype=np.float32)
        src_w = min(new_path_hist.shape[1], B2)
        ph_padded[:, :src_w, :] = new_path_hist[:, :src_w, :]
        self.path_hist  = np.vstack([self.path_hist,  ph_padded])
        self.path_len   = np.concatenate([self.path_len,  new_path_len.astype(np.int32)])

        new_fi = np.empty(M, dtype=object)
        for i, fi in enumerate(new_face_ids):
            new_fi[i] = list(fi)
        self.face_ids   = np.concatenate([self.face_ids, new_fi])
        self.cronologia += new_cronologia


def run_complete_multipath_engine_batched(
    mesh:                          trimesh.Trimesh,
    pos_tx:                        np.ndarray,      # (3,)
    pos_rx:                        np.ndarray,      # (3,)
    r_influence,                                    # float | None (adaptive)
    num_rays:                      int   = 5_000,
    max_bounces:                   int   = 3,
    epsilon_luna:                  complex = 3.0 - 0.01j,
    frequenza:                     float = 2.4e9,
    enable_diffractions:           bool  = True,
    edge_tolerance:                float = 0.01,
    adaptive_min_wavelength_factor: float = 0.5,
    adaptive_max_cap_meters:        float = 20.0,
    # ── HPC extras ──────────────────────────────────────────────────────
    energy_threshold:              float = S_MIN_MAGNITUDE,   # early-out
    max_path_distance:             float = MAX_PATH_DIST,     # early-out [m]
    num_diff_rays:                 int   = 6,
    enable_profiling:              bool  = False,
    # ── External helpers (same signature as originals) ───────────────────
    extract_diffraction_edges:     Optional[Callable] = None,
    generate_keller_cone_rays:     Optional[Callable] = None,
    check_edge_collision:          Optional[Callable] = None,
    # ── Debug mode ───────────────────────────────────────────────────────
    debug_ray_direction:           Optional[np.ndarray] = None,  # (3,) unit vector
) -> dict:
    """
    Vectorized SBR Multipath Engine — drop-in replacement for the original.

    All ray-mesh intersections are executed in ONE trimesh call per bounce
    over the entire active-ray batch.  Fresnel, sphere checks, and direction
    arithmetic are fully vectorized via NumPy.

    Parameters
    ----------
    (see original docstring — all parameters identical)
    energy_threshold   : kill rays with |S| below this (default 1e-4)
    max_path_distance  : kill rays exceeding this total path length [m]
    enable_profiling   : if True, runs cProfile + section timers and prints
    """

    # ------------------------------------------------------------------
    # 0. Setup
    # ------------------------------------------------------------------
    adaptive_mode   = r_influence is None
    r_cfg           = "adaptive" if adaptive_mode else float(r_influence)

    c          = 299_792_458.0
    wavelength = c / frequenza
    k          = 2.0 * np.pi / wavelength

    pos_tx = np.asarray(pos_tx, dtype=np.float64)
    pos_rx = np.asarray(pos_rx, dtype=np.float64)
    pos_rx_f32 = pos_rx.astype(np.float32)

    results = {
        "los_segment":           None,
        "los_blocked":           False,
        "los_paths":             [],   # ← add this line
        "nlos_paths":            [],
        "keller_events":         [],
        "primary_rays_captured": 0,
        "r_influence_mode":      r_cfg,
    }

    timer = SectionTimer()

    # ------------------------------------------------------------------
    # Optional cProfile wrapper
    # ------------------------------------------------------------------
    profiler = None
    if enable_profiling:
        profiler = cProfile.Profile()
        profiler.enable()

    # ------------------------------------------------------------------
    # 1. LoS check (single vectorized call)
    # ------------------------------------------------------------------
    with timer("los_check"):
        los_vec  = pos_rx - pos_tx
        los_dist = float(np.linalg.norm(los_vec))
        los_dir  = los_vec / los_dist

        los_blocked, blocking_pt = check_los(mesh, pos_tx, pos_rx)

    if los_blocked:
        results["los_blocked"] = True
        results["los_segment"] = np.vstack((pos_tx, blocking_pt))
        print(f"\n[LOS INFO] TX and RX are NOT in Line-of-Sight! "
              f"Blocked at point: {np.round(blocking_pt, 2)}")
    else:
        results["los_blocked"] = False
        results["los_segment"] = np.vstack((pos_tx, pos_rx))

        amp_los  = wavelength / (4.0 * np.pi * los_dist)
        fsl_db   = -20.0 * np.log10(amp_los)
        fase_geo = -k * los_dist
        fase_norm = fase_geo % (2.0 * np.pi)

        print(
            f"\n[LOS INFO] Direct Line-of-Sight (LoS) is CLEAR. "
            f"Dist: {los_dist:.2f} m | "
            f"FSL: {fsl_db:.2f} dB | "
            f"Fase: {np.degrees(fase_norm):.2f}°"
    )

        amp_los      = wavelength / (4.0 * np.pi * los_dist)
        fsl_db       = -20.0 * np.log10(amp_los)
        fase_geo     = -k * los_dist
        fase_norm    = fase_geo % (2.0 * np.pi)
        campo_los    = amp_los * np.exp(1j * fase_geo)
        aoa_az       = np.degrees(np.arctan2(los_dir[1], los_dir[0]))
        aoa_el       = np.degrees(np.arcsin(np.clip(los_dir[2], -1.0, 1.0)))

        results["nlos_paths"].append({
            "ray_id":                -1, 
            "bounces":               0,
            "has_diffracted":        False,
            "faces_hit":             [],
            "points":                np.array([pos_tx, pos_rx]),
            "distanza_totale":       los_dist,
            "campo_complesso":       campo_los,
            "fsl_db":                fsl_db,
            "reflection_loss_db":    0.0,
            "diffraction_loss_db":   0.0,
            "path_loss_totale_db":   fsl_db,
            "sfasamento_totale_rad": fase_norm,
            "sfasamento_totale_deg": np.degrees(fase_norm),
            "ritardo_assoluto_ns":   (los_dist / c) * 1e9,
            "aoa_direction":         los_dir,
            "aoa_azimuth_deg":       aoa_az,
            "aoa_elevation_deg":     aoa_el,
            "dettaglio_rimbalzi":    [],
            "r_influence_used":      None,
        })

    # ------------------------------------------------------------------
    # 2. Diffraction edge pre-processing
    # ------------------------------------------------------------------
    diff_edges = []
    if enable_diffractions and extract_diffraction_edges is not None:
        with timer("extract_edges"):
            diff_edges = extract_diffraction_edges(mesh)

    # ── Vectorize edges into flat arrays for batched collision test ────
    if diff_edges:
        _e_p0  = np.array([e['p0']  for e in diff_edges], dtype=np.float32)  # (E, 3)
        _e_dir = np.array([e['dir'] for e in diff_edges], dtype=np.float32)  # (E, 3)
        _e_len = np.array([e['len'] for e in diff_edges], dtype=np.float32)  # (E,)
        
        # --- NEW: Flatten the normals ---
        _e_n0  = np.array([e['n0']  for e in diff_edges], dtype=np.float32)  # (E, 3)
        _e_n1  = np.array([e['n1']  for e in diff_edges], dtype=np.float32)  # (E, 3)

        _e_cvx = np.array([e['is_convex'] for e in diff_edges], dtype=bool)
    else:
        _e_p0 = _e_dir = _e_len = _e_n0 = _e_n1 = None

    

    # ------------------------------------------------------------------
    # 3. Initialise RayBatch
    # ------------------------------------------------------------------
    debug_mode = debug_ray_direction is not None

    if debug_mode:
        # ── DEBUG MODE: single ray from TX in the given direction ──────
        d = np.asarray(debug_ray_direction, dtype=np.float32)
        d = d / np.linalg.norm(d)
        dirs_np    = d.reshape(1, 3)
        origins_np = pos_tx.astype(np.float32).reshape(1, 3)
        batch      = RayBatch(origins_np, dirs_np, max_bounces)
        print(f"\n--- [DEBUG MODE] Single ray from TX | "
              f"Direction: [{d[0]:.4f}, {d[1]:.4f}, {d[2]:.4f}] ---")
    else:
        # ── NORMAL MODE: full Fibonacci sphere ─────────────────────────
        with timer("init_batch"):
            dirs_np    = fibonacci_sphere(num_rays)
            origins_np = np.tile(pos_tx.astype(np.float32), (num_rays, 1))
            batch      = RayBatch(origins_np, dirs_np, max_bounces)
        print(f"\n--- Launching Combined Ray-Tracing Engine | "
              f"({num_rays} Rays) ---")

    total_edges_triggered = 0

    # ------------------------------------------------------------------
    # 4. BOUNCE LOOP  (outer = depth, inner = vectorized over all alive)
    # ------------------------------------------------------------------
    for bounce in range(max_bounces + 1):

        # ── 4a. Build active index ────────────────────────────────────
        with timer("active_mask"):
            active = np.where(batch.alive)[0]        # global indices

        if len(active) == 0:
            break

        N_act = len(active)
        orig_act = batch.origins[active]             # (N_act, 3)
        dirs_act = batch.dirs[active]                # (N_act, 3)

        # ── 4b. Batch ray-mesh intersection ───────────────────────────
        with timer("intersection"):
            hit_mask, hit_pts, hit_faces, hit_dists = batch_intersect(
                mesh, orig_act, dirs_act, max_path_distance
            )

        # Segment endpoints for sphere test (miss → point at max_dist)
        seg_b = hit_pts  # (N_act, 3) — already set to miss point if no hit

        # ── Debug: print ray state at this bounce ─────────────────────
        if debug_mode:
            o  = orig_act[0]
            d  = dirs_act[0]
            print(f"\n  [DEBUG] Bounce {bounce}")
            print(f"    Origin    : [{o[0]:.4f}, {o[1]:.4f}, {o[2]:.4f}]")
            print(f"    Direction : [{d[0]:.4f}, {d[1]:.4f}, {d[2]:.4f}]")
            if hit_mask[0]:
                hp = hit_pts[0]
                print(f"    Mesh hit  : YES — Face {hit_faces[0]} at "
                      f"[{hp[0]:.4f}, {hp[1]:.4f}, {hp[2]:.4f}] "
                      f"(dist {hit_dists[0]:.4f} m)")
                n = mesh.face_normals[hit_faces[0]]
                print(f"    Normal    : [{n[0]:.4f}, {n[1]:.4f}, {n[2]:.4f}]")
                gi = int(active[0])
                S_val = complex(batch.S_real[gi]) + 1j * complex(batch.S_imag[gi])
                print(f"    S_accum   : {S_val:.6f}  |S| = {abs(S_val):.6f}")
            else:
                print(f"    Mesh hit  : NO — ray exits scene")

        # ── 4c. Edge collision check (sparse CPU loop) ─────────────────
        edge_kill_local = np.zeros(N_act, dtype=bool)

        if enable_diffractions and diff_edges and check_edge_collision and generate_keller_cone_rays:
            with timer("diffraction"):

                # Only test rays that haven't already diffracted
                non_diff_mask = ~batch.diffracted[active]          # (N_act,) bool
                non_diff_li   = np.where(non_diff_mask)[0]         # local indices

                edge_local_idx_list = []
                ep_list, ed_list    = [], []

                if len(non_diff_li) > 0:
                    # Ray segment endpoints: hit point if mesh was hit, else max-dist endpoint
                    seg_ends = np.where(
                        hit_mask[non_diff_li, None],
                        hit_pts[non_diff_li],
                        orig_act[non_diff_li] + dirs_act[non_diff_li] * max_path_distance
                    )                                               # (M, 3)  M = len(non_diff_li)

                    ray_vecs  = seg_ends - orig_act[non_diff_li]   # (M, 3)
                    ray_lens  = np.linalg.norm(ray_vecs, axis=1)   # (M,)
                    valid_ray = ray_lens > 0
                    ray_dirs  = np.where(
                        valid_ray[:, None],
                        ray_vecs / np.where(valid_ray[:, None], ray_lens[:, None], 1.0),
                        0.0
                    ).astype(np.float32)                           # (M, 3)

                    # Broadcast: (M, 1, 3) vs (1, E, 3)
                    u = _e_dir[None, :, :]                         # (1, E, 3)
                    v = ray_dirs[:, None, :]                       # (M, 1, 3)
                    w = _e_p0[None, :, :] - orig_act[non_diff_li, None, :]  # (M, E, 3)

                    a    = np.einsum('eij,eij->ei', u*np.ones_like(w), u*np.ones_like(w))
                    # Simpler: precompute scalar dot products via einsum on the (M,E,3) arrays
                    uu   = np.einsum('...i,...i->...', u   * np.ones((len(non_diff_li),1,1), dtype=np.float32), 
                                                    u   * np.ones((len(non_diff_li),1,1), dtype=np.float32))
                    # Use the cleaner form directly:
                    E    = _e_p0.shape[0]
                    M    = len(non_diff_li)

                    # a = dot(u,u), b = dot(u,v), c = dot(v,v), d = dot(u,w), e = dot(v,w)
                    # All shapes (M, E) via einsum over last axis
                    a_me = np.einsum('ei,ei->e', _e_dir, _e_dir)[None, :] \
                            * np.ones((M, 1), dtype=np.float32)   # (M, E) — constant per edge
                    b_me = np.einsum('mi,ei->me', ray_dirs, _e_dir)          # (M, E)
                    c_me = np.einsum('mi,mi->m', ray_dirs, ray_dirs)[:, None]\
                            * np.ones((1, E), dtype=np.float32)   # (M, E)
                    d_me = np.einsum('mei,ei->me', w, _e_dir)                # (M, E)
                    e_me = np.einsum('mei,mi->me', w, ray_dirs)              # (M, E)
                    
                    denom = a_me * c_me - b_me * b_me              # (M, E)
                    valid_denom = np.abs(denom) >= 1e-6

                    tc = np.where(valid_denom, (a_me * e_me - b_me * d_me) / np.where(valid_denom, denom, 1.0), -1.0)
                    sc = np.where(valid_denom, (b_me * e_me - c_me * d_me) / np.where(valid_denom, denom, 1.0), -1.0)

                    # Parametric range check
                    ray_lens_me = ray_lens[non_diff_li] if len(ray_lens) == M \
                                    else ray_lens                   # already (M,)
                    # expand ray_lens for broadcast
                    rl_me = ray_lens[:, None] * np.ones((1, E), dtype=np.float32)

                    in_range = (tc >= 0) & (tc <= rl_me) \
                            & (sc >= 0) & (sc <= _e_len[None, :])  # (M, E)

                    # Closest-point distance check (tolerance = 0.5 m, matching original)
                    pt_on_edge = _e_p0[None, :, :] \
                            + sc[:, :, None] * _e_dir[None, :, :]          # (M, E, 3)
                    pt_on_ray  = orig_act[non_diff_li, None, :] \
                            + tc[:, :, None] * ray_dirs[:, None, :]         # (M, E, 3)
                    gap        = np.linalg.norm(pt_on_edge - pt_on_ray, axis=2)  # (M, E)

                    hit_me = in_range & (gap <= edge_tolerance)    # (M, E)

                    # For each ray: pick the closest edge that fires, must be nearer than mesh hit
                    # tc doubles as "distance along ray" = distance from origin
                    tc_masked = np.where(hit_me, tc, np.inf)       # (M, E)
                    best_e    = np.argmin(tc_masked, axis=1)        # (M,)
                    best_tc   = tc_masked[np.arange(M), best_e]    # (M,)
                    any_hit   = np.isfinite(best_tc)                # (M,) bool

                    # Must be closer than any mesh hit (or mesh missed entirely)
                    mesh_dist_m = np.where(
                        hit_mask[non_diff_li],
                        hit_dists[non_diff_li].astype(np.float32),
                        np.inf
                    )
                    # closer_than_mesh = best_tc < mesh_dist_m       # (M,) bool

                    # fired = any_hit & closer_than_mesh & valid_ray  # (M,) bool

                    EDGE_MESH_EPSILON = 1e-4
                    closer_than_mesh = best_tc <= (mesh_dist_m + EDGE_MESH_EPSILON)       

                    fired = any_hit & closer_than_mesh & valid_ray
                    
                    edge_starts_list, edge_ends_list = [], []
                    edge_n0_list, edge_n1_list, edge_cvx_list = [], [], []  # <-- NEW
                    
                    for idx_m in np.where(fired)[0]:
                        li  = int(non_diff_li[idx_m])
                        e_i = int(best_e[idx_m])
                        gi  = int(active[li])           
                        ep  = pt_on_edge[idx_m, e_i].astype(np.float64)
                        ed  = _e_dir[e_i].astype(np.float64)
                        e_start = _e_p0[e_i].astype(np.float64)
                        e_end   = e_start + ed * float(_e_len[e_i])
                        
                        edge_local_idx_list.append(li)
                        edge_starts_list.append(e_start)       
                        edge_ends_list.append(e_end)           
                        
                        # --- NEW: Capture the normals for the winning edge ---
                        edge_n0_list.append(_e_n0[e_i].astype(np.float64))
                        edge_n1_list.append(_e_n1[e_i].astype(np.float64))
                        edge_cvx_list.append(_e_cvx[e_i])

                        ep_list.append(ep)
                        ed_list.append(ed)
                        edge_kill_local[li] = True
                        
                if edge_local_idx_list:
                    eli_arr = np.array(edge_local_idx_list)
                    total_edges_triggered += len(eli_arr)

                    inject_keller_children(
                        batch                     = batch,
                        edge_local_idx            = eli_arr,
                        active_global_idx         = active,
                        edge_pts                  = np.array(ep_list, dtype=np.float32),
                        edge_dirs                 = np.array(ed_list, dtype=np.float32),
                        incoming_dirs             = dirs_act[eli_arr],
                        edge_starts               = np.array(edge_starts_list, dtype=np.float32), 
                        edge_ends                 = np.array(edge_ends_list, dtype=np.float32),   
                        
                        # --- NEW: Pass the normal arrays ---
                        edge_n0                   = np.array(edge_n0_list, dtype=np.float32),
                        edge_n1                   = np.array(edge_n1_list, dtype=np.float32),
                        edge_is_convex = np.array(edge_cvx_list, dtype=bool),
                        
                        keller_events             = results["keller_events"],
                        k_wave                    = k,
                        generate_keller_cone_rays = generate_keller_cone_rays,
                        num_diff_rays             = num_diff_rays,
                    )
                    batch.alive[active[eli_arr]] = False

        # ── 4d. Vectorized RX sphere check ────────────────────────────
        with timer("sphere_check"):
            if adaptive_mode:
                dist_to_rx = np.linalg.norm(
                    orig_act - pos_rx_f32, axis=1
                ).astype(np.float32)
                total_dist_est = batch.dist_acc[active] + dist_to_rx
                r_check = vec_adaptive_r(
                    total_dist_est, origins_np.shape[0],
                    wavelength,
                    adaptive_min_wavelength_factor,
                    adaptive_max_cap_meters,
                )
            else:
                r_check = float(r_influence)

            # Closest-point sphere check — exact vectorized equivalent of
            # the original check_sphere_intersection():
            #   closest = p_start + clip(dot(rx-p_start, dir), 0, seg_len) * dir
            #   hit     = ||rx - closest|| <= r_influence
            w_rx        = pos_rx_f32 - orig_act                              # (N,3)
            seg_vecs    = seg_b - orig_act                                   # (N,3)
            seg_lens    = np.linalg.norm(seg_vecs, axis=1)                  # (N,)
            safe_lens   = np.where(seg_lens > 0, seg_lens, 1.0)
            dirs_norm   = seg_vecs / safe_lens[:, None]                      # (N,3)
            proj        = np.einsum('ij,ij->i', w_rx, dirs_norm)            # (N,)
            proj_cl     = np.clip(proj, 0.0, seg_lens)                      # (N,)
            closest_pts = orig_act + proj_cl[:, None] * dirs_norm           # (N,3)
            dist_to_cls = np.linalg.norm(pos_rx_f32 - closest_pts, axis=1) # (N,)
            rx_hit_mask = dist_to_cls <= (r_check if adaptive_mode
                                          else float(r_influence))           # (N,) bool
            rx_pts      = closest_pts                                        # (N,3)

        # ── 4e. Process captured rays ─────────────────────────────────
        with timer("capture_assembly"):
            captured_local = np.where(rx_hit_mask & ~edge_kill_local)[0]

            for li in captured_local:
                gi      = int(active[li])
                if not batch.alive[gi]:   # ← ADD THIS GUARD
                    continue

                b_count = int(batch.bounce[gi])

                # ── Direct rays (bounce == 0) ─────────────────────────────────
                if b_count == 0:
                    results["primary_rays_captured"] += 1
                    batch.alive[gi] = False

                    closest_pt   = rx_pts[li].astype(np.float64)
                    dist_direct  = float(np.linalg.norm(closest_pt - pos_tx))
                    amp_direct   = wavelength / (4.0 * np.pi * dist_direct)
                    fase_direct  = -k * dist_direct
                    campo_direct = amp_direct * np.exp(1j * fase_direct)
                    fsl_direct   = -20.0 * np.log10(amp_direct)

                    print(
                        f"Ray ID #{gi:5d} | Bounces: 0 | [D] "
                        f"Dist: {dist_direct:.2f} m | "
                        f"FSL: {fsl_direct:.2f} dB | "
                        f"Fase: {np.degrees(fase_direct % (2*np.pi)):.2f}°"
                    )

                    fase_direct_norm = fase_direct % (2.0 * np.pi)

                    results["los_paths"].append({
                        "distanza_totale":       dist_direct,
                        "campo_complesso":       campo_direct,
                        "fsl_db":                fsl_direct,
                        "sfasamento_totale_rad": fase_direct_norm,
                        "sfasamento_totale_deg": np.degrees(fase_direct_norm),
                        "ritardo_assoluto_ns":   (dist_direct / c) * 1e9,
                    })
                    continue

                # ── Bounced/diffracted rays (bounce >= 1) ─────────────────────
                is_keller = bool(batch.diffracted[gi])
                ray_label = "[K]" if is_keller else "[P]"

                pl         = int(batch.path_len[gi])
                closest_pt = rx_pts[li].astype(np.float64)
                path_arr   = np.vstack([
                    batch.path_hist[gi, :pl, :].astype(np.float64),
                    closest_pt,
                ])
                segs     = np.diff(path_arr, axis=0)
                dist_tot = float(np.sum(np.linalg.norm(segs, axis=1)))

                # ── FSL — must come before scattering decomposition ──────────
                if is_keller:
                    s_prime = float(batch.dist_acc[gi])
                    edge_pt = batch.path_hist[gi, pl - 1, :].astype(np.float64)
                    s_child = float(np.linalg.norm(pos_rx - edge_pt))

                    if s_prime < 1e-9 or s_child < 1e-9:
                        batch.alive[gi] = False
                        continue

                    A_spread = np.sqrt(s_prime / (s_child * (s_prime + s_child)))
                    
                    # FIX: Calculate the incident amplitude using the total distance to the edge
                    amp_incident = wavelength / (4.0 * np.pi * s_prime)
                    amp          = amp_incident * A_spread
                else:
                    # Restored: Standard spherical divergence for pure reflections
                    amp = wavelength / (4.0 * np.pi * dist_tot)

                fsl_db = -20.0 * np.log10(amp)

                # ── Scattering loss decomposition ─────────────────────────────
                S_val    = complex(batch.S_real[gi]) + 1j * complex(batch.S_imag[gi])
                mag_S    = abs(S_val)

                diff_mag = 1.0
                for b in batch.cronologia[gi]:
                    if b.get('tipo') == 'diffraction':
                        diff_mag *= b.get('D_coef_mag', 1.0)

                refl_mag = (mag_S / diff_mag) if diff_mag > 1e-12 else mag_S
                refl_db  = -20.0 * np.log10(refl_mag) if refl_mag > 1e-12 else float('inf')
                diff_db  = -20.0 * np.log10(diff_mag) if diff_mag > 1e-12 else float('inf')
                pl_db    = fsl_db + refl_db + diff_db

                # ── Phase ─────────────────────────────────────────────────────
                fase_geo = -k * dist_tot
                fase_die = float(np.angle(S_val))
                fase_tot = (fase_geo + fase_die) % (2.0 * np.pi)

                # ── AoA ───────────────────────────────────────────────────────
                aoa_dir  = dirs_act[li].astype(np.float64)
                aoa_dir /= np.linalg.norm(aoa_dir)
                aoa_az   = np.degrees(np.arctan2(aoa_dir[1], aoa_dir[0]))
                aoa_el   = np.degrees(np.arcsin(np.clip(aoa_dir[2], -1.0, 1.0)))

                campo  = amp * S_val * np.exp(1j * fase_geo)
                r_used = float(r_check[li]) if adaptive_mode else float(r_influence)

                print(
                    f"Ray ID #{gi:5d} | Bounces: {b_count} | "
                    f"{ray_label} | "
                    f"Dist: {dist_tot:.2f} m | "
                    f"FSL: {fsl_db:.2f} dB | "
                    f"Refl: {refl_db:.2f} dB | "
                    f"Diff: {diff_db:.2f} dB | "
                    f"Total: {pl_db:.2f} dB | "
                    f"Fase: {np.degrees(fase_tot):.2f}°"
                )

                results["nlos_paths"].append({
                    "ray_id":                gi,
                    "bounces":               b_count,
                    "has_diffracted":        bool(batch.diffracted[gi]),
                    "faces_hit":             list(batch.face_ids[gi]),
                    "points":                path_arr,
                    "distanza_totale":       dist_tot,
                    "campo_complesso":       campo,
                    "fsl_db":                fsl_db,
                    "reflection_loss_db":    refl_db,
                    "diffraction_loss_db":   diff_db,
                    "path_loss_totale_db":   pl_db,
                    "sfasamento_totale_rad": fase_tot,
                    "sfasamento_totale_deg": np.degrees(fase_tot),
                    "ritardo_assoluto_ns":   (dist_tot / c) * 1e9,
                    "aoa_direction":         aoa_dir,
                    "aoa_azimuth_deg":       aoa_az,
                    "aoa_elevation_deg":     aoa_el,
                    "dettaglio_rimbalzi":    list(batch.cronologia[gi]),
                    "r_influence_used":      round(r_used, 6),
                })

                batch.alive[gi] = False

        # ── 4f. Vectorized Fresnel reflection ─────────────────────────
        with timer("fresnel_reflect"):
            # Rays that: hit mesh, not captured, not edge-killed, still alive
            refl_local_mask = (
                hit_mask
                & ~rx_hit_mask
                & ~edge_kill_local
                & batch.alive[active]
            )
            refl_local = np.where(refl_local_mask)[0]

            if len(refl_local) > 0:
                r_orig  = orig_act[refl_local]          # (M, 3)
                r_dirs  = dirs_act[refl_local]          # (M, 3)
                r_hpts  = hit_pts[refl_local]           # (M, 3)  hit positions
                r_dists = hit_dists[refl_local]         # (M,)
                r_faces = hit_faces[refl_local]         # (M,)  int32
                r_gi    = active[refl_local]            # (M,)  global indices

                # Fetch face normals for all hitting faces at once
                normals = mesh.face_normals[r_faces].astype(np.float32)   # (M, 3)

                # Flip normals that face away from the incoming ray
                dot_signs = np.einsum('ij,ij->i', r_dirs, normals)       # (M,)
                flip      = dot_signs > 0.0
                normals[flip] = -normals[flip]

                # Fresnel scalar — one NumPy call for all M rays
                R_vec = vec_fresnel_scalar(r_dirs, normals, epsilon_luna)  # (M,) complex

                # Accumulate S
                S_old = batch.S_real[r_gi] + 1j * batch.S_imag[r_gi]    # (M,) complex
                S_new = S_old * R_vec
                batch.S_real[r_gi] = S_new.real.astype(np.float32)
                batch.S_imag[r_gi] = S_new.imag.astype(np.float32)

                # Reflected directions — vectorized
                new_dirs = vec_reflect(r_dirs, normals)                   # (M, 3)

                # New origins = hit_pt + normal * epsilon
                new_origs = r_hpts + normals * NORMAL_OFFSET              # (M, 3)

                # Update accumulated distance
                batch.dist_acc[r_gi] += r_dists.astype(np.float32)

                # Write back to batch
                batch.origins[r_gi] = new_origs
                batch.dirs[r_gi]    = new_dirs
                batch.bounce[r_gi] += 1

                # Update path history (pre-allocated slot)
                ang_inc = np.degrees(
                    np.arccos(np.clip(np.abs(dot_signs[~flip if len(flip) else slice(None)]),
                                      0.0, 1.0))
                )
                for ii, gi in enumerate(r_gi):
                    pl = int(batch.path_len[gi])
                    if pl < batch.path_hist.shape[1]:
                        batch.path_hist[gi, pl, :] = r_hpts[ii]
                        batch.path_len[gi] = pl + 1

                    batch.face_ids[gi]   = list(batch.face_ids[gi]) + [int(r_faces[ii])]
                    batch.cronologia[gi].append({
                        "num_rimbalzo":         int(batch.bounce[gi]),
                        "face_id":              int(r_faces[ii]),
                        "punto_impatto":        r_hpts[ii].astype(np.float64).copy(),
                        "angolo_incidenza_deg": float(np.degrees(
                            np.arccos(np.clip(abs(dot_signs[ii]), 0.0, 1.0))
                        )),
                    })

        # ── 4g. Early-out pruning ──────────────────────────────────────
        with timer("pruning"):
            # Energy threshold: kill rays whose accumulated |S| is too small
            S_mag = np.sqrt(
                batch.S_real[active] ** 2 + batch.S_imag[active] ** 2
            )
            low_energy = active[S_mag < energy_threshold]
            batch.alive[low_energy] = False

            # Distance threshold: kill rays that have walked too far
            over_dist  = active[batch.dist_acc[active] > max_path_distance]
            batch.alive[over_dist] = False

            # Kill rays that exceed max_bounces
            over_bounce = active[batch.bounce[active] > max_bounces]
            batch.alive[over_bounce] = False

            # Kill rays that missed the mesh entirely
            missed = active[~hit_mask]
            batch.alive[missed] = False

            over_bounce = active[batch.bounce[active] > max_bounces]
            batch.alive[over_bounce] = False



    # ------------------------------------------------------------------
    # 5. Profiling output  (only when explicitly requested)
    # ------------------------------------------------------------------
    if enable_profiling:
        timer.report()

    if profiler is not None:
        profiler.disable()
        sio = io.StringIO()
        ps  = pstats.Stats(profiler, stream=sio).sort_stats("cumulative")
        ps.print_stats(20)
        print("\n── cProfile top-20 ──────────────────────────────────")
        print(sio.getvalue())

    # ------------------------------------------------------------------
    # 6. Final report
    # ------------------------------------------------------------------
    
    unique_paths = []

    # ── Coherent sum of all NLOS rays grouped by physical path ────────
    seen_signatures = {}

    for p in results["nlos_paths"]:
        # Extract ID (ensure you added "ray_id": gi in your append block)
        current_gi = p.get("ray_id", -1)
        sig = (p["bounces"], tuple(p["faces_hit"]), p["has_diffracted"])

        if sig not in seen_signatures:
            seen_signatures[sig] = p.copy()
            # Initialize the tracking list for all micro-rays in this group
            seen_signatures[sig]["membro_raggruppamento"] = [current_gi]
        else:
            # Coherent sum: add complex fields
            seen_signatures[sig]["campo_complesso"] += p["campo_complesso"]
            # Track this micro-ray's ID as part of this macroscopic path
            seen_signatures[sig]["membro_raggruppamento"].append(current_gi)

    # Re-calculate dB for the final groups
    for sig, p in seen_signatures.items():
        mag_final = abs(p["campo_complesso"])
        if mag_final > 1e-15:
            p["path_loss_totale_db"] = -20.0 * np.log10(mag_final)
        else:
            p["path_loss_totale_db"] = float('inf')

    # Reconstruct the list
    results["nlos_paths"] = list(seen_signatures.values())


    pure_refl  = [p for p in results["nlos_paths"] if not p["has_diffracted"]]
    diff_paths = [p for p in results["nlos_paths"] if p["has_diffracted"]]

    print("\n" + "=" * 60)
    print(f"   RAY TRACING FINAL REPORT | f = {frequenza/1e9:.2f} GHz")
    print("=" * 60)
    print(f"  Direct rays captured (SBR)  : {results['primary_rays_captured']}")
    print("-" * 60)

    for b in range(1, max_bounces + 1):
        r_count = len([p for p in pure_refl  if p["bounces"] == b])
        d_count = len([p for p in diff_paths if p["bounces"] == b])
        total_b = r_count + d_count
        if total_b > 0:
            print(f"  Paths reaching RX with exactly {b} bounce(s): {total_b}")
            print(f"     ├─ Pure Reflections: {r_count}")
            print(f"     └─ Diffracted Paths: {d_count}")

    print("-" * 60)
    print(f"  Keller Diffraction Events Triggered : {total_edges_triggered}")
    print(f"  Total Multipath Signals at RX       : "
          f"{len([p for p in results['nlos_paths'] if p['bounces'] > 0])}")
    print("=" * 60 + "\n")

    return results
