"""terrain_io — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
from rasterio.enums import Resampling
from rasterio.windows import Window
import matplotlib.pyplot as plt
import numpy as np
import pathlib
import rasterio
import trimesh
from pyproj import CRS
import spiceypy as spice
from rasterio.enums import Resampling
from rasterio.windows import from_bounds
from pyproj import Transformer
import plotly.graph_objects as go
import plotly.io as pio
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

tifs_dir = BASE_DIR / "tifs_new"
kernels_dir = BASE_DIR / "kernels"
meshes_dir = BASE_DIR / "meshes"

spice.furnsh(str(kernels_dir / "naif0012.tls"))
spice.furnsh(str(kernels_dir / "moon_de440_220930.tf"))
spice.furnsh(str(kernels_dir / "moon_pa_de440_200625.bpc"))
spice.furnsh(str(kernels_dir / "pck00011.tpc"))

def jp2_viewer(file_path):
    with rasterio.open(file_path) as src:
        # Mostra i metadati principali (SRID, trasformazione affine, dimensioni)
        print("Sistema di Riferimento (CRS):", src.crs)
        print("Dimensioni (Pixel):", src.width, "x", src.height)
        print("Numero di bande:", src.count)
        
        dem_data = src.read(1)
        
        nodata_value = src.nodata
        if nodata_value is not None:
            import numpy as np
            dem_data = np.where(dem_data == nodata_value, np.nan, dem_data)


    plt.figure(figsize=(10, 8))
    plt.imshow(dem_data, cmap='terrain')
    plt.colorbar(label='Elevazione (metri)')
    plt.title('Digital Elevation Model da file .jp2')
    plt.show()


def jp2_2_tif(file_ingresso, file_uscita): 
    profili_ottimizzati = {
        'driver': 'GTiff',
        'tiled': True,
        'blockxsize': 256,
        'blockysize': 256,
        'compression': 'DEFLATE',
        'predictor': 2
    }

    print("Inizio conversione... Attendi qualche minuto.")
    with rasterio.open(file_ingresso) as src:
        meta = src.meta.copy()
        meta.update(profili_ottimizzati)
        
        with rasterio.open(file_uscita, 'w', **meta) as dst:
            # Legge e scrive a blocchi per non saturare la RAM
            for ji, window in src.block_windows(1):
                data = src.read(1, window=window)
                dst.write(data, 1, window=window)
                
    print("Conversione completata! Usa il nuovo file 'luna_pole_sud_ottimizzato.tif' nei tuoi script.")


def read_tif(file_path):
    with rasterio.open(file_path) as src:
        print("--- PROPRIETÀ BASE DEL RASTER ---")
        print(f"Larghezza (Colonne):   {src.width} pixel")
        print(f"Altezza (Righe):       {src.height} pixel")
        # print(f"Numero di Bande:       {src.count}")
        # print(f"Tipo di dati (Dtype):  {src.dtypes[0]}") # es. float32, int16
        # print(f"Valore NoData nativo:  {src.nodata}")
        altezza = src.height
        larghezza = src.width
        
        # print("\n--- GEORIFERENZIAZIONE E COORDINATE ---")
        # print(f"Sistema di Riferimento (CRS):\n{src.crs}")
        
        # La risoluzione spaziale (dimensione reale del pixel)
        # Nel tuo caso restituirà (20.0, 20.0) cioè metri per pixel
        print(f"Risoluzione pixel (X, Y): {src.res} metri")
        
        # I confini geografici/metrici estremi della mappa (Bounding Box)
        print(f"Bordi della mappa (Bounds):\n{src.bounds}")
        
        # print("\n--- 📐 MATRICE DI TRASFORMAZIONE AFFINE ---")
        # # La matrice usata dal GIS per convertire i Pixel (riga, colonna) in Metri del mondo reale
        # print(src.transform)
        
        # print("\n--- 📦 DIZIONARIO METADATI COMPLETO (.meta) ---")
        # # Un riassunto rapido in formato dizionario Python, utilissimo per creare nuovi file condivisibili
        # print(src.meta)

        dem_zone = src.read(1)
        quota_minima = np.min(dem_zone)
        quota_massima = np.max(dem_zone)
        quota_media = np.mean(dem_zone)
        deviazione_standard = np.std(dem_zone)
        
        print("\n--- 🏔️ ANALISI STATISTICA ALTEZZE LUNARI ---")
        print(f"Punto più profondo (Crateri): {quota_minima} metri")
        print(f"Punto più elevato (Picchi):     {quota_massima} metri")
        print(f"Dislivello totale nella scena:  {quota_massima - quota_minima} metri")
        print(f"Elevazione media del terreno:   {quota_media:.2f} metri")
        print(f"Variabilità del terreno (Std):  {deviazione_standard:.2f} metri")

        return altezza, larghezza


def analisi_terreno(file_path):
    """
    Esegue un'analisi geomorfologica completa direttamente da un file GeoTIFF.
    Non richiede la generazione della mesh 3D.
    """
    with rasterio.open(file_path) as src:
        Z = src.read(1).astype(float)
        risoluzione_x, risoluzione_y = src.res

    # --- 1. STATISTICHE ALTIMETRICHE ---
    quota_min  = np.min(Z)
    quota_max  = np.max(Z)
    quota_media = np.mean(Z)
    quota_std  = np.std(Z)

    print("--- 🏔️ STATISTICHE ALTIMETRICHE ---")
    print(f"Punto più profondo:    {quota_min:.1f} m")
    print(f"Punto più elevato:     {quota_max:.1f} m")
    print(f"Dislivello totale:     {quota_max - quota_min:.1f} m")
    print(f"Elevazione media:      {quota_media:.1f} m")
    print(f"Variabilità (Std):     {quota_std:.1f} m")

    # --- 2. CALCOLO PENDENZA (SLOPE) ---
    # Gradiente finito centrale su X e Y in unità reali (metri)
    dz_dy, dz_dx = np.gradient(Z, risoluzione_y, risoluzione_x)
    pendenza_gradi = np.degrees(np.arctan(np.sqrt(dz_dx**2 + dz_dy**2)))

    print("\n--- 📐 STATISTICHE PENDENZA ---")
    print(f"Pendenza massima:  {np.max(pendenza_gradi):.1f}°")
    print(f"Pendenza media:    {np.mean(pendenza_gradi):.1f}°")
    print(f"Pendenza mediana:  {np.median(pendenza_gradi):.1f}°")

    # --- 3. CLASSIFICAZIONE GEOMORFOLOGICA ---
    totale_px = Z.size

    pianura_bassa_mask = (pendenza_gradi < 5.0)  & (Z < quota_media)
    pianura_alta_mask  = (pendenza_gradi < 5.0)  & (Z >= quota_media)
    pendio_mask        = (pendenza_gradi >= 5.0)  & (pendenza_gradi <= 20.0)
    montagna_mask      =  pendenza_gradi > 20.0

    pct_bacino     = np.sum(pianura_bassa_mask) / totale_px * 100
    pct_altopiano  = np.sum(pianura_alta_mask)  / totale_px * 100
    pct_pendio     = np.sum(pendio_mask)         / totale_px * 100
    pct_montagna   = np.sum(montagna_mask)       / totale_px * 100

    print("\n--- 🌋 CLASSIFICAZIONE GEOMORFOLOGICA ---")
    print(f"🟩 Pianura in Depressione (Bacino/Cratere): {pct_bacino:.1f}%")
    print(f"🟨 Pianura Elevata (Altopiano):             {pct_altopiano:.1f}%")
    print(f"🟧 Pendii e Raccordi Dolci:                 {pct_pendio:.1f}%")
    print(f"🟥 Versanti Ripidi (Bordi Cratere):         {pct_montagna:.1f}%")

    # --- 4. DISTRIBUZIONE ALTIMETRICA (PERCENTILI) ---
    print("\n--- 📊 DISTRIBUZIONE ALTIMETRICA ---")
    for p in [1, 5, 25, 50, 75, 95, 99]:
        print(f"  {p:>3}° percentile: {np.percentile(Z, p):.1f} m")

    return


def write_and_save_tif(file_ingresso, file_output, lato_pixel=None, lato_km=None, centro_x=None, centro_y=None, centro_x_km=None, centro_y_km=None):
    """
    Esegue il clipping quadrato di un GeoTIFF.
    Il lato può essere specificato in pixel (lato_pixel) o in km (lato_km).
    Il centro può essere specificato in pixel (centro_x, centro_y) 
    oppure in chilometri (centro_x_km, centro_y_km).
    Se nessun centro è fornito, usa il centro geometrico del file.
    
    Parametri:
    - file_ingresso:  str,   percorso file sorgente
    - file_output:    str,   percorso file destinazione
    - lato_pixel:     int,   dimensione del lato in pixel (opzionale)
    - lato_km:        float, dimensione del lato in km (opzionale)
    - centro_x:       int,   coordinata X del centro in pixel (opzionale)
    - centro_y:       int,   coordinata Y del centro in pixel (opzionale)
    - centro_x_km:    float, coordinata X del centro in km (opzionale)
    - centro_y_km:    float, coordinata Y del centro in km (opzionale)
    """
    risoluzione_metro_pixel = 20.0

    # --- RISOLUZIONE DEL LATO ---
    if lato_pixel is not None and lato_km is not None:
        raise ValueError("Errore: specifica solo uno tra lato_pixel e lato_km, non entrambi.")
    elif lato_km is not None:
        lato_pixel = int(round((lato_km * 1000.0) / risoluzione_metro_pixel))
        print(f"Lato: {lato_km} km → {lato_pixel} px")
    elif lato_pixel is not None:
        print(f"Lato: {lato_pixel} px → {lato_pixel * risoluzione_metro_pixel / 1000:.3f} km")
    else:
        raise ValueError("Errore: specifica almeno uno tra lato_pixel e lato_km.")

    with rasterio.open(file_ingresso) as src:
        res_x, res_y = src.res
        risoluzione_metro_pixel_x = abs(res_x)
        risoluzione_metro_pixel_y = abs(res_y)
        
        W_max = src.width
        H_max = src.height
        mezzo_lato = lato_pixel // 2

        centro_assoluto_x = W_max // 2
        centro_assoluto_y = H_max // 2

        # --- RISOLUZIONE DEL CENTRO ---
        if centro_x is not None and centro_y is not None:
            cx = centro_x
            cy = centro_y
            print(f"Modalità: pixel diretti → ({cx}, {cy})")

        elif centro_x_km is not None and centro_y_km is not None:
            offset_pixel_x = int(round((centro_x_km * 1000.0) / risoluzione_metro_pixel_x))
            offset_pixel_y = int(round((centro_y_km * 1000.0) / risoluzione_metro_pixel_y))
            cx = centro_assoluto_x + offset_pixel_x
            cy = centro_assoluto_y - offset_pixel_y
            print(f"Modalità: km ({centro_x_km}, {centro_y_km}) → pixel ({cx}, {cy})")

        else:
            cx = centro_assoluto_x
            cy = centro_assoluto_y
            print(f"Modalità: centro geometrico del file → ({cx}, {cy})")

        # Controllo strutturale
        if lato_pixel > W_max or lato_pixel > H_max:
            raise ValueError(f"Errore: Il lato richiesto ({lato_pixel}px) supera la dimensione del file ({W_max}x{H_max}px).")

        # --- FAIL-SAFE: clamping ai bordi ---
        offset_x = max(0, min(cx - mezzo_lato, W_max - lato_pixel))
        offset_y = max(0, min(cy - mezzo_lato, H_max - lato_pixel))

        finestra_clipping = Window(offset_x, offset_y, lato_pixel, lato_pixel)
        dem_ritagliato = src.read(1, window=finestra_clipping)
        nuova_trasformazione = rasterio.windows.transform(finestra_clipping, src.transform)
        nuovi_metadati = src.meta.copy()
        nuovi_metadati.update({
            'height': lato_pixel,
            'width':  lato_pixel,
            'transform': nuova_trasformazione
        })

    with rasterio.open(file_output, 'w', **nuovi_metadati) as dst:
        dst.write(dem_ritagliato, 1)

    print(f"✅ File salvato: '{file_output}'")
    print(f"Finestra ({lato_pixel}x{lato_pixel} px): Colonne [{offset_x}:{offset_x+lato_pixel}], Righe [{offset_y}:{offset_y+lato_pixel}]")


def creates_normals(baricentri, normali, passo_grafico, lunghezza_metri):
    """
    Calcola i segmenti di linea pronti per go.Scatter3d staccati da None,
    ma applica il passo PRIMA di generare le liste per risparmiare memoria e CPU.
    """
    # Applica il campionamento (passo) direttamente sulle matrici dei dati prima del calcolo
    baricentri_ridotti = baricentri[::passo_grafico]
    normali_ridotte = normali[::passo_grafico]
    
    num_tri_filtrati = len(baricentri_ridotti)
    
    # Allocazione matrici vettorizzate
    X_mat = np.zeros((num_tri_filtrati, 3))
    Y_mat = np.zeros((num_tri_filtrati, 3))
    Z_mat = np.zeros((num_tri_filtrati, 3))
    
    p_inizio = baricentri_ridotti
    p_fine = baricentri_ridotti + (normali_ridotte * lunghezza_metri)
    
    X_mat[:, :2] = np.vstack((p_inizio[:, 0], p_fine[:, 0])).T
    Y_mat[:, :2] = np.vstack((p_inizio[:, 1], p_fine[:, 1])).T
    Z_mat[:, :2] = np.vstack((p_inizio[:, 2], p_fine[:, 2])).T
    
    X_mat[:, 2] = np.nan
    Y_mat[:, 2] = np.nan
    Z_mat[:, 2] = np.nan
    
    Xg = [None if np.isnan(val) else val for val in X_mat.flatten()]
    Yg = [None if np.isnan(val) else val for val in Y_mat.flatten()]
    Zg = [None if np.isnan(val) else val for val in Z_mat.flatten()]
    
    return Xg, Yg, Zg


def tif2mesh(file_path, fattore_esagerazione_z=1.0):
    with rasterio.open(file_path) as src:
        Z = src.read(1).astype(float)
        ny, nx = Z.shape

        cols = np.arange(nx)
        rows = np.arange(ny)

        # Pixel-center coordinates, not raster outer bounds
        x = np.array([
            rasterio.transform.xy(src.transform, 0, c, offset="center")[0]
            for c in cols
        ])

        y_top_to_bottom = np.array([
            rasterio.transform.xy(src.transform, r, 0, offset="center")[1]
            for r in rows
        ])

    # Make y ascend bottom -> top, consistent with your current mesh convention
    Z = np.flipud(Z) * fattore_esagerazione_z
    y = y_top_to_bottom[::-1]

    X, Y = np.meshgrid(x, y)

    vertices = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T

    idx = np.arange(ny * nx).reshape(ny, nx)
    top_left     = idx[:-1, :-1].ravel()
    top_right    = idx[:-1, 1:].ravel()
    bottom_left  = idx[1:, :-1].ravel()
    bottom_right = idx[1:, 1:].ravel()

    faces = np.vstack([
        np.vstack([top_left, bottom_left, top_right]).T,
        np.vstack([bottom_left, bottom_right, top_right]).T,
    ])

    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)

    return vertices[:, 0], vertices[:, 1], vertices[:, 2], faces, mesh


def upsampling_geotiff(file_input, file_output, nuova_risoluzione_metri=10.0, metodo_interpolazione='cubic'):
    
    metodi_supportati = {
        'cubic':        Resampling.cubic,
        'cubic_spline': Resampling.cubic_spline,
        'bilinear':     Resampling.bilinear,
        'lanczos':      Resampling.lanczos,
        'nearest':      Resampling.nearest,
        'average':      Resampling.average,
        'mode':         Resampling.mode,
    }
    
    if metodo_interpolazione not in metodi_supportati:
        raise ValueError(f"Metodo '{metodo_interpolazione}' non supportato. Scegli tra: {list(metodi_supportati.keys())}")
    
    resampling_algo = metodi_supportati[metodo_interpolazione]

    with rasterio.open(file_input) as src:
        risoluzione_attuale_x, _ = src.res
        fattore_scala = risoluzione_attuale_x / nuova_risoluzione_metri
        nuova_larghezza = int(src.width * fattore_scala)
        nuova_altezza = int(src.height * fattore_scala)
        
        print(f"--- 🔄 AVVIO RICAMPIONAMENTO ---")
        print(f"Risoluzione originale: {risoluzione_attuale_x} m/px -> Dimensione: {src.width}x{src.height}")
        print(f"Nuova risoluzione:     {nuova_risoluzione_metri} m/px -> Dimensione: {nuova_larghezza}x{nuova_altezza}")
        print(f"Metodo utilizzato:     {metodo_interpolazione}")
        
        dati_ricampionati = src.read(
            1,
            out_shape=(nuova_altezza, nuova_larghezza),
            resampling=resampling_algo
        )
        
        nuova_trasformazione = src.transform * src.transform.scale(
            (src.width / nuova_larghezza),
            (src.height / nuova_altezza)
        )
        
        nuovi_metadati = src.meta.copy()
        nuovi_metadati.update({
            "height": nuova_altezza,
            "width":  nuova_larghezza,
            "transform": nuova_trasformazione
        })
    
    with rasterio.open(file_output, "w", **nuovi_metadati) as dst:
        dst.write(dati_ricampionati, 1)
        
    print(f"🎉 Salvataggio completato: '{file_output}'\n")


def create_trimesh_canyon(width=100.0, length=100.0, depth=30.0, res_x=20, res_y=20):
    """
    Creates a symmetric V-shaped validation canyon, returning a Trimesh object.
    """
    x = np.linspace(-width/2, width/2, res_x)
    y = np.linspace(-length/2, length/2, res_y)
    X, Y = np.meshgrid(x, y)
    Z = depth * (np.abs(X) / (width/2)) - depth

    # Convert structured grid to vertices and faces for Trimesh
    vertices = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T
    
    faces = []
    for i in range(res_y - 1):
        for j in range(res_x - 1):
            v0 = i * res_x + j
            v1 = v0 + 1
            v2 = (i + 1) * res_x + j
            v3 = v2 + 1
            faces.append([v0, v1, v2])
            faces.append([v1, v3, v2])
            
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
    return mesh


def generate_lunar_mesh(size=100, res=500, num_craters=15, max_height=1.5):
    """Genera un mesh lunare pianeggiante con micro-rugosità e crateri sparsi.

    Args:
        size (float): Dimensione laterale del terreno quadrato [metri]
        res (int): Risoluzione della griglia (numero di vertici per lato)
        num_craters (int): Numero di crateri da scavare nel terreno
        max_height (float): Altezza massima della micro-rugosità (regolite)
    """
    # 1. Creazione della griglia X, Y piatta
    x = np.linspace(-size / 2, size / 2, res)
    y = np.linspace(-size / 2, size / 2, res)
    X, Y = np.meshgrid(x, y)

    # 2. Generazione micro-rugosità di fondo (regolite lunare) mediante onde sinusoidali sovrapposte
    # (Simula un rumore frattale pseudo-casuale per mantenere il codice privo di librerie esterne)
    Z = np.zeros_like(X)
    frequencies = [0.1, 0.3, 0.8]
    amplitudes = [max_height * 0.5, max_height * 0.3, max_height * 0.1]

    for f, a in zip(frequencies, amplitudes):
        Z += a * np.sin(f * X + 1.5) * np.cos(f * Y + 0.7)
        Z += a * 0.5 * np.cos(f * 2 * X) * np.sin(f * 2 * Y)

    # 3. Scavo dei crateri (Funzione gaussiana modificata per creare bordo sollevato e fondo piatto)
    # np.random.seed(42)  # Per rendere il terreno riproducibile
    for _ in range(num_craters):
        # Centro del cratere casuale sul piano
        cx = np.random.uniform(-size * 0.4, size * 0.4)
        cy = np.random.uniform(-size * 0.4, size * 0.4)

        # Raggio del cratere (piccoli, per mantenere il terreno prevalentemente piatto)
        r_crater = np.random.uniform(4.0, 12.0)
        depth = np.random.uniform(2.0, 5.0)

        # Distanza di ogni punto della griglia dal centro del cratere
        dist = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2)

        # Profilo matematico del cratere lunare
        # - Depressione centrale gaussiana
        depressione = -depth * np.exp(-((dist / (r_crater * 0.8)) ** 2))
        # - Lieve innalzamento del bordo esterno (effetto espulsione detriti)
        bordo = (depth * 0.3) * np.exp(-(((dist - r_crater) / (r_crater * 0.3)) ** 2))

        Z += depressione + bordo

    # 4. Compilazione dei vertici in formato (N, 3)
    vertices = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T

    # 5. Generazione delle facce triangolari (Pattern standard per griglie regolari)
    faces = []
    for i in range(res - 1):
        for j in range(res - 1):
            # Indici dei 4 vertici del quadrato corrente
            v0 = i * res + j
            v1 = v0 + 1
            v2 = (i + 1) * res + j
            v3 = v2 + 1
            # Divisione del quadrato in due triangoli
            faces.append([v0, v1, v2])
            faces.append([v1, v3, v2])

    faces = np.array(faces)

    # 6. Creazione del mesh tramite Trimesh
    lunar_mesh = trimesh.Trimesh(vertices=vertices, faces=faces)

    # Forza il calcolo delle normali delle facce e dei vertici per il Ray Tracing
    lunar_mesh.fix_normals()

    return lunar_mesh


def generate_lunar_mesh_2(
    size=100.0, 
    triangle_resolution=0.5,  # <--- Nuova gestione: distanza in metri tra i vertici
    terrain_type='basin', 
    num_craters=15, 
    min_crater_r=4.0, 
    max_crater_r=12.0, 
    max_height=1.5,
    seed=None
):
    """Genera un mesh lunare tridimensionale controllando la dimensione reale dei triangoli.

    Args:
        size (float): Dimensione laterale del terreno quadrato [metri]
        triangle_resolution (float): Dimensione del lato di ogni triangolo/passo della griglia [metri]
        terrain_type (str): Tipo di macro-terreno ('flat', 'basin', 'hill', 'mountainous')
        num_craters (int): Numero di crateri da scavare nel terreno
        min_crater_r (float): Raggio minimo dei crateri [metri]
        max_crater_r (float): Raggio massimo dei crateri [metri]
        max_height (float): Altezza massima della micro-rugosità di fondo
        seed (int, optional): Seed per rendere la generazione deterministica
    """
    if seed is not None:
        np.random.seed(seed)

    # 1. Calcolo dinamico della risoluzione della griglia (quanti vertici servono per lato)
    # Calcola il numero di segmenti necessari e aggiunge 1 per includere il vertice finale
    res = int(np.ceil(size / triangle_resolution)) + 1
    
    # 2. Creazione della griglia X, Y regolare
    x = np.linspace(-size / 2, size / 2, res)
    y = np.linspace(-size / 2, size / 2, res)
    X, Y = np.meshgrid(x, y)
    Z = np.zeros_like(X)

    # 3. Generazione della Macro-Topografia (Forma del terreno base)
    t = terrain_type.lower()
    if t == 'flat':
        Z += np.sin(X * 0.01) * np.cos(Y * 0.01) * 0.5
    elif t == 'basin':
        dist_center_sq = X**2 + Y**2
        Z -= (size * 0.15) * np.exp(-dist_center_sq / (2 * (size * 0.25)**2))
        Z += np.sin(X * 0.04) * np.cos(Y * 0.04) * 0.8
    elif t == 'hill':
        Z += (np.sin(X * 0.05) * (size * 0.03)) + (np.cos(Y * 0.04) * (size * 0.03))
    elif t == 'mountainous':
        Z += np.abs(np.sin(X * 0.04) * np.cos(Y * 0.04)) * (size * 0.12)
        Z += np.sin(X * 0.15) * np.sin(Y * 0.12) * (size * 0.02)
    else:
        raise ValueError("terrain_type deve essere 'flat', 'basin', 'hill' o 'mountainous'")

    # 4. Generazione micro-rugosità di fondo (regolite lunare)
    frequencies = [0.1, 0.3, 0.8]
    amplitudes = [max_height * 0.5, max_height * 0.3, max_height * 0.1]

    for f, a in zip(frequencies, amplitudes):
        Z += a * np.sin(f * X + 1.5) * np.cos(f * Y + 0.7)
        Z += a * 0.5 * np.cos(f * 2 * X) * np.sin(f * 2 * Y)

    # 5. Scavo dei crateri (Ordinati dal più grande al più piccolo)
    crater_radii = np.random.uniform(min_crater_r, max_crater_r, num_craters)
    crater_radii.sort()
    crater_radii = crater_radii[::-1]

    for r_crater in crater_radii:
        cx = np.random.uniform(-size * 0.45, size * 0.45)
        cy = np.random.uniform(-size * 0.45, size * 0.45)
        depth = r_crater * np.random.uniform(0.2, 0.35)
        dist = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2)

        depressione = -depth * np.exp(-((dist / (r_crater * 0.8)) ** 2))
        bordo = (depth * 0.25) * np.exp(-(((dist - r_crater) / (r_crater * 0.25)) ** 2))

        Z += depressione + bordo

    # 6. Compilazione dei vertici in formato (N, 3)
    vertices = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T

    # 7. Generazione delle facce triangolari (Pattern standard CCW)
    faces = []
    for i in range(res - 1):
        for j in range(res - 1):
            v0 = i * res + j
            v1 = v0 + 1
            v2 = (i + 1) * res + j
            v3 = v2 + 1
            
            faces.append([v0, v1, v2])
            faces.append([v1, v3, v2])

    faces = np.array(faces)

    # 8. Creazione del mesh tramite Trimesh con ricalcolo delle normali
    lunar_mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
    lunar_mesh.fix_normals()

    return lunar_mesh


def ply_merger(
    folder_path: str, output_file_path: str
) -> None:
    """Carica tutti i file .

    ply da una cartella, li unisce in un unico
    grande oggetto Trimesh e lo salva come un singolo file .ply.
    """
    path = pathlib.Path(folder_path)
    mesh_list = []

    # Trova tutti i file .ply nella cartella
    for file_path in path.glob("*.ply"):
        try:
            geometry = trimesh.load(str(file_path))

            # Se il file viene letto come scena, estrae le singole mesh
            if isinstance(geometry, trimesh.Scene):
                for mesh in geometry.geometry.values():
                    mesh_list.append(mesh)
            else:
                mesh_list.append(geometry)

        except Exception as e:
            print(f"Errore nel caricamento di {file_path.name}: {e}")

    # Verifica se sono state trovate mesh
    if not mesh_list:
        raise ValueError("Nessun file .ply valido trovato nella cartella.")

    print(f"Unione di {len(mesh_list)} elementi in corso...")

    # Unisce tutte le mesh in un unico grande blocco di dati
    big_mesh = trimesh.util.concatenate(mesh_list)

    # Esporta direttamente nel percorso specificato come file .ply
    big_mesh.export(output_file_path, file_type="ply")
    print(f"Salvataggio completato con successo in: {output_file_path}")

def _as_pyproj_crs(crs):
    """
    Convert rasterio CRS or pyproj CRS to pyproj CRS.
    """
    return CRS.from_user_input(crs)


def _get_dem_crs(src):
    if src.crs is None:
        raise ValueError("The DEM has no CRS.")
    return _as_pyproj_crs(src.crs)


def _get_lunar_geographic_crs(dem_crs):
    """
    Extract the geographic lunar CRS from the projected DEM CRS.
    """
    dem_crs = _as_pyproj_crs(dem_crs)

    geo_crs = dem_crs.geodetic_crs

    if geo_crs is None:
        raise ValueError("Could not extract geographic CRS from DEM CRS.")

    return geo_crs


def _get_moon_radius_from_crs(dem_crs):
    """
    Extract lunar reference radius from CRS.

    For your CRS, this should return 1737400 m.
    """
    dem_crs = _as_pyproj_crs(dem_crs)
    return float(dem_crs.ellipsoid.semi_major_metre)


def _pixel_center_xy(transform, rows, cols):
    """
    Convert raster row/col indices to projected x/y coordinates at pixel centers.
    Works also if the affine transform has rotation terms.
    """
    x = (
        transform.c
        + (cols + 0.5) * transform.a
        + (rows + 0.5) * transform.b
    )

    y = (
        transform.f
        + (cols + 0.5) * transform.d
        + (rows + 0.5) * transform.e
    )

    return x, y

def inspect_dem(dem_path):
    with rasterio.open(dem_path) as src:
        print("CRS:")
        print(src.crs)
        print()

        print("Size:")
        print(f"width  = {src.width}")
        print(f"height = {src.height}")
        print()

        print("Resolution [m/px]:")
        print(src.res)
        print()

        print("Scene Size:")
        print(f"{src.width * src.res[0] * 1e-3} x {src.height * src.res[1] * 1e-3} km")
        print()

        print("Bounds [projected meters]:")
        print(src.bounds)
        print()

        print("Transform:")
        print(src.transform)
        print()

        print("NoData:")
        print(src.nodata)

def visualize_dem_2d(
    dem_path,
    downsample_factor=20,
    colorscale="Earth_r",
    clip_percentiles=(2, 98),
    title="LOLA DEM 2D preview",
):
    with rasterio.open(dem_path) as src:
        out_h = max(2, src.height // downsample_factor)
        out_w = max(2, src.width // downsample_factor)

        dem = src.read(
            1,
            out_shape=(out_h, out_w),
            resampling=Resampling.nearest,
        ).astype(float)

        transform = src.transform * src.transform.scale(
            src.width / out_w,
            src.height / out_h,
        )

        nodata = src.nodata

    if nodata is not None:
        dem[dem == nodata] = np.nan

    rows, cols = np.indices(dem.shape)
    x_m, y_m = _pixel_center_xy(transform, rows, cols)

    zmin = zmax = None
    if clip_percentiles is not None:
        zmin = float(np.nanpercentile(dem, clip_percentiles[0]))
        zmax = float(np.nanpercentile(dem, clip_percentiles[1]))

    fig = go.Figure(data=go.Heatmap(
        x=x_m[0, :] / 1000.0,
        y=y_m[:, 0] / 1000.0,
        z=dem,
        zmin=zmin,
        zmax=zmax,
        colorscale=colorscale,
        colorbar=dict(title="Elevation [m]"),
        hovertemplate=(
            "X: %{x:.3f} km<br>"
            "Y: %{y:.3f} km<br>"
            "Elevation: %{z:.1f} m"
            "<extra></extra>"
        ),
    ))

    fig.update_layout(
        title=title,
        xaxis=dict(
            title="Polar stereographic X [km]",
            scaleanchor="y",
            scaleratio=1,
        ),
        yaxis=dict(title="Polar stereographic Y [km]"),
        width=900,
        height=800,
    )

    fig.show()

def latlon_to_dem_xy(lat_deg, lon_deg, dem_crs):
    """
    Lunar lat/lon -> DEM projected x/y meters.
    """
    geo_crs = _get_lunar_geographic_crs(dem_crs)

    transformer = Transformer.from_crs(
        geo_crs,
        dem_crs,
        always_xy=True,
    )

    x_m, y_m = transformer.transform(lon_deg, lat_deg)
    return x_m, y_m

def selection_to_bounds(
    dem_path,
    method,
    *,
    center_lat=None,
    center_lon=None,
    center_x_km=None,
    center_y_km=None,
    side_km=None,
    vertices_latlon=None,
    vertices_xy_km=None,
    xy_km_is_offset_from_raster_center=False,
):
    """
    Return rectangular crop bounds in DEM projected meters:
        left, bottom, right, top

    Supported methods:
        "center_latlon"
        "center_xy_km"
        "vertices_latlon"
        "vertices_xy_km"

    For xy_km methods:
        default = absolute polar stereographic km
        optional = offset from raster center, matching your older function style
    """

    with rasterio.open(dem_path) as src:
        dem_crs = _get_dem_crs(src)
        bounds = src.bounds

        raster_center_x = 0.5 * (bounds.left + bounds.right)
        raster_center_y = 0.5 * (bounds.bottom + bounds.top)

    if method == "center_latlon":
        if center_lat is None or center_lon is None or side_km is None:
            raise ValueError("center_latlon requires center_lat, center_lon, side_km.")

        cx, cy = latlon_to_dem_xy(center_lat, center_lon, dem_crs)

        half = 0.5 * side_km * 1000.0
        left = cx - half
        right = cx + half
        bottom = cy - half
        top = cy + half

    elif method == "center_xy_km":
        if center_x_km is None or center_y_km is None or side_km is None:
            raise ValueError("center_xy_km requires center_x_km, center_y_km, side_km.")

        cx = center_x_km * 1000.0
        cy = center_y_km * 1000.0

        if xy_km_is_offset_from_raster_center:
            cx = raster_center_x + cx
            cy = raster_center_y + cy

        half = 0.5 * side_km * 1000.0
        left = cx - half
        right = cx + half
        bottom = cy - half
        top = cy + half

    elif method == "vertices_latlon":
        if vertices_latlon is None or len(vertices_latlon) != 4:
            raise ValueError("vertices_latlon requires exactly 4 points: [(lat, lon), ...].")

        xs = []
        ys = []

        for lat, lon in vertices_latlon:
            x, y = latlon_to_dem_xy(lat, lon, dem_crs)
            xs.append(x)
            ys.append(y)

        left = min(xs)
        right = max(xs)
        bottom = min(ys)
        top = max(ys)

    elif method == "vertices_xy_km":
        if vertices_xy_km is None or len(vertices_xy_km) != 4:
            raise ValueError("vertices_xy_km requires exactly 4 points: [(x_km, y_km), ...].")

        xs = np.array([p[0] for p in vertices_xy_km], dtype=float) * 1000.0
        ys = np.array([p[1] for p in vertices_xy_km], dtype=float) * 1000.0

        if xy_km_is_offset_from_raster_center:
            xs = raster_center_x + xs
            ys = raster_center_y + ys

        left = float(np.min(xs))
        right = float(np.max(xs))
        bottom = float(np.min(ys))
        top = float(np.max(ys))

    else:
        raise ValueError(
            "method must be one of: center_latlon, center_xy_km, vertices_latlon, vertices_xy_km"
        )

    return left, bottom, right, top

def crop_dem_by_bounds(
    dem_path,
    output_path,
    bounds_m,
):
    """
        Crop a GeoTIFF using projected bounds in the DEM CRS.

        bounds_m = (left, bottom, right, top)

        # Centered square by lat/lon
    bounds_m = selection_to_bounds(
        dem_path,
        method="center_latlon",
        center_lat=-89.67,
        center_lon=129.78,
        side_km=25.0,
    )

    # Centered square by projected km
    bounds_m = selection_to_bounds(
        dem_path,
        method="center_xy_km",
        center_x_km=0.0,
        center_y_km=0.0,
        side_km=25.0,
    )

    # Four lat/lon vertices, rectangular envelope
    bounds_m = selection_to_bounds(
        dem_path,
        method="vertices_latlon",
        vertices_latlon=[
            (-89.8, 120.0),
            (-89.8, 140.0),
            (-89.5, 140.0),
            (-89.5, 120.0),
        ],
    )

    # Four projected-km vertices, rectangular envelope
    bounds_m = selection_to_bounds(
        dem_path,
        method="vertices_xy_km",
        vertices_xy_km=[
            (-10.0, -10.0),
            ( 10.0, -10.0),
            ( 10.0,  10.0),
            (-10.0,  10.0),
        ],
    )
    """

    left, bottom, right, top = bounds_m

    with rasterio.open(dem_path) as src:
        raw_window = from_bounds(
            left,
            bottom,
            right,
            top,
            transform=src.transform,
        )

        window = raw_window.round_offsets().round_lengths()

        full_window = Window(0, 0, src.width, src.height)
        window = window.intersection(full_window)

        if window.width <= 0 or window.height <= 0:
            raise ValueError("Crop window is outside the DEM bounds.")

        data = src.read(1, window=window)

        new_transform = rasterio.windows.transform(window, src.transform)

        meta = src.meta.copy()
        meta.update({
            "height": int(window.height),
            "width": int(window.width),
            "transform": new_transform,
        })

    with rasterio.open(output_path, "w", **meta) as dst:
        dst.write(data, 1)

    print(f"Saved cropped DEM: {output_path}")
    print(
        f"Window: row={window.row_off}, col={window.col_off}, "
        f"height={window.height}, width={window.width}"
    )

    return output_path, window

def dem_to_pa_mesh(
    dem_path,
    *,
    target_resolution_m=None,
    resampling_method="lanczos",
    utc_time="2026-06-22T00:00:00",
):
    """
    Convert a lunar South-Pole polar stereographic DEM to a triangular mesh
    in the MOON_PA frame.

    Parameters
    ----------
    dem_path : str
        Path to the cropped or full DEM GeoTIFF.

    target_resolution_m : float or None
        Desired mesh grid spacing in meters.

        None:
            use native DEM resolution.

        Equal to native resolution:
            unchanged sampling.

        Larger than native resolution:
            coarser mesh, e.g. 20 m -> 100 m.

        Smaller than native resolution:
            interpolated finer mesh, e.g. 20 m -> 10 m.

    resampling_method : str
        One of:
            "nearest", "bilinear", "cubic", "cubic_spline",
            "lanczos", "average"

        For physically faithful native DEM:
            use "nearest".

        For smoother visualization:
            use "bilinear" or "cubic".

        For coarsening:
            use "average" or "bilinear".

    utc_time : str
        Epoch used for SPICE ME -> PA rotation.

    Returns
    -------
    mesh_pa : trimesh.Trimesh
        Triangular terrain mesh in MOON_PA coordinates.

    aux : dict
        Useful arrays and metadata.
    """

    resampling_methods = {
        "nearest": Resampling.nearest,
        "bilinear": Resampling.bilinear,
        "cubic": Resampling.cubic,
        "cubic_spline": Resampling.cubic_spline,
        "lanczos": Resampling.lanczos,
        "average": Resampling.average,
    }

    if resampling_method not in resampling_methods:
        raise ValueError(
            f"Unknown resampling_method='{resampling_method}'. "
            f"Choose one of {list(resampling_methods.keys())}."
        )

    resampling = resampling_methods[resampling_method]

    # ------------------------------------------------------------
    # 1. Read DEM, optionally resampled to target_resolution_m
    # ------------------------------------------------------------
    with rasterio.open(dem_path) as src:
        if src.crs is None:
            raise ValueError("DEM has no CRS. Cannot convert stereographic coordinates to lat/lon.")

        dem_crs = CRS.from_user_input(src.crs)

        geo_crs = dem_crs.geodetic_crs
        if geo_crs is None:
            raise ValueError("Could not extract lunar geographic CRS from DEM CRS.")

        r_moon = float(dem_crs.ellipsoid.semi_major_metre)

        native_w = src.width
        native_h = src.height

        native_res_x = abs(src.res[0])
        native_res_y = abs(src.res[1])

        if target_resolution_m is None:
            out_w = native_w
            out_h = native_h
        else:
            scale_x = native_res_x / target_resolution_m
            scale_y = native_res_y / target_resolution_m

            out_w = int(round(native_w * scale_x))
            out_h = int(round(native_h * scale_y))

            out_w = max(2, out_w)
            out_h = max(2, out_h)

        dem_masked = src.read(
            1,
            out_shape=(out_h, out_w),
            resampling=resampling,
            masked=True,
        )

        dem = dem_masked.astype(float).filled(np.nan)

        transform = src.transform * src.transform.scale(
            native_w / out_w,
            native_h / out_h,
        )

    effective_res_x = native_res_x * native_w / out_w
    effective_res_y = native_res_y * native_h / out_h

    print(f"Native DEM resolution:      {native_res_x:.3f} m × {native_res_y:.3f} m")
    print(f"Requested mesh resolution:  {target_resolution_m}")
    print(f"Output DEM shape:           {out_h} × {out_w}")
    print(f"Effective mesh resolution:  {effective_res_x:.3f} m × {effective_res_y:.3f} m")
    print(f"Resampling method:          {resampling_method}")

    # ------------------------------------------------------------
    # 2. Pixel centers -> stereographic projected x/y
    # ------------------------------------------------------------
    rows, cols = np.indices(dem.shape)

    x_ps = (
        transform.c
        + (cols + 0.5) * transform.a
        + (rows + 0.5) * transform.b
    )

    y_ps = (
        transform.f
        + (cols + 0.5) * transform.d
        + (rows + 0.5) * transform.e
    )

    # ------------------------------------------------------------
    # 3. Stereographic x/y -> lunar lon/lat
    # ------------------------------------------------------------
    to_geo = Transformer.from_crs(
        dem_crs,
        geo_crs,
        always_xy=True,
    )

    lon_deg, lat_deg = to_geo.transform(x_ps, y_ps)

    lon = np.deg2rad(lon_deg)
    lat = np.deg2rad(lat_deg)

    # ------------------------------------------------------------
    # 4. lon/lat/elevation -> Moon-centered ME-like Cartesian
    # ------------------------------------------------------------
    radius = r_moon + dem

    X_me = radius * np.cos(lat) * np.cos(lon)
    Y_me = radius * np.cos(lat) * np.sin(lon)
    Z_me = radius * np.sin(lat)

    vertices_me = np.column_stack([
        X_me.ravel(),
        Y_me.ravel(),
        Z_me.ravel(),
    ])

    # ------------------------------------------------------------
    # 5. ME -> PA rotation with SPICE
    # ------------------------------------------------------------
    et = spice.str2et(utc_time)
    R_me_to_pa = spice.pxform("MOON_ME", "MOON_PA", et)

    # Row-vector convention:
    # v_pa = R_me_to_pa @ v_me for column vectors
    # therefore for row arrays:
    # vertices_pa = vertices_me @ R_me_to_pa.T
    vertices_pa = vertices_me @ R_me_to_pa.T

    valid_vertex = np.all(np.isfinite(vertices_pa), axis=1)

    # ------------------------------------------------------------
    # 6. Build triangular faces
    # ------------------------------------------------------------
    ny, nx = dem.shape
    idx = np.arange(ny * nx).reshape(ny, nx)

    faces_1 = np.column_stack([
        idx[:-1, :-1].ravel(),
        idx[1:, :-1].ravel(),
        idx[:-1, 1:].ravel(),
    ])

    faces_2 = np.column_stack([
        idx[1:, :-1].ravel(),
        idx[1:, 1:].ravel(),
        idx[:-1, 1:].ravel(),
    ])

    faces = np.vstack([faces_1, faces_2])

    # Remove triangles touching invalid DEM pixels
    keep_faces = np.all(valid_vertex[faces], axis=1)
    faces = faces[keep_faces]

    # ------------------------------------------------------------
    # 7. Build trimesh object
    # ------------------------------------------------------------
    mesh_pa = trimesh.Trimesh(
        vertices=vertices_pa,
        faces=faces,
        process=False,
    )

    print(f"Vertices:                  {len(vertices_pa):,}")
    print(f"Faces kept:                {len(faces):,}")

    aux = {
        "dem": dem,
        "x_ps": x_ps,
        "y_ps": y_ps,
        "lat_deg": lat_deg,
        "lon_deg": lon_deg,
        "X_me": X_me,
        "Y_me": Y_me,
        "Z_me": Z_me,
        "vertices_me": vertices_me,
        "vertices_pa": vertices_pa,
        "faces": faces,
        "native_resolution_x_m": native_res_x,
        "native_resolution_y_m": native_res_y,
        "effective_resolution_x_m": effective_res_x,
        "effective_resolution_y_m": effective_res_y,
        "target_resolution_m": target_resolution_m,
        "resampling_method": resampling_method,
        "r_moon": r_moon,
        "R_me_to_pa": R_me_to_pa,
        "dem_crs": dem_crs,
        "geo_crs": geo_crs,
        "transform": transform,
    }

    return mesh_pa, aux

def normalize(v):
    v = np.asarray(v, dtype=float)
    n = np.linalg.norm(v)
    if n == 0:
        raise ValueError("Cannot normalize zero vector.")
    return v / n


def build_local_frame_from_pa_mesh(mesh_pa, x_hint_pa=None):
    """
    Build a local visualization/simulation frame from a PA mesh.

    The local frame is:
        origin_local = center of the patch
        +Z_local     = radial up, away from Moon center
        +X_local     = tangent direction chosen from x_hint_pa
        +Y_local     = completes right-handed frame

    Returns:
        origin_pa
        A_local_to_pa

    where columns of A_local_to_pa are:
        [x_local_in_pa, y_local_in_pa, z_local_in_pa]
    """

    vertices = np.asarray(mesh_pa.vertices, dtype=float)
    valid = np.all(np.isfinite(vertices), axis=1)

    if not np.any(valid):
        raise ValueError("Mesh has no valid vertices.")

    # Patch center in PA coordinates
    origin_pa = np.mean(vertices[valid], axis=0)

    # Local Up = radial direction from Moon center to patch center
    z_up_pa = normalize(origin_pa)

    # Choose a global reference vector to define local X.
    # Near the south pole, PA Z is almost parallel to local up/down,
    # so [0,0,1] may be a bad choice. Use [1,0,0] by default if needed.
    if x_hint_pa is None:
        candidate = np.array([0.0, 0.0, 1.0])

        if abs(np.dot(candidate, z_up_pa)) > 0.9:
            candidate = np.array([1.0, 0.0, 0.0])
    else:
        candidate = normalize(x_hint_pa)

    # Project candidate onto the tangent plane
    x_local_pa = candidate - np.dot(candidate, z_up_pa) * z_up_pa
    x_local_pa = normalize(x_local_pa)

    # Right-handed frame: x cross y = z
    y_local_pa = np.cross(z_up_pa, x_local_pa)
    y_local_pa = normalize(y_local_pa)

    A_local_to_pa = np.column_stack([
        x_local_pa,
        y_local_pa,
        z_up_pa,
    ])

    return origin_pa, A_local_to_pa

def pa_to_local(points_pa, origin_pa, A_local_to_pa):
    """
    Convert PA coordinates to local frame.

    points_pa can be:
        shape (3,)
        shape (N, 3)
    """
    points_pa = np.asarray(points_pa, dtype=float)
    return (points_pa - origin_pa) @ A_local_to_pa


def local_to_pa(points_local, origin_pa, A_local_to_pa):
    """
    Convert local coordinates back to PA.
    """
    points_local = np.asarray(points_local, dtype=float)
    return origin_pa + points_local @ A_local_to_pa.T


def mesh_pa_to_local(mesh_pa, origin_pa, A_local_to_pa):
    """
    Convert a PA trimesh terrain mesh to local coordinates.
    Faces are unchanged.
    """
    vertices_local = pa_to_local(mesh_pa.vertices, origin_pa, A_local_to_pa)

    mesh_local = trimesh.Trimesh(
        vertices=vertices_local,
        faces=mesh_pa.faces.copy(),
        process=False,
    )

    return mesh_local

def plot_vector3d(fig, start, end, color="red", width =1, name="Vector"):
    """Aggiunge un vettore 3D (linea + punta a cono) a una figura esistente."""
    x0, y0, z0 = start
    x1, y1, z1 = end
    
    # 1. Linea del corpo del vettore
    fig.add_trace(go.Scatter3d(
        x=[x0, x1], y=[y0, y1], z=[z0, z1],
        mode='lines', line=dict(color=color, width=width), name=name
    ))
    
    # 2. Punta del vettore (Cono) posizionata esattamente sulla fine (end)
    fig.add_trace(go.Cone(
        x=[x1], y=[y1], z=[z1],                 # Posizione della punta
        u=[x1-x0], v=[y1-y0], w=[z1-z0],       # Direzione del vettore
        colorscale=[[0, color], [1, color]],    # Colore solido
        showscale=False, sizemode='absolute', sizeref=width/10
    ))

def plot_point3D(fig, point, color="red", size =1, name="Vector"):
    """Aggiunge un vettore 3D (linea + punta a cono) a una figura esistente."""
    x, y, z = point
    
    # 1. Linea del corpo del vettore
    fig.add_trace(go.Scatter3d(
        x=[x], y=[y], z=[z],
        mode='markers', marker=dict(size=12, color = color), name=name,
    ))
    

def plot_sphere3d_mesh(fig, center=(0,0,0), radius=1.0, color="lightblue", name="Sphere"):
    """Aggiunge una sfera 3D a una figura Plotly esistente usando go.Mesh3d."""
    xc, yc, zc = center
    from scipy.spatial import ConvexHull
    # 1. Genera punti campionati uniformemente sulla superficie sferica
    # Usiamo coordinate sferiche appiattite in array 1D
    phi = np.linspace(0, np.pi, 20)
    theta = np.linspace(0, 2 * np.pi, 20)
    phi, theta = np.meshgrid(phi, theta)
    phi = phi.flatten()
    theta = theta.flatten()
    
    # 2. Trasforma in coordinate cartesiane 1D (Vertici)
    x = xc + radius * np.sin(phi) * np.cos(theta)
    y = yc + radius * np.sin(phi) * np.sin(theta)
    z = zc + radius * np.cos(phi)
    
    # 3. Calcola l'involucro convesso (Convex Hull) per ottenere le facce triangolari
    points = np.vstack((x, y, z)).T
    hull = ConvexHull(points)
    i, j, k = hull.simplices.T  # Indici dei vertici che formano ogni triangolo
    
    # 4. Aggiunge la mesh alla figura con i parametri grafici originali
    fig.add_trace(go.Mesh3d(
        x=x, y=y, z=z,
        i=i, j=j, k=k,
        color=color,          # go.Mesh3d accetta direttamente il parametro color!
        opacity=0.5,
        flatshading=False,    # Se True, mostra i triangoli netti stile "low-poly"
        name=name,
        showlegend=True,
        lighting=dict(
            ambient=0.2,
            diffuse=0.8,
            specular=0.5,
            roughness=0.5,
            fresnel=0.2
        ),
        lightposition=dict(x=1, y=1, z=0.5)
    ))

def stereographic_xy_to_local(
    x_ps_m,
    y_ps_m,
    dem_crs,
    origin_pa,
    A_local_to_pa,
    utc_time,
    alt_m=0.0,
):
    """
    Convert lunar polar stereographic coordinates to your local mesh frame.

    Inputs
    ------
    x_ps_m, y_ps_m:
        Polar stereographic DEM coordinates in meters.

    dem_crs:
        CRS of the DEM, for example src.crs.

    origin_pa, A_local_to_pa:
        Local-frame definition obtained from build_local_frame_from_pa_mesh(mesh_pa).

    utc_time:
        Epoch for SPICE MOON_ME -> MOON_PA transformation.

    alt_m:
        Height above lunar reference sphere.
        For grid-center placement, use 0.0.
        generate_grid_nodes() will later find the actual terrain height.

    Returns
    -------
    p_local:
        3D point in local coordinates.

    info:
        Dictionary with intermediate lat/lon and PA coordinates.
    """

    dem_crs = CRS.from_user_input(dem_crs)
    geo_crs = dem_crs.geodetic_crs

    if geo_crs is None:
        raise ValueError("Could not extract lunar geographic CRS from DEM CRS.")

    r_moon = float(dem_crs.ellipsoid.semi_major_metre)

    # 1. Polar stereographic x/y -> lunar lon/lat
    to_geo = Transformer.from_crs(
        dem_crs,
        geo_crs,
        always_xy=True,
    )

    lon_deg, lat_deg = to_geo.transform(x_ps_m, y_ps_m)

    lon = np.deg2rad(lon_deg)
    lat = np.deg2rad(lat_deg)

    # 2. lon/lat/alt -> ME-like Moon-centered Cartesian
    radius = r_moon + alt_m

    p_me = np.array([
        radius * np.cos(lat) * np.cos(lon),
        radius * np.cos(lat) * np.sin(lon),
        radius * np.sin(lat),
    ], dtype=float)

    # 3. ME -> PA
    et = spice.str2et(utc_time)
    R_me_to_pa = spice.pxform("MOON_ME", "MOON_PA", et)

    p_pa = R_me_to_pa @ p_me

    # 4. PA -> local
    p_local = pa_to_local(
        p_pa,
        origin_pa,
        A_local_to_pa,
    )

    info = {
        "lat_deg": lat_deg,
        "lon_deg": lon_deg,
        "p_me": p_me,
        "p_pa": p_pa,
        "p_local": p_local,
    }

    return p_local, info

def stereographic_xy_to_pa(x_ps_m, y_ps_m, dem_crs, utc_time, alt_m=0.0):
    """Lunar polar stereographic x/y -> MOON_PA Cartesian point."""
    dem_crs = CRS.from_user_input(dem_crs)
    geo_crs = dem_crs.geodetic_crs
    if geo_crs is None:
        raise ValueError("Could not extract lunar geographic CRS from DEM CRS.")
    r_moon = float(dem_crs.ellipsoid.semi_major_metre)

    # 1. stereographic -> lon/lat
    to_geo = Transformer.from_crs(dem_crs, geo_crs, always_xy=True)
    lon_deg, lat_deg = to_geo.transform(x_ps_m, y_ps_m)
    lon, lat = np.deg2rad(lon_deg), np.deg2rad(lat_deg)

    # 2. lon/lat/alt -> ME Cartesian
    radius = r_moon + alt_m
    p_me = np.array([
        radius * np.cos(lat) * np.cos(lon),
        radius * np.cos(lat) * np.sin(lon),
        radius * np.sin(lat),
    ], dtype=float)

    # 3. ME -> PA
    et = spice.str2et(utc_time)
    R_me_to_pa = spice.pxform("MOON_ME", "MOON_PA", et)
    p_pa = R_me_to_pa @ p_me

    info = {"lat_deg": lat_deg, "lon_deg": lon_deg, "p_me": p_me, "p_pa": p_pa}
    return p_pa, info