"""timing — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
from collections import defaultdict
import time


class SectionTimer:
    """
    Lightweight per-section wall-clock accumulator.
    Usage:
        timer = SectionTimer()
        with timer("intersection"):
            ...batch_intersect(...)
        timer.report()
    """

    def __init__(self):
        self._acc   = defaultdict(float)
        self._calls = defaultdict(int)
        self._cur   = None
        self._t0    = None

    def __call__(self, name: str):
        self._cur = name
        return self

    def __enter__(self):
        self._t0 = time.perf_counter()
        return self

    def __exit__(self, *_):
        elapsed = time.perf_counter() - self._t0
        self._acc[self._cur]   += elapsed
        self._calls[self._cur] += 1

    def report(self):
        print("\n" + "─" * 52)
        print("  SECTION TIMING REPORT")
        print("─" * 52)
        total = sum(self._acc.values())
        for name, t in sorted(self._acc.items(), key=lambda x: -x[1]):
            pct   = 100.0 * t / total if total > 0 else 0.0
            calls = self._calls[name]
            print(f"  {name:<26} {t:7.3f}s  {pct:5.1f}%  (×{calls})")
        print(f"  {'TOTAL':<26} {total:7.3f}s")
        print("─" * 52 + "\n")
