"""viz — auto-generated by module split (behaviour-preserving)."""
from __future__ import annotations
from rasterio.windows import Window
import numpy as np
import plotly.graph_objects as go
import rasterio
from geometry import check_sphere_intersection, batch_intersect, check_los
from em_core import pattern_from_grap

def plot_vector3d(fig, start, end, color="red", width =1, name="Vector"):
    """Aggiunge un vettore 3D (linea + punta a cono) a una figura esistente."""
    x0, y0, z0 = start
    x1, y1, z1 = end
    
    # 1. Linea del corpo del vettore
    fig.add_trace(go.Scatter3d(
        x=[x0, x1], y=[y0, y1], z=[z0, z1],
        mode='lines', line=dict(color=color, width=width), name=name
    ))
    
    # 2. Punta del vettore (Cono) posizionata esattamente sulla fine (end)
    fig.add_trace(go.Cone(
        x=[x1], y=[y1], z=[z1],                 # Posizione della punta
        u=[x1-x0], v=[y1-y0], w=[z1-z0],       # Direzione del vettore
        colorscale=[[0, color], [1, color]],    # Colore solido
        showscale=False, sizemode='absolute', sizeref=width/10
    ))

def plot_point3D(fig, point, color="red", size =1, name="Vector"):
    """Aggiunge un vettore 3D (linea + punta a cono) a una figura esistente."""
    x, y, z = point
    
    # 1. Linea del corpo del vettore
    fig.add_trace(go.Scatter3d(
        x=[x], y=[y], z=[z],
        mode='markers', marker=dict(size=12, color = color), name=name,
    ))
    

def plot_sphere3d(fig, center=(0,0,0), radius=1.0, color="dimgray", name="Sphere", n=40):
    xc, yc, zc = center
    phi   = np.linspace(0, np.pi,   n)      # polar
    theta = np.linspace(0, 2*np.pi, n)      # azimuth
    phi, theta = np.meshgrid(phi, theta)    # both (n, n) — DON'T flatten

    x = xc + radius * np.sin(phi) * np.cos(theta)
    y = yc + radius * np.sin(phi) * np.sin(theta)
    z = zc + radius * np.cos(phi)

    fig.add_trace(go.Surface(
        x=x, y=y, z=z,
        colorscale=[[0, color], [1, color]],
        showscale=False,
        opacity=0.4,
        name=name,
        lighting=dict(ambient=0.4, diffuse=0.8, specular=0.2,
                      roughness=0.6, fresnel=0.2),
    ))
    
def visualize_tif(file_path, lato_pixel_vis):
    """
    Legge e visualizza solo una porzione specificata dal centro 
    del file fornito, a piena risoluzione e senza downsampling.
    """
    with rasterio.open(file_path) as src:
        # 1. Calcola il centro geometrico del file corrente (indipendentemente da quanto è grande)
        centro_x = src.width // 2
        centro_y = src.height // 2
        
        # 2. Calcola l'offset per la porzione da visualizzare
        offset_x = centro_x - (lato_pixel_vis // 2)
        offset_y = centro_y - (lato_pixel_vis // 2)
        
        # 3. Applica la finestra di ritaglio visivo e gestisce i confini del file
        finestra_visiva = Window(offset_x, offset_y, lato_pixel_vis, lato_pixel_vis)
        finestra_visiva = finestra_visiva.intersection(Window(0, 0, src.width, src.height))
        
        larghezza_effettiva = finestra_visiva.width
        altezza_effettiva = finestra_visiva.height
        
        if larghezza_effettiva <= 0 or altezza_effettiva <= 0:
            raise ValueError("La dimensione inserita per la visualizzazione non è valida.")
        
        # 4. Lettura dei pixel reali a piena risoluzione
        dem_ritagliato = src.read(1, window=finestra_visiva).astype(float)
        
        # Allinea l'orientamento verticale al GIS standard
        dem_ritagliato = np.flipud(dem_ritagliato)
        
        if src.nodata is not None:
            dem_ritagliato[dem_ritagliato == src.nodata] = np.nan
            
        # 5. Calcola le coordinate chilometriche reali dagli angoli della finestra
        x_min_metri, y_max_metri = src.transform * (offset_x, offset_y)
        x_max_metri, y_min_metri = src.transform * (offset_x + larghezza_effettiva, offset_y + altezza_effettiva)

        # Generazione vettori degli assi per Plotly
        x_km = np.linspace(x_min_metri / 1000.0, x_max_metri / 1000.0, dem_ritagliato.shape[1])
        y_km = np.linspace(y_min_metri / 1000.0, y_max_metri / 1000.0, dem_ritagliato.shape[0])

        print(f"--- 🔍 VISUALIZZAZIONE FINESTRA ---")
        print(f"Risoluzione renderizzata a schermo: {larghezza_effettiva}x{altezza_effettiva} pixel.")

        # 6. Generazione del grafico Plotly Heatmap
        fig = go.Figure(data=go.Heatmap(
            z=dem_ritagliato,
            x=x_km,
            y=y_km,
            colorscale='Earth_r',
            colorbar=dict(title="Elevazione (m)"),
            hovertemplate="X: %{x:.2f} km<br>Y: %{y:.2f} km<br>Quota: %{z:.0f} m<extra></extra>"
        ))

        # Posiziona il marker rosso sul centro esatto della porzione inquadrata
        centro_x_km = (x_km[0] + x_km[-1]) / 2
        centro_y_km = (y_km[0] + y_km[-1]) / 2
        fig.add_trace(go.Scatter(
            x=[centro_x_km], y=[centro_y_km], mode='markers',
            marker=dict(size=12, color="red", line=dict(width=2, color="white")), 
            name="Centro Vista"
        ))

        fig.update_layout(
            title=dict(
                text=f"Mappa 2D | {larghezza_effettiva}x{altezza_effettiva} px<br><span style='font-size: 13px; color: gray;'>Scala reale mostrata: {larghezza_effettiva * 20 / 1000:.2f}x{altezza_effettiva * 20 / 1000:.2f} km</span>",
                x=0.5
            ),
            xaxis=dict(title="Distanza dal Polo Sud - Asse X (km)", scaleanchor="y", scaleratio=1),
            yaxis=dict(title="Distanza dal Polo Sud - Asse Y (km)"),
            width=750, height=700,
            margin=dict(l=60, r=40, b=60, t=80)
        )

        fig.show()


def _add_antenna_frame(fig, origin, boresight, up, scale, label, bs_color):
    """Draw an antenna's local frame: boresight + h/v polarization axes.
    Uses the same convention as the engine's antenna_frame (v = cross(h, boresight))."""
    import plotly.graph_objects as go
    o = np.asarray(origin, dtype=float)
    b = np.asarray(boresight, dtype=float); b = b / np.linalg.norm(b)
    u = np.asarray(up, dtype=float);        u = u / np.linalg.norm(u)
    if abs(np.dot(b, u)) > 0.999:           # boresight ∥ up -> degenerate fallback
        u = np.array([1.0, 0.0, 0.0])
    h = np.cross(u, b); h = h / np.linalg.norm(h)
    
    # v = np.cross(h, b); v = v / np.linalg.norm(v)
    v = np.cross(b, h); v = v / np.linalg.norm(v)  # was cross(h, b)

 
    for vec, col, nm in [(b, bs_color,    f"{label} boresight"),
                         (h, "darkorange", f"{label} h (H-pol axis)"),
                         (v, "limegreen",  f"{label} v (V-pol axis)")]:
        tip = o + scale * vec
        fig.add_trace(go.Scatter3d(
            x=[o[0], tip[0]], y=[o[1], tip[1]], z=[o[2], tip[2]],
            mode="lines", line=dict(color=col, width=6),
            name=nm, showlegend=True, hoverinfo="name",
        ))
        fig.add_trace(go.Cone(
            x=[tip[0]], y=[tip[1]], z=[tip[2]],
            u=[vec[0]], v=[vec[1]], w=[vec[2]],
            sizemode="absolute", sizeref=scale * 0.3, anchor="tip",
            colorscale=[[0, col], [1, col]], showscale=False,
            showlegend=False, hoverinfo="none",
        ))


def _bounce_color_map(bounce_counts):
    """Map each distinct bounce count to a visually distinct color.

    Works for an arbitrary (unbounded) number of bounce counts: hues are
    spread evenly around the HSV wheel over whatever counts are present.
    """
    import colorsys
    counts = sorted({int(b) for b in bounce_counts})
    n = max(len(counts), 1)
    cmap = {}
    for i, b in enumerate(counts):
        r, g, bl = colorsys.hsv_to_rgb(i / n, 0.65, 1.0)
        cmap[b] = f"rgb({int(r * 255)},{int(g * 255)},{int(bl * 255)})"
    return cmap


def _clip_segment_to_box(p0, p1, lo, hi):
    """Clip segment p0->p1 to the AABB [lo, hi].
 
    Returns (q0, q1, clipped_start, clipped_end) or None if the segment lies
    fully outside the box. clipped_start/clipped_end say whether each endpoint
    was moved inward (i.e. the polyline must break there).
    """
    p0 = np.asarray(p0, float)
    p1 = np.asarray(p1, float)
    d  = p1 - p0
    t0, t1 = 0.0, 1.0
    for ax in range(3):
        if abs(d[ax]) < 1e-12:                    # segment parallel to this slab
            if p0[ax] < lo[ax] or p0[ax] > hi[ax]:
                return None
            continue
        inv = 1.0 / d[ax]
        ta  = (lo[ax] - p0[ax]) * inv
        tb  = (hi[ax] - p0[ax]) * inv
        if ta > tb:
            ta, tb = tb, ta
        t0 = max(t0, ta)
        t1 = min(t1, tb)
        if t0 > t1:
            return None
    q0 = p0 + t0 * d
    q1 = p0 + t1 * d
    return q0, q1, (t0 > 1e-9), (t1 < 1.0 - 1e-9)


def _clip_polyline_to_box(pts, lo, hi):
    """pts: (N,3). Returns (xs, ys, zs) lists ready for go.Scatter3d, with None
    separators. Empty lists mean nothing of the polyline is inside the window."""
    pts = np.asarray(pts, float)
    if pts.ndim == 1:
        pts = pts.reshape(1, -1)
    X, Y, Z = [], [], []
    open_piece = False
    for a, b in zip(pts[:-1], pts[1:]):
        res = _clip_segment_to_box(a, b, lo, hi)
        if res is None:
            if open_piece:
                X.append(None); Y.append(None); Z.append(None)
                open_piece = False
            continue
        q0, q1, clipped_start, clipped_end = res
        if (not open_piece) or clipped_start:
            if open_piece:                         # break before a re-entry
                X.append(None); Y.append(None); Z.append(None)
            X.append(q0[0]); Y.append(q0[1]); Z.append(q0[2])
            open_piece = True
        X.append(q1[0]); Y.append(q1[1]); Z.append(q1[2])
        if clipped_end:                            # left the box -> close piece
            X.append(None); Y.append(None); Z.append(None)
            open_piece = False
    return X, Y, Z


def _compute_local_window(trimesh_mesh, pos_rx, r_influence,
                          window_height=None, window_margin=None):
    v        = np.asarray(trimesh_mesh.vertices, float)
    mesh_min = v.min(axis=0)
    mesh_max = v.max(axis=0)
    pos_rx   = np.asarray(pos_rx, float)
 
    span_xy = float(np.linalg.norm(mesh_max[:2] - mesh_min[:2]))
    relief  = float(mesh_max[2] - mesh_min[2])
 
    # Track whether each dimension was set by the caller. Explicit values are
    # authoritative -> they define the exact truncation distance and are NOT
    # overridden by the RX-inclusion clamp below. Auto values stay safe (always
    # keep RX + its capture sphere visible).
    margin_auto = window_margin is None
    height_auto = window_height is None
 
    if margin_auto:
        window_margin = max(2.0 * r_influence, 0.05 * span_xy, 1.0)
    if height_auto:
        # enough to cover surface relief, the RX, its capture sphere, + headroom
        rx_above = float(pos_rx[2] - mesh_min[2]) + 2.0 * r_influence
        window_height = max(relief, rx_above, 5.0 * r_influence, 5.0)
 
    lo = np.array([mesh_min[0] - window_margin,
                   mesh_min[1] - window_margin,
                   mesh_min[2] - max(1.0, 0.1 * window_height)])
    hi = np.array([mesh_max[0] + window_margin,
                   mesh_max[1] + window_margin,
                   mesh_min[2] + window_height])
 
    # Keep RX + capture sphere visible ONLY along auto-sized dimensions, so an
    # explicit window_height / window_margin truncates exactly where asked.
    rx_lo = pos_rx - r_influence
    rx_hi = pos_rx + r_influence
    if margin_auto:
        lo[0], lo[1] = min(lo[0], rx_lo[0]), min(lo[1], rx_lo[1])
        hi[0], hi[1] = max(hi[0], rx_hi[0]), max(hi[1], rx_hi[1])
    if height_auto:
        lo[2] = min(lo[2], rx_lo[2])
        hi[2] = max(hi[2], rx_hi[2])
    return lo, hi


def visualize_with_plotly(
    trimesh_mesh, results, pos_tx, pos_rx, r_influence,
    show_edges=True, debug_mode=False, ray_id=None,
    boresight_tx=None, boresight_rx=None, up_tx=None, up_rx=None,
    frame_scale=None,
    long_distance=False,       # clip geometry into a local window above the mesh
    window_height=None,        # vertical extent above mesh floor [m]; None -> auto
    window_margin=None,        # horizontal margin around mesh/RX [m]; None -> auto
    z_exaggeration=1.0,        # >1 stretches Z so near-surface detail pops
):
    """
    Renderizza la scena 3D SBR utilizzando Plotly.
 
    Se debug_mode=True e viene fornito un ray_id, isola il percorso specifico
    e visualizza la geometria di diffrazione (spigolo e punto di impatto).
 
    long_distance=True : pensata per TX molto in alto. Ritaglia raggi, LoS e
    traiettoria di debug in una finestra locale appena sopra la mesh e fissa i
    range degli assi su quella finestra, così la geometria vicino alla
    superficie resta leggibile invece di collassare in una fetta sottile.
    Compatibile con debug_mode.
    """
    fig = go.Figure()
 
    # Local window (only needed in long-distance mode)
    win_lo = win_hi = None
    if long_distance:
        win_lo, win_hi = _compute_local_window(
            trimesh_mesh, pos_rx, r_influence, window_height, window_margin
        )
 
    def _clip(pts):
        """Return (xs, ys, zs) for a polyline: clipped in long_distance mode,
        raw otherwise."""
        p = np.asarray(pts, float)
        if not long_distance:
            return p[:, 0], p[:, 1], p[:, 2]
        return _clip_polyline_to_box(p, win_lo, win_hi)
 
    # =========================================================================
    # 1. RENDERING DELLA MESH LUNARE
    # =========================================================================
    vertices = trimesh_mesh.vertices
    faces    = trimesh_mesh.faces
    mesh_opacity = 0.2 if debug_mode else 0.5
 
    fig.add_trace(go.Mesh3d(
        x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
        i=faces[:, 0],    j=faces[:, 1],    k=faces[:, 2],
        color="dimgray",
            showscale=False,
            opacity=0.5,
            flatshading=False,
            name="Mesh",
            lighting=dict(
                ambient=0.2,
                diffuse=0.8,
                specular=0.5,
                roughness=0.5,
                fresnel=0.2
            ),
            lightposition=dict(x=1, y=1, z=-5)
        ))

 
    if show_edges:
        tri_vertices = vertices[faces]
        x_edges, y_edges, z_edges = [], [], []
        for tri in tri_vertices:
            x_edges.extend([tri[0, 0], tri[1, 0], tri[2, 0], tri[0, 0], None])
            y_edges.extend([tri[0, 1], tri[1, 1], tri[2, 1], tri[0, 1], None])
            z_edges.extend([tri[0, 2], tri[1, 2], tri[2, 2], tri[0, 2], None])
        fig.add_trace(go.Scatter3d(
            x=x_edges, y=y_edges, z=z_edges,
            mode="lines", line=dict(color="black", width=0.5),
            name="Mesh Edges", showlegend=False, hoverinfo="none", opacity=0.4,
        ))
 
    # =========================================================================
    # 2. NODI TX ED RX
    # =========================================================================
    pos_tx = np.asarray(pos_tx, float)
    pos_rx = np.asarray(pos_rx, float)
 
    tx_in_window = (not long_distance) or np.all(
        (pos_tx >= win_lo) & (pos_tx <= win_hi)
    )
    if tx_in_window:
        fig.add_trace(go.Scatter3d(
            x=[pos_tx[0]], y=[pos_tx[1]], z=[pos_tx[2]],
            mode="markers", marker=dict(size=6, color="red"),
            name="TX Node Center",
        ))
    else:
        # TX is outside the window (typically far above): keep an on-screen note
        cx = 0.5 * (win_lo[0] + win_hi[0])
        cy = 0.5 * (win_lo[1] + win_hi[1])
        fig.add_trace(go.Scatter3d(
            x=[cx], y=[cy], z=[win_hi[2]],
            mode="markers+text",
            marker=dict(size=6, color="red", symbol="diamond-open"),
            text=[f"↑ TX at Z={pos_tx[2]:.0f} m "
                  f"(+{pos_tx[2] - win_hi[2]:.0f} m above window)"],
            textposition="top center", textfont=dict(color="red", size=11),
            name="TX (above window)",
        ))
 
    fig.add_trace(go.Scatter3d(
        x=[pos_rx[0]], y=[pos_rx[1]], z=[pos_rx[2]],
        mode="markers", marker=dict(size=6, color="blue"),
        name="RX Node Center",
    ))
 
    # =========================================================================
    # 2b. ANTENNA FRAMES (boresight + h/v polarization axes)
    # =========================================================================
    if frame_scale is None:
        d = float(np.linalg.norm(pos_tx - pos_rx))
        frame_scale = 0.15 * d if d > 1e-6 else 1.0
    if long_distance:
        # 0.15*d explodes when TX is far up; cap to the window size
        win_dim = float(np.min(win_hi - win_lo))
        frame_scale = min(frame_scale, 0.2 * win_dim)
    if boresight_tx is not None and up_tx is not None and tx_in_window:
        _add_antenna_frame(fig, pos_tx, boresight_tx, up_tx, frame_scale, "TX", "crimson")
    if boresight_rx is not None and up_rx is not None:
        _add_antenna_frame(fig, pos_rx, boresight_rx, up_rx, frame_scale, "RX", "royalblue")
 
    # =========================================================================
    # 3. SFERA DI INFLUENZA RX
    # =========================================================================
    u = np.linspace(0, 2 * np.pi, 30)
    v = np.linspace(0, np.pi, 15)
    xs = r_influence * np.outer(np.cos(u), np.sin(v)) + pos_rx[0]
    ys = r_influence * np.outer(np.sin(u), np.sin(v)) + pos_rx[1]
    zs = r_influence * np.outer(np.ones(np.size(u)), np.cos(v)) + pos_rx[2]
    for i in range(xs.shape[0]):
        fig.add_trace(go.Scatter3d(
            x=xs[i, :], y=ys[i, :], z=zs[i, :],
            mode="lines", line=dict(color="cyan", width=1),
            showlegend=False, hoverinfo="none", opacity=0.3,
        ))
    for j in range(xs.shape[1]):
        fig.add_trace(go.Scatter3d(
            x=xs[:, j], y=ys[:, j], z=zs[:, j],
            mode="lines", line=dict(color="cyan", width=1),
            name="RX Capture Sphere (Wireframe)" if j == 0 else None,
            showlegend=True if j == 0 else False,
            hoverinfo="none", opacity=0.3,
        ))
 
    # =========================================================================
    # 4. LINE-OF-SIGHT
    # =========================================================================
    if results["los_segment"] is not None:
        los_pts = results["los_segment"]
        lx, ly, lz = _clip(los_pts)
        if len(lx):
            if not results["los_blocked"]:
                fig.add_trace(go.Scatter3d(
                    x=lx, y=ly, z=lz, mode="lines",
                    line=dict(color="cyan", width=6),
                    name="Line-of-Sight (Clear)",
                ))
            else:
                fig.add_trace(go.Scatter3d(
                    x=lx, y=ly, z=lz, mode="lines",
                    line=dict(color="yellow", width=4, dash="dash"),
                    name="LoS Blocked (Obstruction Point)",
                ))
 
    # =========================================================================
    # 5. CAMMINI MULTIPATH (NLOS) - BIFORCAZIONE DEBUG
    # =========================================================================
    if debug_mode and ray_id is not None:
        # --- MODALITÀ DEBUG: isola un singolo ray_id -------------------------
        target_path = None
        for p in results["nlos_paths"]:
            if ray_id in p.get("membro_raggruppamento", []):
                target_path = p
                break
 
        if target_path is None:
            print(f"Ray ID #{ray_id} non trovato nei risultati raggruppati.")
        else:
            # 1. Traiettoria principale (clipped in long-distance mode)
            mx, my, mz = _clip(target_path["points"])
            fig.add_trace(go.Scatter3d(
                x=mx, y=my, z=mz,
                mode="lines+markers", line=dict(color="magenta", width=6),
                marker=dict(size=4, color="magenta"),
                name=f"Path Family for #{ray_id}",
            ))
 
            # 2. Dettaglio di ogni rimbalzo (riflessioni e diffrazioni)
            for i, b in enumerate(target_path.get("dettaglio_rimbalzi", [])):
                p_impatto = np.asarray(b["punto_impatto"], float)
                tipo = b.get("tipo", "reflection")
 
                if tipo == "diffraction":
                    ed     = np.array(b["edge_dir"], float)
                    beta_0 = b["angolo_incidenza_deg"]
                    d_mag  = b.get("D_coef_mag", 0)
                    d_db   = -20.0 * np.log10(d_mag) if d_mag > 1e-12 else float("inf")
 
                    fig.add_trace(go.Scatter3d(
                        x=[p_impatto[0]], y=[p_impatto[1]], z=[p_impatto[2]],
                        mode="markers",
                        marker=dict(size=10, color="lime", symbol="diamond"),
                        name=f"Keller Event (B{i+1})",
                    ))
                    edge_line = np.array([p_impatto - ed * 0.5, p_impatto + ed * 0.5])
                    fig.add_trace(go.Scatter3d(
                        x=edge_line[:, 0], y=edge_line[:, 1], z=edge_line[:, 2],
                        mode="lines", line=dict(color="red", width=8),
                        name=f"Edge B{i+1}",
                    ))
                    label = f"Diff {i+1}<br>β₀: {beta_0:.1f}°<br>Loss: {d_db:.1f} dB"
                    fig.add_trace(go.Scatter3d(
                        x=[p_impatto[0]], y=[p_impatto[1]], z=[p_impatto[2] + 0.15],
                        mode="text", text=[label],
                        textfont=dict(color="lime", size=11),
                        showlegend=False, hoverinfo="none",
                    ))
                else:
                    ang_inc = b["angolo_incidenza_deg"]
                    face    = b["face_id"]
                    fig.add_trace(go.Scatter3d(
                        x=[p_impatto[0]], y=[p_impatto[1]], z=[p_impatto[2]],
                        mode="markers", marker=dict(size=6, color="orange"),
                        name=f"Reflection (B{i+1})",
                    ))
                    label = f"Refl {i+1}<br>Face: {face}<br>Inc: {ang_inc:.1f}°"
                    fig.add_trace(go.Scatter3d(
                        x=[p_impatto[0]], y=[p_impatto[1]], z=[p_impatto[2] + 0.15],
                        mode="text", text=[label],
                        textfont=dict(color="orange", size=11),
                        showlegend=False, hoverinfo="none",
                    ))
 
            # 3. HUD panel
            hud_text = (
                f"<b>SBR Diagnostic: Ray #{ray_id}</b><br>"
                f"---------------------------------<br>"
                f"<b>Total Distance:</b> {target_path['distanza_totale']:.2f} m<br>"
                f"<b>Absolute Delay:</b> {target_path['ritardo_assoluto_ns']:.2f} ns<br>"
                f"<b>Total Path Loss:</b> {target_path['path_loss_totale_db']:.2f} dB<br>"
                f"<b>Final Phase:</b> {target_path['sfasamento_totale_deg']:.1f}°<br>"
                f"<b>AoA (Az, El):</b> {target_path['aoa_azimuth_deg']:.1f}°, "
                f"{target_path['aoa_elevation_deg']:.1f}°"
            )
            fig.add_annotation(
                text=hud_text, align="right", showarrow=False,
                xref="paper", yref="paper", x=0.01, y=0.97,
                bgcolor="rgba(0,0,0,0.8)", bordercolor="cyan", borderwidth=1,
                font=dict(color="white", size=12, family="monospace"),
            )
            _title = f"[DEBUG MODE] SBR Diagnostic Mode: Ray Family ID #{ray_id}"
            if long_distance:
                _title += " — long-distance window"
 
    else:
        # --- MODALITÀ STANDARD: tutti i percorsi macroscopici ----------------
        bounce_colors = _bounce_color_map(
            [r["bounces"] for r in results["nlos_paths"] if r["bounces"] > 0]
        )
        legend_added = set()
 
        for ray in results["nlos_paths"]:
            bounces        = ray["bounces"]
            has_diffracted = ray.get("has_diffracted", False)
            pts            = np.array(ray["points"])
 
            if bounces == 0:
                continue
 
            xs_r, ys_r, zs_r = _clip(pts)
            if len(xs_r) == 0:           # nothing of this path is inside the window
                continue
 
            has_reflections = any(
                bb.get("tipo", "reflection") == "reflection"
                for bb in ray.get("dettaglio_rimbalzi", [])
            )
            if has_diffracted and has_reflections:
                color, style_key, width = "deepskyblue", f"mixed_{bounces}", 4
                label = f"{bounces} Bounce(s) — Mixed Reflection+Diffraction"
            elif has_diffracted:
                color, style_key, width = "lime", f"keller_{bounces}", 4
                label = f"{bounces} Bounce(s) — Keller Diffraction"
            else:
                color = bounce_colors.get(bounces, "white")
                style_key, width = f"reflection_{bounces}", 3
                label = f"{bounces} Bounce(s) — Pure Reflection"
            
            show_in_legend = style_key not in legend_added
            legend_added.add(style_key)
 
            fig.add_trace(go.Scatter3d(
                x=xs_r, y=ys_r, z=zs_r,
                mode="lines", line=dict(color=color, width=width),
                name=label, showlegend=show_in_legend, legendgroup=style_key,
            ))
 
        _title = ("SBR Multipath Ray Tracing Engine — Lunar Scene"
                   f" | TX-RX Distance: {(np.linalg.norm(pos_tx-pos_rx) / 1e3):2f} km "
                  + (" [DEBUG MODE]" if debug_mode else "")
                  + (" — long-distance window" if long_distance else ""))
 
    # =========================================================================
    # 6. LAYOUT  (single update_layout for both branches)
    # =========================================================================
    scene = dict(
        xaxis=dict(title="X [m]", showgrid=True),
        yaxis=dict(title="Y [m]", showgrid=True),
        zaxis=dict(title="Z [m]", showgrid=True),
        aspectmode="data",
    )
    if long_distance:
        wx = float(win_hi[0] - win_lo[0])
        wy = float(win_hi[1] - win_lo[1])
        wz = float(win_hi[2] - win_lo[2])
        base = max(wx, wy, 1e-9)
        scene["xaxis"]["range"] = [win_lo[0], win_hi[0]]
        scene["yaxis"]["range"] = [win_lo[1], win_hi[1]]
        scene["zaxis"]["range"] = [win_lo[2], win_hi[2]]
        scene["aspectmode"]  = "manual"
        scene["aspectratio"] = dict(
            x=wx / base, y=wy / base, z=(wz / base) * float(z_exaggeration)
        )
 
    fig.update_layout(
        template="plotly", title=_title, scene=scene,
        margin=dict(l=0, r=0, b=0, t=40),
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    )
 
    fig.show()


def visualize_mesh_3D(trimesh_mesh, pos_tx=None, pos_rx=None, tx_grid=None, 
                      rx_grid=None, size=3, show_edges=True, show_axes=True, vis_map = False):
    vertices = trimesh_mesh.vertices
    faces = trimesh_mesh.faces

    n_vertici   = len(vertices)
    n_triangoli = len(faces)
    x_range_km  = (vertices[:, 0].max() - vertices[:, 0].min()) / 1000
    y_range_km  = (vertices[:, 1].max() - vertices[:, 1].min()) / 1000
    z_min       = vertices[:, 2].min()
    z_max       = vertices[:, 2].max()

    titolo = (
        f"Mesh 3D Lunare | "
        f"Triangoli: {n_triangoli:,} | "
        f"Vertici: {n_vertici:,} | "
        f"Estensione: {x_range_km:.2f} x {y_range_km:.2f} km | "
        f"Z: [{z_min:.0f} m, {z_max:.0f} m]"
    )

    fig = go.Figure()

    fig.add_trace(go.Mesh3d(
            x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
            i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
            color="dimgray",
            showscale=False,
            opacity=0.5,
            flatshading=False,
            name="Mesh",
            lighting=dict(
                ambient=0.2,
                diffuse=0.8,
                specular=0.5,
                roughness=0.5,
                fresnel=0.2
            ),
            lightposition=dict(x=1, y=1, z=-5)
        ))


    def add_points(points, color, name):
        if points is not None:
            p = np.asarray(points)
            if p.ndim == 1: p = p.reshape(1, -1)
            fig.add_trace(go.Scatter3d(
                x=p[:, 0], y=p[:, 1], z=p[:, 2],
                mode="markers",
                marker=dict(size=size, color=color),
                name=name
            ))

    add_points(pos_tx, "red", "TX")
    add_points(pos_rx, "blue", "RX")

    if tx_grid is not None and len(tx_grid) > 0:
        pts = np.array([p for p in tx_grid if p is not None])
        fig.add_trace(go.Scatter3d(
            x=pts[:, 0], y=pts[:, 1], z=pts[:, 2],
            mode="markers",
            marker=dict(size=size, color="red", opacity=1),
            name="TX grid"
        ))

    if rx_grid is not None and len(rx_grid) > 0:
        pts = np.array([p for p in rx_grid if p is not None])
        fig.add_trace(go.Scatter3d(
            x=pts[:, 0], y=pts[:, 1], z=pts[:, 2],
            mode="markers",
            marker=dict(size=size, color="blue", opacity=1),
            name="RX grid"
        ))

    if vis_map:
        if pos_tx is None:
            raise ValueError("vis_map=True requires pos_tx.")

        pos_tx_arr = np.asarray(pos_tx, dtype=np.float64).reshape(3)

        C = trimesh_mesh.triangles_center.astype(np.float64)
        F = len(trimesh_mesh.faces)

        vec = C - pos_tx_arr[None, :]
        dist = np.linalg.norm(vec, axis=1)

        valid = dist > 1e-9

        dirs = np.zeros_like(vec)
        dirs[valid] = vec[valid] / dist[valid, None]

        origins = np.repeat(pos_tx_arr[None, :], F, axis=0)

        max_dist = float(dist.max() + 1.0)
        tol = 0.10

        hit_mask, hit_pts, hit_faces, hit_dists = batch_intersect(
            trimesh_mesh,
            origins,
            dirs,
            max_dist
        )

        # Pure geometric LoS blockage
        blocked_by_geometry = valid & hit_mask & (hit_dists < dist - tol)
        clear_los = valid & (~blocked_by_geometry)

        # Face orientation classification
        Nf = trimesh_mesh.face_normals.astype(np.float64).copy()

        # Physical upward copy for DEM/roof-like faces only
        N_up = Nf.copy()
        N_up[N_up[:, 2] < 0.0] *= -1.0

        abs_nz = np.abs(N_up[:, 2])

        terrain_like = abs_nz > 0.35
        wall_like = ~terrain_like

        to_tx = pos_tx_arr[None, :] - C
        to_tx_norm = to_tx / np.maximum(
            np.linalg.norm(to_tx, axis=1, keepdims=True),
            1e-12
        )

        tx_on_top_side = np.einsum("ij,ij->i", N_up, to_tx_norm) > 0.0

        reachable = clear_los & (
            wall_like |
            (terrain_like & tx_on_top_side)
        )

        not_reachable = valid & (~reachable)

        print(
            f"[TX visibility map] Reachable Faces: {reachable.sum()}/{len(reachable)} "
            f"({100.0 * reachable.mean():.1f}%)"
        )
        # print(
        #     f"[TX visibility map] Faces Not Reachable: {not_reachable.sum()}/{len(not_reachable)} "
        #     f"({100.0 * not_reachable.mean():.1f}%)"
        # )

        f_not = faces[not_reachable]
        if len(f_not) > 0:
            fig.add_trace(go.Mesh3d(
                x=vertices[:, 0],
                y=vertices[:, 1],
                z=vertices[:, 2],
                i=f_not[:, 0],
                j=f_not[:, 1],
                k=f_not[:, 2],
                color="red",
                opacity=0.5,
                showscale=False,
                name="Not reachable from TX",
                lighting=dict(
                ambient=0.2,
                diffuse=0.8,
                specular=0.5,
                roughness=0.5,
                fresnel=0.2
            ),
            lightposition=dict(x=1, y=1, z=-5)
        ))

        # f_yes = faces[reachable]
        # if len(f_yes) > 0:
        #     fig.add_trace(go.Mesh3d(
        #         x=vertices[:, 0],
        #         y=vertices[:, 1],
        #         z=vertices[:, 2],
        #         i=f_yes[:, 0],
        #         j=f_yes[:, 1],
        #         k=f_yes[:, 2],
        #         color="green",
        #         opacity=0.55,
        #         flatshading=True,
        #         showscale=False,
        #         name="Reachable from TX",
        #     ))
       
    axis_style = dict(
        backgroundcolor="#e8e8f0",
        gridcolor="#ccccdd",
        color="#333333"
    ) if show_axes else dict(
        visible=False,
        showgrid=False,
        showticklabels=False,
        showspikes=False,
        title=""
    )

    if show_edges:
        edges_x, edges_y, edges_z = [], [], []
        for face in faces:
            for i in [0, 1, 2, 0]:
                pt = vertices[face[i]]
                edges_x.append(pt[0])
                edges_y.append(pt[1])
                edges_z.append(pt[2])
            edges_x.append(None); edges_y.append(None); edges_z.append(None)

        fig.add_trace(go.Scatter3d(
            x=edges_x, y=edges_y, z=edges_z,
            mode="lines",
            line=dict(color="rgba(0,0,0,0.15)", width=1),
            name="Edges"
        ))


    fig.update_layout(
        title=dict(text=titolo, x=0.5, font=dict(size=13, color="#333333")),
        scene=dict(
            aspectmode="data",
            bgcolor="#f0f0f8",
            xaxis=axis_style,
            yaxis=axis_style,
            zaxis=axis_style,
        ),
        paper_bgcolor="#ffffff",
        plot_bgcolor="#ffffff",
        margin=dict(l=0, r=0, b=0, t=40),
        legend=dict(font=dict(color="#333333")),
        template="plotly_white"
    )

    fig.show()


def visualize_keller_diagnostics(trimesh_mesh, results, pos_tx, pos_rx, r_influence, ray_length=10, keller_index=0, show_normals=False, normal_length=0.3):
    fig = go.Figure()

    # --- 1. Rendering Mesh ---
    faces = trimesh_mesh.faces
    fig.add_trace(go.Mesh3d(
        x=trimesh_mesh.vertices[:, 0], y=trimesh_mesh.vertices[:, 1], z=trimesh_mesh.vertices[:, 2],
        i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
        color="dimgray",
            showscale=False,
            opacity=0.5,
            flatshading=False,
            name="Mesh",
            lighting=dict(
                ambient=0.2,
                diffuse=0.8,
                specular=0.5,
                roughness=0.5,
                fresnel=0.2
            ),
            lightposition=dict(x=1, y=1, z=-5)
        ))

    # --- 2. Face normals ---
    if show_normals:
        norm_x, norm_y, norm_z = [], [], []
        for centroid, normal in zip(trimesh_mesh.triangles_center, trimesh_mesh.face_normals):
            tip = centroid + normal * normal_length
            norm_x.extend([centroid[0], tip[0], None])
            norm_y.extend([centroid[1], tip[1], None])
            norm_z.extend([centroid[2], tip[2], None])
        fig.add_trace(go.Scatter3d(
            x=norm_x, y=norm_y, z=norm_z,
            mode="lines", line=dict(color="magenta", width=2),
            opacity=0.7, name="Face Normals"
        ))

    # --- 3. Nodi e Sfera RX ---
    def add_sphere(center, color, name, size=1.5):
        fig.add_trace(go.Scatter3d(
            x=[center[0]], y=[center[1]], z=[center[2]],
            mode="markers", marker=dict(size=size*5, color=color), name=name
        ))

    add_sphere(pos_tx, "red", "TX Node")
    add_sphere(pos_rx, "blue", "RX Node")

    # --- 4. Line-of-Sight ---
    if results["los_segment"] is not None:
        los = results["los_segment"]
        fig.add_trace(go.Scatter3d(
            x=los[:, 0], y=los[:, 1], z=los[:, 2],
            mode="lines", line=dict(color="cyan" if not results["los_blocked"] else "yellow", width=4),
            name="LoS"
        ))

    # --- 5. Keller event ---
    keller_events = results["keller_events"]
    if 0 <= keller_index < len(keller_events):
        event = keller_events[keller_index]
        p_diff = event["hit_point"]

        add_sphere(p_diff, "green", "Diffraction Point", size=0.6)

        e_start = event["edge_start"]
        e_end   = event["edge_end"]
        fig.add_trace(go.Scatter3d(
            x=[e_start[0], e_end[0]],
            y=[e_start[1], e_end[1]],
            z=[e_start[2], e_end[2]],
            mode="lines", line=dict(color="red", width=8), name="Diffracting Edge"
        ))

        pts = np.array(event["path_to_edge"])
        fig.add_trace(go.Scatter3d(
            x=pts[:, 0], y=pts[:, 1], z=pts[:, 2],
            mode="lines", line=dict(color="orange", width=4), name="Incoming Ray"
        ))

        edge_dir = e_start - e_end
        edge_dir = edge_dir / np.linalg.norm(edge_dir)
        incoming_dir = (p_diff - pos_tx) / np.linalg.norm(p_diff - pos_tx)
        cos_beta_0 = np.clip(np.dot(incoming_dir, edge_dir), -1.0, 1.0)
        beta_0     = np.arccos(cos_beta_0)  
        
        cone_x, cone_y, cone_z = [], [], []
        for cd in event["child_dirs"]:
            origin = p_diff + cd * 0.05
            target = origin + cd * ray_length

            c_points, _, _ = trimesh_mesh.ray.intersects_location([origin], [cd])
            end_pt = target
            if len(c_points) > 0:
                dists = np.linalg.norm(c_points - origin, axis=1)
                valid = dists > 0.05
                if np.any(valid):
                    end_pt = c_points[valid][np.argmin(dists[valid])]

            hit_rx, rx_pt = check_sphere_intersection(origin, end_pt, pos_rx, r_influence)

            cone_x.extend([origin[0], end_pt[0], None])
            cone_y.extend([origin[1], end_pt[1], None])
            cone_z.extend([origin[2], end_pt[2], None])

            if hit_rx:
                fig.add_trace(go.Scatter3d(
                    x=[origin[0], rx_pt[0]], y=[origin[1], rx_pt[1]], z=[origin[2], rx_pt[2]],
                    mode="lines", line=dict(color="lime", width=5), name="Captured Ray"
                ))

        fig.add_trace(go.Scatter3d(
            x=cone_x, y=cone_y, z=cone_z, 
            mode="lines", line=dict(color="lime", width=2), opacity=0.4, name="Keller Cone"
        ))

    fig.update_layout(title=f"Cone Angle {np.rad2deg(beta_0):.4f} deg", scene=dict(aspectmode="data"), template="plotly", showlegend=True)
    fig.show()


TERRAIN_STYLES = {
    "Flat":     {"color": "#1f77b4", "marker": "^", "ls": "-"},
    "Basin":    {"color": "#ff7f0e", "marker": "o", "ls": "--"},
    "Slope":    {"color": "#2ca02c", "marker": "s", "ls": "-."},
    "Mountain": {"color": "#d62728", "marker": "D", "ls": ":"},
}


def campaign_to_plot_input(campaign):
    """
    Converte il risultato di run_multipath_campaign nel formato
    atteso da plot_all: {"nlos_paths": [...]}

    Uso:
        results_per_terrain = {
            "Flat":     campaign_to_plot_input(campaign_flat),
            "Basin":    campaign_to_plot_input(campaign_basin),
            "Slope":    campaign_to_plot_input(campaign_slope),
            "Mountain": campaign_to_plot_input(campaign_mountain),
        }
        plot_all(results_per_terrain, frequenza=2.4e9)
    """
    return {"nlos_paths": campaign["all_paths"]}

def print_full_ray_history_2(risultati):
    """
    Stampa un report unificato, dettagliato e diagnostico per tutti i percorsi 
    multipath calcolati dal simulatore di ray-tracing.
    """
    print(f"\n{'='*95}")
    print(f"{'REPORT DETTAGLIATO E DIAGNOSTICA PERCORSI MULTIPATH':^95}")
    print(f"{'='*95}\n")
 
    for i, path in enumerate(risultati['nlos_paths']):
 
        is_los          = path['bounces'] == 0
        is_diffracted   = path.get('has_diffracted', False)
        has_reflections = any(
            b.get('tipo', 'reflection') == 'reflection'
            for b in path.get('dettaglio_rimbalzi', [])
        )
 
        if is_los:
            tag           = "[L]"
            tipo_percorso = "LoS Analitico (Diretto)"
        elif is_diffracted and has_reflections:
            tag           = "[M]"
            tipo_percorso = f"NLoS Mixed — Reflection+Diffraction ({path['bounces']} bounce(s))"
        elif is_diffracted:
            tag           = "[K]"
            tipo_percorso = f"NLoS Diffracted — Keller ({path['bounces']} bounce(s))"
        else:
            tag           = "[P]"
            tipo_percorso = f"NLoS Pure Reflection ({path['bounces']} bounce(s))"
 
        # Arrival (RX) and departure (TX) angles, global + local frames.
        aoa_az_g = path.get('aoa_azimuth_global_deg',   path.get('aoa_azimuth_deg', 0.0))
        aoa_el_g = path.get('aoa_elevation_global_deg', path.get('aoa_elevation_deg', 0.0))
        aoa_az_l = path.get('aoa_azimuth_local_deg',   float('nan'))
        aoa_el_l = path.get('aoa_elevation_local_deg', float('nan'))
        aod_az_g = path.get('aod_azimuth_global_deg',   float('nan'))
        aod_el_g = path.get('aod_elevation_global_deg', float('nan'))
        aod_az_l = path.get('aod_azimuth_local_deg',   float('nan'))
        aod_el_l = path.get('aod_elevation_local_deg', float('nan'))
        r_val = path.get("r_influence_used")
        n_micro = len(path.get("membro_raggruppamento", [])) or 1
 
        # ── Estrazione diretta dal dizionario (NO RICALCOLO) ───────────
        fsl_db       = path.get('fsl_db', 0.0)
        refl_loss_db = path.get('reflection_loss_db', 0.0)
        diff_loss_db = path.get('diffraction_loss_db', 0.0)
        gain_tx      = path.get('gain_tx_db', 0.0)
        gain_rx      = path.get('gain_rx_db', 0.0)
        # LoS stores the polarization mismatch under 'IL_db'; NLoS under 'pol_loss'
        pol_loss     = path.get('pol_loss', path.get('IL_db', 0.0))
        family_id    = path.get('ray_id', 'N/A')
 
        # Per-path budget (one representative micro-ray), end to end incl. gains
        path_budget = (fsl_db + refl_loss_db + pol_loss + diff_loss_db
                       - gain_tx - gain_rx)
 
        # Honest coherent-vs-incoherent interference of the SAME bundle:
        #   coh  = -20log10|Σ campo_i|      (fields added with phase)
        #   inc  = -20log10 sqrt(Σ|campo_i|^2)   (powers added, phase ignored)
        # interference = coh - inc  ->  0 dB for a single ray, <0 constructive, >0 destructive
        # campo_complesso is now the AVERAGE over the bundle; the coherent SUM
        # is n_micro * campo. Compare coherent-sum vs incoherent-sum magnitude.
        coh_mag = n_micro * abs(path['campo_complesso'])
        P_inc   = path.get('potenza_incoerente', abs(path['campo_complesso']) ** 2)
        inc_mag = np.sqrt(P_inc)
        coh_loss = -20.0 * np.log10(coh_mag) if coh_mag > 1e-15 else float('inf')
        inc_loss = -20.0 * np.log10(inc_mag) if inc_mag > 1e-15 else float('inf')
        interference_db = coh_loss - inc_loss
 
        # ── Stampe principali ─────────────────────────────────────────
        print(f"--- PERCORSO #{i} {tag} | {tipo_percorso} | Family ID #{family_id} ---")
        if not is_los:
            print(f"  Composizione SBR : {n_micro} micro-raggio/i -> 1 componente coerente")
        print(f"  Distanza totale  : {path['distanza_totale']:.2f} m")
        r_str = f"{r_val:.6f} m" if r_val is not None else "N/A (LoS deterministico)"
        print(f"  R Influence Used : {r_str}")
        print(f"  Ritardo assoluto : {path['ritardo_assoluto_ns']:.2f} ns")
        print(f"  Fase segnale     : {path['sfasamento_totale_deg']:.1f}°")
        print(f"  |Campo|          : {abs(path['campo_complesso']):.6e}")
 
        # ── Budget di perdita (un singolo micro-raggio rappresentativo) ─
        print(f"  Budget di perdita (per micro-raggio):")
        print(f"     FSL            : {fsl_db:8.2f} dB")
        if not is_los:
            print(f"     Riflessione    : {refl_loss_db:8.2f} dB")
        print(f"     Polarizzazione : {pol_loss:8.2f} dB")
        if abs(diff_loss_db) > 1e-9:
            print(f"     Diffrazione    : {diff_loss_db:8.2f} dB")
        print(f"     Guadagni Ant.  : {-(gain_tx + gain_rx):+8.2f} dB   "
              f"(TX {gain_tx:+.2f} | RX {gain_rx:+.2f} dBi)")
        print(f"     {'-'*28}")
        print(f"     Perdita path   : {path_budget:8.2f} dB")
 
        # ── Interferenza del bundle (onesta: coerente vs incoerente) ───
        if is_los or n_micro <= 1:
            print(f"  Interferenza SBR :    +0.00 dB   (raggio singolo: nessuna interferenza)")
        else:
            tipo_int = ("costruttiva" if interference_db < -0.05
                        else "distruttiva (fading)" if interference_db > 0.05
                        else "trascurabile")
            print(f"  Interferenza SBR : {interference_db:+8.2f} dB   "
                  f"({n_micro} raggi combinati coerentemente -> {tipo_int})")
                
        print(f"  Angoli Partenza (TX) [global = travel dir | local = vs boresight]:")
        print(f"     Globale : Azimuth {aod_az_g:>7.1f}°, Elevation {aod_el_g:>7.1f}°")
        print(f"     Locale  : Azimuth {aod_az_l:>7.1f}°, Elevation {aod_el_l:>7.1f}°")
        print(f"  Angoli Arrivo   (RX) [global = travel dir | local = came-from vs boresight]:")
        print(f"     Globale : Azimuth {aoa_az_g:>7.1f}°, Elevation {aoa_el_g:>7.1f}°")
        print(f"     Locale  : Azimuth {aoa_az_l:>7.1f}°, Elevation {aoa_el_l:>7.1f}°")
 
        # ── Cronologia Rimbalzi ───────────────────────────────────────
        if not is_los:
            print("  Cronologia Rimbalzi:")
            for j, bounce in enumerate(path['dettaglio_rimbalzi']):
                p             = bounce['punto_impatto']
                face          = bounce['face_id']
                tipo          = bounce.get('tipo', 'reflection')
                ang_incidenza = bounce['angolo_incidenza_deg']
                ang_grazing   = 90.0 - ang_incidenza
 
                if tipo == 'diffraction':
                    ed_dir = bounce.get('edge_dir', [0, 0, 0])
                    d_mag  = bounce.get('D_coef_mag', float('nan'))
                    d_ph   = bounce.get('D_coef_phase_deg', float('nan'))
                    d_db   = -20.0 * np.log10(d_mag) if d_mag > 1e-12 else float('inf')
                    print(f"    -> Evento {j+1}: [DIFFRAZIONE KELLER]")
                    print(f"       - Punto Impatto (Edge)     : [{p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f}]")
                    print(f"       - Edge Dir                 : [{ed_dir[0]:.3f}, {ed_dir[1]:.3f}, {ed_dir[2]:.3f}]")
                    print(f"       - β₀ (incidenza su edge)   : {ang_incidenza:.1f}°")
                    print(f"       - |D|                      : {d_mag:.6f}  ({d_db:.2f} dB)")
                    print(f"       - Phase(D)                 : {d_ph:.1f}°")
                else:
                    print(f"    -> Rimbalzo {j+1}: [RIFLESSIONE]")
                    print(f"       - Face ID                  : {face}")
                    print(f"       - Punto Impatto            : [{p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f}]")
                    print(f"       - Angolo Incid. (Normal)   : {ang_incidenza:.1f}°")
                    print(f"       - Angolo Grazing (Surface) : {ang_grazing:.1f}°")
                    rte = bounce.get('R_TE')
                    rtm = bounce.get('R_TM')
                    if rte is not None and rtm is not None:
                        print(f"       - Coeff. Fresnel R_TE      : {rte.real:+.3f}{rte.imag:+.3f}j  (|R|={abs(rte):.3f})")
                        print(f"       - Coeff. Fresnel R_TM      : {rtm.real:+.3f}{rtm.imag:+.3f}j  (|R|={abs(rtm):.3f})")
                    rl = bounce.get('refl_loss_db')
                    if rl is not None:
                        print(f"       - Reflection Loss          : {rl:.2f} dB")
                    pb = bounce.get('pol_before')
                    pa = bounce.get('pol_after')
                    if pb is not None and pa is not None:
                        print(f"       - Polarizzazione           : {pb} (AR {bounce.get('ar_before_db', float('nan')):.1f} dB) "
                              f"-> {pa} (AR {bounce.get('ar_after_db', float('nan')):.1f} dB)")
        else:
            print("  Stato            : Percorso Diretto LoS (Nessun rimbalzo)")
 
        print("-" * 75 + "\n")
 
    print(f"{'='*95}\n")


def _los_reference_angles(pos_tx, pos_rx):
    """AoA (az, el) at RX of the direct TX->RX direction, in degrees.
    Matches the engine's LoS convention: arrival direction = pos_tx - pos_rx."""
    d = np.asarray(pos_tx, float) - np.asarray(pos_rx, float)
    n = np.linalg.norm(d)
    if n < 1e-12:
        return 0.0, 0.0
    ref_az = np.degrees(np.arctan2(d[1], d[0]))
    ref_el = np.degrees(np.arcsin(np.clip(d[2] / n, -1.0, 1.0)))
    return ref_az, ref_el


def _wrap180(a):
    """Wrap an angle (deg) to (-180, 180]."""
    return (a + 180.0) % 360.0 - 180.0


def _extract_arrays(campaign_results):
    """Pull flat arrays from raw campaign results."""
    delay_ns, power_lin = [], []
    aoa_az_rel, aoa_el_rel = [], []
    rms_ds_list = []

    for entry in campaign_results:
        paths = entry["result"]["nlos_paths"]

        # Per-link LoS reference direction (relative AoA is measured from this)
        ref_az, ref_el = _los_reference_angles(entry["pos_tx"], entry["pos_rx"])

        pair_delays, pair_powers = [], []

        for p in paths:
            campo = complex(p["campo_complesso"])
            e2 = abs(campo) ** 2                       # = path power |campo|^2

            delay_ns.append(p["ritardo_assoluto_ns"])
            power_lin.append(e2)

            # FIX 2: relative AoA (Δα wrapped to ±180°, Δβ as difference)
            aoa_az_rel.append(_wrap180(p["aoa_azimuth_deg"] - ref_az))
            aoa_el_rel.append(p["aoa_elevation_deg"] - ref_el)

            # collect NLoS only for RMS-DS (as in the original draft)
            if p["bounces"] > 0:
                pair_delays.append(p["ritardo_assoluto_ns"])
                pair_powers.append(e2)

        # RMS-DS per link (paper eq. 11-12): power-weighted second moment of delay
        if len(pair_delays) > 1:
            d = np.array(pair_delays)
            w = np.array(pair_powers)                  # FIX 1: weight = power (NOT power**2)
            w = w / w.sum()
            tau_mean = np.dot(w, d)
            rms_ds = float(np.sqrt(max(np.dot(w, d ** 2) - tau_mean ** 2, 0.0)))
            rms_ds_list.append(rms_ds)

    return (
        np.array(delay_ns),
        np.array(power_lin),
        np.array(aoa_az_rel),
        np.array(aoa_el_rel),
        np.array(rms_ds_list),
    )

def plot_pattern_2D(path, coel=45):
    pat = pattern_from_grap(path)
    az = np.linspace(0, 360, 5000)

    # ---- azimuth cut at chosen coelevation + its peak ----
    gains = pat(np.full_like(az, coel), az)
    cut_max = gains.max()
    az_cut_peak = az[gains == cut_max]            # azimuth(s) of the cut's peak

    fig = go.Figure(go.Scatterpolar(r=gains, theta=az, mode="lines"))
    fig.add_trace(go.Scatterpolar(
        r=[cut_max]*len(az_cut_peak), theta=az_cut_peak, mode="markers",
        name=f"cut max ({cut_max:.2f} dBW)",
        marker=dict(color="red", size=10, symbol="circle")))
    fig.update_layout(
        title=f"EIRP azimuth cut at coel = {coel:.0f}°",
        polar=dict(radialaxis=dict(title="EIRP [dBW]", range=[-30, 30]),
                   angularaxis=dict(rotation=90, direction="clockwise")))
    fig.show()

    # ---- global max from the grid's OWN axes ----
    i_th, i_ph = np.unravel_index(np.argmax(pat.grid), pat.grid.shape)
    coel_max, az_max, gmax = pat.theta[i_th], pat.phi[i_ph], pat.grid.max()
    print(f"Global max {gmax:.2f} dBW @ Co-Elev: {coel_max:.1f}° | Az: {az_max:.1f}°")

    # ---- 3D balloon + arrow to the global max ----
    G  = pat.grid
    TH = np.deg2rad(pat.theta)[:, None]; PH = np.deg2rad(pat.phi)[None, :]
    r  = G - G.min()
    X = r*np.sin(TH)*np.cos(PH); Y = r*np.sin(TH)*np.sin(PH); Z = r*np.cos(TH)
    fig = go.Figure(go.Surface(x=X, y=Y, z=Z, surfacecolor=G, colorscale="Turbo",
                               colorbar=dict(title="EIRP [dBW]")))

    th, ph = np.deg2rad(coel_max), np.deg2rad(az_max)
    L = 1.15 * r.max()
    x_max = L*np.sin(th)*np.cos(ph); y_max = L*np.sin(th)*np.sin(ph); z_max = L*np.cos(th)
    plot_vector3d(fig, [0, 0, 0], [x_max, y_max, z_max], 'red', width = 15)

    fig.update_layout(title="GRAP E1 EIRP - 3D balloon", scene=dict(aspectmode="data"))
    fig.show()

    